### ISSUE TITLE
Audio track selection?

### ISSUE THREAD

**Issue by AsuraAce** [killergerbah/asbplayer#101]
Is it possible to change the audio track (sorry couldn't find anything)? 

If not, is it because of the limitation of a browser based player or is it a planned feature?

**Comment by killergerbah** [comment]
In the README you will find a section that shows you how to enable audio track selection through an experimental Chrome feature.
There's currently a bug where the selected audio track may not be the one that's used for flashcards however.

**Comment by AsuraAce** [comment]
Thank you. 

Works fine with the web player, but it seems the Anki export (Alt + Shift + Q) defaults to the first track.

- couldn't find a way to change the track within the Anki export.
- would be nice if asbplayer defaults to the active audio track (if possible).

**Comment by killergerbah** [comment]
Yeah there's a bug that needs to be fixed so that the correct audio track is used for flashcards but the UI could be improved as well to include a selection.

**Comment by killergerbah** [comment]
Linking the related bug https://github.com/killergerbah/asbplayer/issues/105

**Comment by killergerbah** [comment]
Closing this issue as audio track selection is implemented. The https://github.com/killergerbah/asbplayer/issues/105 needs to be fixed however.
