### ISSUE TITLE
Regex filter for "sentence" text when exporting to Anki

### ISSUE THREAD

**Issue by killergerbah** [killergerbah/asbplayer#106]
For example, it would be nice to be able to remove the name of the speaker that's commonly found in parentheses at the beginning of some subtitles. See https://github.com/killergerbah/asbplayer/issues/103

**Comment by fr1edrik** [comment]
Not really sure if its according to this issue or the mentioned below, but I added a button for hiding the speaker when exporting (so its includes the regex).

https://github.com/killergerbah/asbplayer/pull/129
