### ISSUE TITLE
Can't export audio to flashcards

### ISSUE THREAD

**Issue by SonnyAu** [killergerbah/asbplayer#108]
So for the audio field when I export it, it just gives me "You must provide a "data", "path", or "url" field." How do I fix this?

Additionally, for the dropdown menus, I don't have the field types that the video has and I'm not where to get them(Ex. Sentence, Definition, Word, Audio).
![Dropdown](https://user-images.githubusercontent.com/81658408/146971575-dcbe5406-4a3c-44b5-a5f3-cb9312521933.jpg)

**Comment by killergerbah** [comment]
@SonnyAu Please select a `Note Type` from the drop down menu. This will populate the remaining drop down menus with fields from the note type.

**Comment by killergerbah** [comment]
@SonnyAu Closing this. Feel free to re-open if you're still experiencing the problem.
