### ISSUE TITLE
Request: Allow capturing of the current subtitle and the next subtitle

### ISSUE THREAD

**Issue by YeezyYeezyWhatsGood** [killergerbah/asbplayer#109]
Often times one subtitle has half a sentence and the next has the next has the next half of a sentence and it would be nice if there was a keybind that would capture both as one line. ie I am watching overlord and came across the line
144
00:10:36,385 --> 00:10:39,347 
（アルベド）
この失態を払拭する機会を
いただけるのであれば―

145
00:10:40,014 --> 00:10:42,266 
これに勝る喜びはございません
It would really be nice if I could combine these without editing the subtitle file or not using the subtitle file and timing things manually. Maybe make the default keybind ctrl+shift+x+2 or something I'm not sure.

**Comment by killergerbah** [comment]
The range selection slider in the Anki export dialog is supposed to solve this problem. Are you asking for an even faster way to capture adjacent subtitles?

This is how to use the slider:
![asbplayer-help-20210102](https://user-images.githubusercontent.com/2254858/147882525-ef595acd-66b9-493a-9a74-19775799f59d.jpg)

**Comment by killergerbah** [comment]
I will plan to add documentation for the range selection feature as the feature is not obvious to users.

**Comment by killergerbah** [comment]
Documented here https://github.com/killergerbah/asbplayer#adjusting-anki-flashcards
