### ISSUE TITLE
Request: prevent playback bar and other elements from appearing when moving mouse

### ISSUE THREAD

**Issue by Timc168** [killergerbah/asbplayer#110]
I'm currently using this in full screen mode with 2 subtitles and hovering over words with yomichan to see definition. But the playback buttons and bar keep popping up as im doing this. Could a feature be implemented so that either the elements are toggleable with a hotkey or only appear when hovering below a certain point.

**Comment by killergerbah** [comment]
193db8aea04c3b1ac175373c2aef4fc9be818137
