### ISSUE TITLE
Request: Adding pitch accent from Yomichan, in Anki export 

### ISSUE THREAD

**Issue by jhyl22** [killergerbah/asbplayer#116]

**Comment by killergerbah** [comment]
@jhyl22 Can you elaborate on how exactly a feature like this would work? What would you like that Yomichan with a dictionary like スーパー大辞林 doesn't provide?

**Comment by jhyl22** [comment]
I am not too familiar with スーパー大辞林, but I am aware that with other other sentence mining workflows, such as using animebook, there is the possibility of adding pitch patterns (via the Kanjium pitch accents library imported into Yomichan) to cards, as well as changing the colour of the word depending on the pitch pattern. 
I suppose that in order for this feature to work, there would need to be the option to add words and definitions automatically in asbplayer (for example this can be done in animebook). 
Here is a demo of animebook for reference:
![demo](https://user-images.githubusercontent.com/66427894/150214686-e154a44c-f4ca-44d6-be99-22a11ab55da8.gif)

**Comment by killergerbah** [comment]
@jhyl22 I think the only feature in that gif that asbplayer doesn't implement already is a keyboard shortcut to update the last card with media.

This is what's happening in the gif:
1. Word is highlighted with Yomichan.
2. Card is exported using the + button next to the definition.
3. Keyboard shortcut is used to update last exported card with screenshot and audio.
4. 
I'm not exactly sure how the pitch accent is being rendered so nicely in the card, but that should be possible to setup entirely with Yomichan and Anki.

A similar flow that's possible with asbplayer:
1. Word is highlighted with Yomichan.
2. Keyboard shortcut is used to open Anki export dialog.
3. Card is exported using the + button next to the definition.
4. 'Update last card' button is used to update the last exported card with screenshot and audio.

**Comment by jhyl22** [comment]
Ah, I never knew about the 'Update last card' feature, thank you so much for raising that to my attention! With that, I'm completely happy with asbplayer, because now I can add pretty much everything I need with two clicks. Thank you so much!
