### ISSUE TITLE
Subtitle not displaying correctly

### ISSUE THREAD

**Issue by Staz0r** [killergerbah/asbplayer#123]
17.0
Subtitle is centered to the middle of display screen instead of the video player

**Comment by killergerbah** [comment]
Hi @Staz0r can you provide more info? For example: what site you're seeing this on, maybe a screenshot?

**Comment by Staz0r** [comment]
- Youtube
![image](https://user-images.githubusercontent.com/51358327/155868955-1a7e3889-d1d0-4ab3-ae33-5cdf7bf853dc.png)

- Zoro (Im using the watch2gether feature as the video player is aligned to the left to show you how the subtitle interact with the player)
![image](https://user-images.githubusercontent.com/51358327/155869204-b3310fe8-719d-4fd0-b260-04ebeb359f89.png)

**Comment by Staz0r** [comment]
No problem, I know that most people watches them in full screen mode. But I usually watch things with the tab split in half so that I could open another window to do something else

**Comment by killergerbah** [comment]
bf0747d87a711e667c99bac593ac5f705c003ee6
