### ISSUE TITLE
Setting not saving

### ISSUE THREAD

**Issue by OltiP2** [killergerbah/asbplayer#127]
On chrome i always used the extension and it worked great and always saved my anki setting but i wanted to play x 256 videos so i installed chromium i set up everything like in chrome but when i close the window and relaunch chromium and go the asb website my setting don't get saved like my anki settings but in chrome it always saved my settings

**Comment by killergerbah** [comment]
Can you check that chromium is allowed to save data at chrome://settings/cookies ?
Can you also check for any logs in the developer console when opening and closing the settings popup?
You can check logs by going to menu -> other tools -> developer console

**Comment by OltiP2** [comment]
I went on the cookies settings and turned on cookies and turned off Clear cookies and site data when you close all windows its working now thank you
