### ISSUE TITLE
Skip video by 10 seconds with left and right arrow or A/D key

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#130]
you can't skip forward or backward with the left and right arrows because the two keys are bound to seek to previous/next subtitle, I love this future and I'm using it a lot (seek to previous/next subtitle) but it would be nice if you could change it from left and right arrows to any other keys that you want. let's say I wanna change it to A/D key to seek to previous/next subtitle, that way you can skip forward and backward 10 seconds like normally you do on Netflix and Youtube

**Comment by nzarbayezid** [comment]
@killergerbah 

https://user-images.githubusercontent.com/101425664/163699767-ab91c17b-1622-449e-b866-84245b285ad8.mp4

**Comment by killergerbah** [comment]
Will be in next release
