### ISSUE TITLE
Can't make cards for videos without subtitles

### ISSUE THREAD

**Issue by YeezyYeezyWhatsGood** [killergerbah/asbplayer#132]
For some reason recently when I try to press ctrl+shift+x or ctrl+shift+c to make cards for videos without subtitles it won't work. Should I reinstall the extensions? I can make the asbplayer popup appear through ctrl+shift+f but ctrl+shit+x afterwards does nothing. Here's a screenshot of my shortcuts.
![image](https://user-images.githubusercontent.com/28869518/161722827-fe3c1abf-65d7-4688-a5b5-3e00bffb768b.png)
Edit: For context this is with youtube videos.

**Comment by killergerbah** [comment]
@YeezyYeezyWhatsGood So it used to work? Just to confirm, when you use Ctrl+Shift+C or Ctrl+Shift+X the blinking recording icon doesn't appear on the tab and even if you use either shortcut twice, nothing happens?

**Comment by killergerbah** [comment]
@YeezyYeezyWhatsGood It was a bug in the asbplayer code that I accidentally deployed a couple days ago. If you can, please let me know that you are no longer seeing the issue.

**Comment by YeezyYeezyWhatsGood** [comment]
Thank you for fixing the issue it is all fixed! 

P.S. asbplayer has been tremendously helpful in my journey learning Japanese. You are the GOAT!

**Comment by killergerbah** [comment]
Great!
And glad it's helping!
