### ISSUE TITLE
Your file couldn’t be accessed

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#135]
it is happening to me since yesterday, I deleted it and reinstalled it again but couldn't fix it

![image](https://user-images.githubusercontent.com/101425664/163300788-12ab4e28-e32f-4595-840c-3c80ff57bf2a.png)
![image](https://user-images.githubusercontent.com/101425664/163300812-1cd662d7-1821-43fd-acda-ec2b69302b2d.png)

**Comment by killergerbah** [comment]
@nzarbayezid can you paste a screenshot here of the folder where you saved the extension?

**Comment by nzarbayezid** [comment]
> @nzarbayezid can you paste a screenshot here of the folder where you saved the extension?

I just looked for the folder and it was in the temp folder, so I immediately knew that I should not have dragged and dropped the zip file in google, cuz that way it will install the extension in a temp folder that way when I clean my computer it will also delete the extension also :D
my bad I'm gonna unzip and change the folder for the extension
thanks
