### ISSUE TITLE
one little tweak can make a big difference!

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#137]
First of all thanks for the last update, it was perfect, I have one little request, both [Immerse With Migaku](https://chrome.google.com/webstore/detail/immerse-with-migaku-beta/acpchjgielgmkgkplljakcibfbjjppbk) and [Language Reactor](https://chrome.google.com/webstore/detail/language-reactor/hoombieeljmmljlkjmnheibnpciblicm)
 have the future to Seek to previous/next subtitle, but one thing that all of them have in common is that they use "Seek backward/forward by 10 Sec Left/Right and Seek to previous/next subtitle A/D" maybe you think it's not important, but it is, let me tell you how, some of the pc users are playing games so they used to use the AWSD keys, and we are using this extension cuz we want to learn languages, that meaning we use the Seek to previous/next subtitle a lot, the easiest keys to do that are A/D not Left/Right cuz in order to press Left/Right you have to let go the mouse, doing this one time is okay but for hundred times is annoying, cuz we always go back to the previous subtitle If we don't understand the line so we are always using the Seek to the previous subtitle and with the other hand grabbing the mouse in order to search and select the word that we don't know.
 what I'm saying is that all the extensions using these Keybinds that I mentioned, I hope you can change that and don't worry about the users they will get used to the new Keybinds cuz they are better, or maybe you can let us change they Keybinds ourself, this one I think takes a lot of coding, and changing the 5 sec to 10 sec is way better cuz youtube and Netflix are using that amount by default.

I gotta say without doubt your extension is really smooth with Netflix and Youtube

![image](https://user-images.githubusercontent.com/101425664/165355273-de920af9-6ab6-4cb8-b6b8-68e1006ade61.png)

![image](https://user-images.githubusercontent.com/101425664/165355425-1fc10bb5-4fad-48d5-98cd-ff8c6b3ac2ff.png)

**Comment by killergerbah** [comment]
Thanks for the suggestion, it's easy to change the back/forward offset to 10 seconds but I'd prefer to change the bindings only if there's a way to easily change back to the original ones or at least let people know that the bindings changed.

**Comment by nzarbayezid** [comment]
trust me bro they will used to it and it is better. at the end, it's your call if you wanna change it or not

**Comment by killergerbah** [comment]
Thanks I went ahead and changed the interval to 10 seconds. There's another ticket for customizable key binds (https://github.com/killergerbah/asbplayer/issues/94) that should take care of your other request.
