### ISSUE TITLE
mkv mute

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#140]
even with the experimental web platform features the audio is muted, is that something normal or it should play audio?

I tried it both on google chrome and Microsoft edge, none of them have audio, but I was able to make Microsoft edge play X265.
I really to be able to play mkv also

**Comment by killergerbah** [comment]
@nzarbayezid Really depends on the browser. Different mkv files can have different audio encodings. I've had the most success with Microsoft Edge and the paid HEVC support. In the README you'll find a link to the animebook readme which has more info about browsers and their compatibility with video/audio formats.
