### ISSUE TITLE
After clicking "Export" button in "Anki export" dialog just freezes and nothing happen

### ISSUE THREAD

**Issue by Arey125** [killergerbah/asbplayer#142]

**Comment by killergerbah** [comment]
@Arey125 can you provide more details?
What exactly are you doing when this issue occurs? What site, keyboard shortcut? Could you maybe record a video? Thanks!

**Comment by killergerbah** [comment]
> Here is the video https://user-images.githubusercontent.com/46898072/168992787-171f883a-182f-4ce9-b7a8-6678fedc1701.mp4

@Arey125 Thanks! This looks like a bug. Do you mind opening the developers console and pasting what logs you see there when this issue happens?

**Comment by killergerbah** [comment]
Closing this as it has no updates.
I've seen this happen on a Mac where the AnkiConnect server doesn't respond if Anki is backgrounded for a while.
