### ISSUE TITLE
Feature request: Make subtitles blurry

### ISSUE THREAD

**Issue by KairozSS** [killergerbah/asbplayer#143]
I think it would be great to be able to make the subtitles blurry like this:
![image](https://user-images.githubusercontent.com/23144233/170291179-38ac775a-ea80-4580-9f37-4daad99dbb6f.png)

At least I find this feature useful myself.

**Two ways to do this:**
You could be able to do this with the current implementation of asb player **if you were allowed to change the opacity of the text with the CSS rgba function**.
![image](https://user-images.githubusercontent.com/23144233/170292942-0b5da060-5710-4bb9-aa58-cf40b4712f9b.png)
You set the opacity of the subtitle text to 0 and then you set the "Subtitle Outline Thickness" to anything between 10 and 15. I see this property is controlled by the text-shadow CSS property.

The other way would be making a CSS "blurry" class like this one:
```
.blurry {
        color: rgba(0,0,0,0);
	text-shadow: 0 0 14px #ffffff;
}
```
And apply it to the tag that containts the subtitles when the user press a designated key.
Another way would be cycling through with the "S" key like this: Show subtitles -> Blurry Subtitles -> Hide Subtitles -> Show Subtitles.

**Comment by killergerbah** [comment]
Thanks for the suggestion - can you help me understand why you would find a feature like this useful? To me, it seems like hide/show subtitles is sufficient.

**Comment by KairozSS** [comment]
I used to do this exercise where you showed me a blurry subtitle line and I replayed the audio of that line several times until I felt confident enough to tell what that line said. And I would do that for every subtitle line in the video.

The reason I find difficult to do this in asbplayer it is because I can't tell when the current subtitle line ends. I have to press left arrow and right arrow several times to figure out the end of the subtitle line and the start of the next while they are hidden. If I show the subtitles so I can know where the current line ends, I will end up reading the line and it defeats the whole point of the exercise.

Sometimes when I'm mining, I end up mining the wrong subtitle line, because the word I wanted to mine happened to be at the very end of the line, so I end up mining the next line which doesn't contain the word. But for this one, you could argue that before mining you should pause, show the subtitles and make sure you are mining the right line. Although in this process, you will end up reading what the next line says.

What I want is a way to know when a subtitle line ends without knowing the actual content of the subtitles, and blurry subtitles solves that.

**Comment by killergerbah** [comment]
That makes sense.
Until this feature is implemented - as a workaround, you can use the down arrow to seek to the beginning of the current subtitle. In your case, once you've finished listening to the line you can try down, and if that doesn't work then press left. This should put you at the beginning of the line again.
