### ISSUE TITLE
how to get the Netflix font?

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#146]
the Netflix font is so much easier for reading and it's bold, so is there any way I get that on the Asbplayer?
is there any way that I can get the same font as asbplayer but with bold?

![Netflix (1)](https://user-images.githubusercontent.com/101425664/172726411-ce3ad02b-af05-4e96-8da7-ff610622d0cb.jpg)

**Comment by killergerbah** [comment]
There isn't currently a way to change the font weight but you can choose a font family from the asbplayer settings under Video Subtitles Appearance.

You could try installing a font that you want to use and then setting the subtitle font family to that.
