### ISSUE TITLE
One little future that makes the extension faster while sentence mining

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#147]
I love how fast your extension work hopefully we can make it better

https://user-images.githubusercontent.com/101425664/173694039-80134633-317e-431b-86b6-99e104ba58fd.mp4

**Comment by killergerbah** [comment]
Hey thanks for pointing out all these little details. I'll consider this a bug in the website.

**Comment by killergerbah** [comment]
b9d82564d84d0f6c3d7419c13e1ef3fd73ab1f68

**Comment by killergerbah** [comment]
The website has been updated with this fix.
