### ISSUE TITLE
a bug that wont let you have space between the sentence

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#148]
I could explain this bug with only one video, be I thought with these 2 boring videos you can understand the problem and hopefully fix it in near future, sorry for my English and the boringness in my videos :D

1

https://user-images.githubusercontent.com/101425664/173699840-bd3b56d8-9cf8-466b-93ce-67322f1e5d18.mp4

2

https://user-images.githubusercontent.com/101425664/173699619-3ad8e546-b148-42cd-a6d4-6137cd7d4c2b.mp4

**Comment by killergerbah** [comment]
Thanks, I think I know where the issue is. As you pointed out, it's likely a problem with the custom fields. Really good find.

**Comment by killergerbah** [comment]
26e56a1d3aab24be20f4ec5bc54565ab16790e35

**Comment by killergerbah** [comment]
The website has been updated with this fix.
The next extension release will include this fix.
