### ISSUE TITLE
Bug with "apply selection" for the sentence field

### ISSUE THREAD

**Issue by bcatalfo** [killergerbah/asbplayer#150]
You have to press enter to get it to update correctly
Steps to reproduce:
1) ctrl+shift+x mine a line of dialogue
2) expand the slider to include the next line
3) Click the "apply selection" on the audio field to rerecord (turns out this step is vital to reproducing the bug)
4) click the "apply selection" check mark at the right edge of the sentence field
5) notice it doesn't update but does if you go in the sentence field and press enter

**Comment by killergerbah** [comment]
Thank you for reporting this.

**Comment by killergerbah** [comment]
@YeezyYeezyWhatsGood What version of the extension are you on?

**Comment by YeezyYeezyWhatsGood** [comment]
I am on version 0.18.2

**Comment by killergerbah** [comment]
I'm not able to reproduce this at the moment. I'll keep an eye out for it though.

**Comment by apache1123** [comment]
I am on 0.19.0 and also encountered this. Here's a clip (I think the video & audio are disabled by DRM):

https://user-images.githubusercontent.com/4437157/181007666-e4b1afbb-b039-4db8-98cc-127328257b0c.mp4

I think the first time I encountered this, the sentence field "apply selection" check mark wasn't even clickable after clicking on the audio field "apply selection" check mark, but I wasn't able to reproduce that the subsequent times.

Hope that helps

**Comment by killergerbah** [comment]
I am reproducing this regularly. Haven't been able to find the fix though.
