### ISSUE TITLE
Keyboard shortcut custom keybinds

### ISSUE THREAD

**Issue by ChubYee** [killergerbah/asbplayer#152]
I want to be able to bind the keys to my liking, because right now in my workflow, I'm having to go back and forth with either my left hand or right hand to click the arrow keys to go to previous/next subtitle line, or repeat subtitle line. I want to change the binds to Q, W and E to make it more efficient

**Comment by killergerbah** [comment]
There's an issue for this in the backlog already. It's a difficult task, so probably not coming soon.

**Comment by nzarbayezid** [comment]
I don't know if you remember but I already mentioned that most people prefer to seek forward subtitles with the A and D for more efficient

**Comment by killergerbah** [comment]
@nzarbayezid Yeah I remember. To implement something like this I might think about implementing preset control schemes that include the bindings you mentioned.

**Comment by killergerbah** [comment]
Duplicated by https://github.com/killergerbah/asbplayer/issues/94

**Comment by killergerbah** [comment]
@nzarbayezid I have a build that supports custom binds, let me know if you want to test it out

**Comment by nzarbayezid** [comment]
That's a good news thanks, yeah i wanna test it out

**Comment by killergerbah** [comment]
@nzarbayezid I've attached the build to this message. Open the settings and change the asbplayer URL to https://killergerbah.github.io/asbplayer-staging/. You can configure shortcuts there.
[asbplayer-extension-0.21.0-snapshot2.zip](https://github.com/killergerbah/asbplayer/files/9730530/asbplayer-extension-0.21.0-snapshot2.zip)

**Comment by killergerbah** [comment]
I've gone ahead and made an official release so you can use that one: https://github.com/killergerbah/asbplayer/releases/tag/v0.21.0

But as always if you find any issues feel free to let me know.

**Comment by nzarbayezid** [comment]
i cant configure shortcuts

![image](https://user-images.githubusercontent.com/101425664/194767542-3585d996-ae7a-45b2-a6ba-c1ccc96b939d.png)

**Comment by killergerbah** [comment]
@nzarbayezid yeah you have to do it from the site
![image](https://user-images.githubusercontent.com/2254858/194994097-0800a4a1-61a5-4ee7-8e23-cb64a7fe3775.png)
