### ISSUE TITLE
User-supplied CSS for subtitles

### ISSUE THREAD

**Issue by ChubYee** [killergerbah/asbplayer#153]
Currently, the customization you can do to the subtitle is outline thickness (though I'd call it more of an outline glow, since it disperses/diffuses the more you increase the value), and background opacity. I'm wanting to be able to change the thickness of the stroke
![combine_images (3)](https://user-images.githubusercontent.com/104586776/177105019-99d3422c-3e38-4544-aac1-6d0911677275.jpg)

**Comment by killergerbah** [comment]
The type of stroke you're looking for that outlines the text isn't really possible with CSS right now. However, the text shadow style could achieve something similar.
