### ISSUE TITLE
Subtitles not detected on Amazon Prime

### ISSUE THREAD

**Issue by apache1123** [killergerbah/asbplayer#156]
Hello

Not sure if the Prime Video's video player got updated or whatnot since issue #50, but now the issue seems to exist again.
The video does get detected but not the subtitles. 

Looking through your comments on that issue last time, it seems that the prime video player is pretty iffy...hopefully it's not hard to find a workaround this time...

Thanks!

(Loving the extension by the way! I use it all the time on Crunchyroll and Hidive)

**Comment by killergerbah** [comment]
> Not sure if the Prime Video's video player got updated or whatnot since issue https://github.com/killergerbah/asbplayer/issues/50, but now the issue seems to exist again.
The video does get detected but not the subtitles.

Can you elaborate on the problem a bit more? Dragging-and-dropping subtitle files doesn't work? For what it's worth, asbplayer hasn't ever been able to auto-detect Amazon Prime subtitles (not sure if that's the problem being pointed out here).

**Comment by apache1123** [comment]
Ah yes sorry I meant auto-detect Amazon prime subtitles. I saw that issue and thought that was what was meant. I somehow missed the fact that the readme mentions this is not supported. Sorry about that!
