### ISSUE TITLE
Problems with hotkeys

### ISSUE THREAD

**Issue by avc1657** [killergerbah/asbplayer#157]
For some reason when i watch videos on places like youtube, hotkeys to create cards work normally, but when i watch a local video, i cant create cards because hotkeys suddenly stop working. The hotkey to activate the extension still works normally, though.

OS: W10
Browser: Edge Chromium v104
Anki version: 2.1.35
Asbplayer version: 0.19

**Comment by killergerbah** [comment]
The keyboard shortcuts for the asbplayer site are different from the extension. See the README for the different shortcuts. You probably want to use Ctrl+Shift+Q to open the Anki dialog.

**Comment by killergerbah** [comment]
Closing this unless you are still having issues @avc1657
