### ISSUE TITLE
save sentence for later

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#158]
I hope you could implement a way to save sentences for later that we can sentence mining at the end of the movie, most of the time I want to enjoy the movie and sentence mine later, but right now it's not possible because there is no way that we can save the sentence for later, maybe you can let us save current sentence with hotkey and let us download the sentences that we are saved as SRT file so we can sentence mine it when we finished the move. I know it's hard to implement such thing with online cloud, but the Srt method is good enough, that way we can download the SRT and open it later for sentence mining and it's gonna be only the sentences that we are saved before and nothing else in it

![Screenshot 2022-08-12 022404](https://user-images.githubusercontent.com/101425664/184258941-fa910b31-c51c-4f7f-80d5-69d39b37a8b0.png)

**Comment by killergerbah** [comment]
Do you mind explaining why Ctrl+Shift+A isn't good enough?
By "save for later" you mean "save for later, even if asbplayer is closed?"

**Comment by nzarbayezid** [comment]
> By "save for later" you mean "save for later, even if asbplayer is closed?"
YES

I know you can save the sentences in the extension with hotkeys, but it's not so useful because when you close asbplayer the saved sentences is gone, maybe you can implement something that let us download the saved sentence as an SRT file that way we can come back to it later and sentence ming it

**Comment by nzarbayezid** [comment]
don't like the idea?

**Comment by killergerbah** [comment]
It's a good idea I just need to implement it

**Comment by killergerbah** [comment]
@nzarbayezid This is implemented. Let me know if it works for you.
