### ISSUE TITLE
Automatic subtitle detection

### ISSUE THREAD

**Issue by OltiP2** [killergerbah/asbplayer#159]
If the video and subtitle have the same name and are in the same folder it automatically loads the subs
example: EP1.mkv EP1.ass, so it automatically loads the subs

**Comment by killergerbah** [comment]
This will save the effort of selecting both files to drag and drop (or putting both files in a folder and dragging the folder) but feature would be inconvenient for people who want to watch without subs (or at least, who would like to have that option).
