### ISSUE TITLE
white background error

### ISSUE THREAD

**Issue by HaiDuongdarkocean** [killergerbah/asbplayer#160]
https://user-images.githubusercontent.com/82883287/186328913-d7514036-8c2f-4770-bca8-9c8a7af38a94.mp4

When the extension takes a screenshot, it appears on a white background. img can't be capture. I reinstalled it, but the error still, Please correct this mistake.

**Comment by killergerbah** [comment]
What other extensions are you using?

**Comment by HaiDuongdarkocean** [comment]
I'm using asbplayer-extension-0.19.0

**Comment by HaiDuongdarkocean** [comment]
and all extension her.
![KFuttqInnJ](https://user-images.githubusercontent.com/82883287/186445426-f27c1f5a-12b0-49ea-acfb-1a798625f542.png)
e

**Comment by HaiDuongdarkocean** [comment]
The problem is that the extension changes the background color, I'm stupid shittt :"<

**Comment by killergerbah** [comment]
@HaiDuongdarkocean Why is that the problem? Is that interacting badly with another extension?
