### ISSUE TITLE
Please support dual subtitles

### ISSUE THREAD

**Issue by vuongcris4** [killergerbah/asbplayer#162]

**Comment by killergerbah** [comment]
Have you tried dragging in multiple subtitle files at once?
If that doesn't work for you what specifically are you looking for？

**Comment by vuongcris4** [comment]
oh, thank you so much

**Comment by vuongcris4** [comment]
btw, how to auto add second subtitles to definition field?

**Comment by killergerbah** [comment]
Can you try using the slider at the bottom of the Anki Export dialog?
Adjust the slider and then use the checkmark button inside the "Sentence" field.

**Comment by killergerbah** [comment]
I've created a bug for https://github.com/killergerbah/asbplayer/issues/165

**Comment by 7ati1** [comment]
> Can you try using the slider at the bottom of the Anki Export dialog? Adjust the slider and then use the checkmark button inside the "Sentence" field.

can you please explain that more ? 
i'm using vocaseive with ASBplayer auto copy subtitles to clipboard enabled, is there a way to update the last card by adding a field that shows the second subtitle on the back of the card ?

**Comment by killergerbah** [comment]
> can you please explain that more ?
I believe that at the time I was thinking messing with the slider would cause the subtitles from the second track to be automatically included in the text field. Currently this is not really the case. All tracks will be included in the sentence field by default already.

> i'm using vocaseive with ASBplayer auto copy subtitles to clipboard enabled, is there a way to update the last card by adding a field that shows the second subtitle on the back of the card ?
It's in my to-do list to add support filling Anki fields other data besides the existing sentence, word, definition, etc.
