### ISSUE TITLE
Feature request: Select multiple subtitle lines for anki export

### ISSUE THREAD

**Issue by trexrush** [killergerbah/asbplayer#167]
I would like to be able to include multiple subtitles in a mined card. Some subtitles are short and dont give adequate context for a word to be mined, and I like including enough context in my cards to discern meaning from context by adding additional subtitles to the 'sentence'.

A feature to adress this could look like allowing shift-clicking of multiple subtitle lines or selecting multiple lines of subtitle text with the cursor in the subtitle list before creating an anki export, and the export would
   - create audio encompassing all of the subtitle lines
   - include all highlighted lines as the sentence field.

This is a not-very-well-known feature that animebook has that I would love to see implemented in asbplayer.

**Comment by killergerbah** [comment]
@trexrush Kind of late, but for what it's worth it's not hard to achieve this in the Anki export UI itself. You just need to adjust the slider.
However I agree it could be nice to implement something like this in the subtitle list as well.
