### ISSUE TITLE
Black Screen When Playing Local File

### ISSUE THREAD

**Issue by SapiBau** [killergerbah/asbplayer#173]
When I try to play this file, it only shows a black screen, but the audio is still playing (The video recorder didn't record the audio). When i try to play the file in Microsoft Movies & TV, it shows an error code 0xc00d5212. I could play the file using MPV.

https://user-images.githubusercontent.com/114275578/192080325-9b5da398-2330-48d6-9a9f-d0fce8af4b63.mp4

**Comment by killergerbah** [comment]
Hey check out this part of the readme https://github.com/killergerbah/asbplayer#browser-compatibility
Basically chrome doesn't support some audio/video codecs. If you want to use asbplayer with those you'll need a different chromium build. I've had the most success with Microsoft edge and paid hevc support.
