### ISSUE TITLE
Infinite loop after clicking any option on anki export

### ISSUE THREAD

**Issue by DumbBoy2** [killergerbah/asbplayer#177]
Basically, I can't export cards. everything is set up correctly since It worked in previous updates. Tried reinstalling the extension already but didn't work... only change that I made recently are updating the extension and installing nordvpn but non of those should create a problem. I suspect it's the vpn(even if I actually tried shutting everything off even from task manager already and it didn't work) but yomichan export is working fine...

**Comment by DumbBoy2** [comment]
ok this is interesting, I tried downgrading (bugged version was the last one 0.21) and the all work progressively worser up the the 0.17.     0.20/0.19/0.18 ctrl shift x wan't even working and 0.17 ctrl shift z stopped working as well... returning to 0.21 fix this problem but it still get stucked on infinite loop without being able to export...

**Comment by DumbBoy2** [comment]
update: 
forget what I said about older version I'm sleepy right now and I forgot to rebind the shorcuts...
However I found out the exstension works fine on streaming sites like zoro to and I suppose Netflix (will try tomorrow) but have troubles with local files. I guess I'll have to stick to mpv + mpvacious for those files...

I'm on windows 8.1 if it's of any help...

**Comment by DumbBoy2** [comment]
Tested this morning with a windows 10 laptop and local file export still doesn’t work… I had the same problems downgrading as well so it’s not me being sleepy (I double checked this time and shortcuts were correctly binded)

**Comment by killergerbah** [comment]
@DumbBoy2 By infinite loop you mean buttons are grayed out and the UI is stuck forever?
Can you try bringing Anki to foreground when this happens?
Another thing to check is any adblocker software.
Finally if you can look at chrome://extensions for any error logs when this happens those could be helpful.

**Comment by DumbBoy2** [comment]
Ok sorry for the late reply... Yeah with infinite loop i mean buttons are grayed out and the UI is stuck forever. Tried bringing Anki to the foreground and now it says that it's impossible to record audio cause there is none to record... just checked and the video (which works flawlessly on mpv) has no audio when I upload it on asb player. What's even more crazy is that it seems to be a problem of that specific show (subs please release of komi san) cause I just tried with chainsawman and everything works fine, even exporting to anki... I use uBlock origin as an adblocker but I don't think that's the ploblem since exporting now works fine for some reason (maybe the loop was cused by anki not being in the foreground) but I don't understand why it does cut the audio of that show when I upload it... it's the subs please release of komisan if you want to try it yourself, but this doesn't make any sense since the chainsawman release I used was form subsplease as well...

**Comment by killergerbah** [comment]
@DumbBoy2 Are you saying that the audio doesn't play for that video file?
That's a known problem with Chrome not supporting all audio codecs.

**Comment by DumbBoy2** [comment]
Yeah I guess that’s the problem even if it doesn’t make any sense for them to be using a different codec only for that particular show… (specially if you know subsplease) anyway i guess all problems are solved at this point…
