### ISSUE TITLE
Manifest file is missing or unreadable Could not load manifest.

### ISSUE THREAD

**Issue by Zachwyat1** [killergerbah/asbplayer#179]
When loading unpacked i get the "Manifest file is missing or unreadable
Could not load manifest"

**Comment by killergerbah** [comment]
Most likely you downloaded the wrong zip file. You need to download the one named `asbplayer-extension-0.21.0.zip`

**Comment by Zachwyat1** [comment]
Thanks for the quick reply. I downloaded that exact file and unzipped it to a new folder. It still has the same error. I tried troubleshooting from what I found on youtube and online yet nothing improves the situation.

**Comment by Zachwyat1** [comment]
Also just tried it on my desktop as well with the same issue

**Comment by Zachwyat1** [comment]
Figured it out. I was downloading the wrong zip. I appreciate your help.
