### ISSUE TITLE
Getting "Failed to Fetch"

### ISSUE THREAD

**Issue by parthshahp** [killergerbah/asbplayer#207]
Getting failed to fetch on Windows 11, Google Chrome, everything latest version. I'm using the asbplayer extension.

- ankiconnect works fine (am using it with Yomichan as well which works)
- Tried with uBlock origin uninstalled, it didn't change anything
- No other extensions

Any idea what could be the issue?

**Comment by killergerbah** [comment]
Have you already added https://killergerbah.github.io to the CORS origin whitelist in the AnkiConnect settings? There's a blurb about in the README: https://github.com/killergerbah/asbplayer#asbplayer-cant-connect-to-anki-it-shows-an-error-message-eg-failed-to-fetch

**Comment by parthshahp** [comment]
Ah, sorry I forgot to mention that, yes I did do that!

**Comment by Voxtopass** [comment]
I'm getting the same error suddenly when I've never gotten the error before in the few months I've been using the extension. To be safe, I disable any extensions running on YouTube, and I have AnkiConnect setup correctly (it worked before).


The error from the developer console when I click "export":
```
Error: Failed to fetch  
    at e.<anonymous> (anki-ui.js:17:33913)
    at anki-ui.js:17:27913  
    at Object.next (anki-ui.js:17:28018)  
    at i (anki-ui.js:17:26732)  
(anonymous) @ anki-ui.js:86  
(anonymous) @ anki-ui.js:86  
(anonymous) @ anki-ui.js:86  
l @ anki-ui.js:86  
```

**Comment by parthshahp** [comment]
Hmm, haven't been able to reproduce this issue for some reason. Tried after a couple of days (didn't change anything) and seems to be working now. I had reinstalled the extension, cleared browser cache, and restarted the computer to no avail earlier, but everything seems to be fine now. I'll leave the issue open as it seems @Voxtopass is still having problems.

**Comment by killergerbah** [comment]
Thanks for the log, unfortunately that error is super generic.
Most helpful might be a screenshot of the request and response from the network tab.
You'll see a request labeled with a red 127.0.0.1 - if you click on that you will see more details such as request/response status/headers which would be more helpful information.

**Comment by killergerbah** [comment]
Another person reported a similar issue and was able to work around it by switching to the latest version of Chrome. I'm assuming @Voxtopass has either fixed the issue or moved on.
