### ISSUE TITLE
An option to pause the video when you hover over the subtitles

### ISSUE THREAD

**Issue by LeonardoLima22** [killergerbah/asbplayer#208]
Hi, i'm the guy from the line breaks and crop image suggestion. i have a new idea.

it's an option to pause the video when you put your mouse over the subtitles to check with yomichan, rikaikun etc...

Another thing i'm thinking is the video to continue playing if you remove the mouse of the subs,
but i'm not sure if this would work well with yomichan because you need to click on the (+) sign to add the card, and if you do that you need to move your mouse out of the subtitle, so the video would play without me wanting it, but if you can find a way around this would be nice, but just the pause feature would be sufficient.

**Comment by Hirosashii** [comment]
Seconding this, and also the ability resume play after moving away from the subs. For the yomichan window problem stated above, you could potentially replay the video when 'x' amount of pixels away from the yomichan window since the spacing between the subs and the yomichan window is consistent?

**Comment by Y-LBG** [comment]
That would be... Amazing <3

Don't mind so much the "continue playing when removing the mouse from the subtitles"...
I'd be okay with having to "just press Space" honestly.

But the gymnastics to : Press Space (to pause asbplayer), Press Shift (for Yomichan) & hover with the mouse... My fingers are not that agile (yet ?) Hahaha

**Comment by Kastannn** [comment]
Also seconding since this feature sounds amazing. Hopefully eventually  you'll be able to add something of this sort! :)

**Comment by Mupu** [comment]
It would be awesome indeed. To add to the list of dictionary apps: I'm also using jpdb-breader. It would be awesome if this feature worked with it. It would completely replace mpv for jpdb then as well. jpdb-breader + asbplayber to insert subtitles to have jap dub + jap sub inside online players is awesome!
https://github.com/max-kamps/jpd-breader
