### ISSUE TITLE
Clipboard keeps auto pasting current subs

### ISSUE THREAD

**Issue by Ethan1978** [killergerbah/asbplayer#217]
When I have it to save the subtitle to the clipboard it keeps pasting it into yomichan, over and over. I have the latest version of Crome {Version 111.0.5563.111 (Official Build) (64-bit)} and the latest version of ASB {-0.25.0} I don't know if others are having this issue, since I haven't seen it in the issues tab. 
I was using [0.24.0.zip] before and never had this issue.

**Comment by killergerbah** [comment]
You're talking about the Yomichan search page right? If you turn off the "clipboard monitor" that problem should go away.
