### ISSUE TITLE
Uncaught Error: Extension context invalidated.

### ISSUE THREAD

**Issue by MiniBooM7** [killergerbah/asbplayer#218]
When I press cntrl + shift + F on any site I get this error in the extension error log:

Uncaught Error: Extension context invalidated.

Context
https://killergerbah.github.io/asbplayer/ (example)

absplayer.js:1 (anonymous function)
1 !function...

And I don´t get the window for select the subtitles.

**Comment by killergerbah** [comment]
@MiniBooM7 Restart your browser; should fix it.

**Comment by MiniBooM7** [comment]
> @MiniBooM7 Restart your browser; should fix it.

I was on 0.25.0. Now I updated to 0.26.0 and restarted the browser but it doesn´t get fixed.

**Comment by killergerbah** [comment]
@MiniBooM7 Make sure the extension is only installed once. You need to uninstall 0.25.0.
And also check chrome://extension/shortcuts to make sure shortcuts are set up.

**Comment by MiniBooM7** [comment]
> @MiniBooM7 Make sure the extension is only installed once. You need to uninstall 0.25.0. And also check chrome://extensions/shortcuts to make sure shortcuts are set up.

It was the shorcuts, thank you!

**Comment by MiniBooM7** [comment]
@killergerbah Sorry for all the problems, but I used the extension before and I didn´t have any problem. Now when I press cntrl + shift + U it makes all the process like is recording but then the card in Anki hasn´t the audio and the picture... Thank you.

**Comment by killergerbah** [comment]
@MiniBooM7 Some things to check:
- Audio/image fields are configured in Anki settings
- Extension popup "record audio" and "take screenshot" are enabled
- Anki card browser is closed
- Ctrl + Shift + U is actually bound to the "Update last card" action
- You are using Ctrl + Shift + U when a subtitle is showing on screen
- If you're on macOS, make sure that Anki isn't being backgrounded as in "Note for MacOS Users" here:  https://foosoft.net/projects/anki-connect/

**Comment by MiniBooM7** [comment]
> 

All fixed. Thank you!
