### ISSUE TITLE
Subtitles don’t display

### ISSUE THREAD

**Issue by SomieStuff** [killergerbah/asbplayer#222]
When I try to mine a subtitle, it tells me to open a file. When I open a ass file, it doesn’t do anything, and if I try to open it from the webpage it turns white. The file works elsewhere so I think it’s an asb problem

**Comment by killergerbah** [comment]
Can you upload the file here? What site are you seeing this problem on?

**Comment by killergerbah** [comment]
No response

**Comment by SomieStuff** [comment]
Sorry for not responding. I tried another file and it worked, so I think it was the ass

**Comment by killergerbah** [comment]
@SomieStuff If you are able, can you upload the file here? Maybe I can fix it.
