### ISSUE TITLE
Screenshots from firefox are blank

### ISSUE THREAD

**Issue by ChimneyBiscuits** [killergerbah/asbplayer#223]
When updating a card with ctrl+shift+u the screenshot that ends up in anki is completely black when done in firefox, The screenshot is also completely black if you download it from mining history

**Comment by killergerbah** [comment]
Firefox isn't supported.
You'll have to use a Chromium-based browser.
Out of curiosity, you are seeing this with a local file or streaming video?

**Comment by ChimneyBiscuits** [comment]
local file, everything else seems to work fine.

**Comment by Diego014cshmemorizer** [comment]
> When updating a card with ctrl+shift+u the screenshot that ends up in anki is completely black when done in firefox, The screenshot is also completely black if you download it from mining history

What type of screenshot file is it?

**Comment by Diego014cshmemorizer** [comment]
Also, Have you tried Chrome or Edge?

**Comment by Diego014cshmemorizer** [comment]
> When updating a card with ctrl+shift+u the screenshot that ends up in anki is completely black when done in firefox, The screenshot is also completely black if you download it from mining history

@ChimneyBiscuits, May I please see your code? I might be able to suggest something.

**Comment by Diego014cshmemorizer** [comment]
> > @ChimneyBiscuits, May I please see your code? I might be able to suggest something.
> 
> I don't code, i'm just a user of the site. I switched to using a chromium-based browser months ago

Oh, Sorry to bother you about coding.
