### ISSUE TITLE
Autoscrolling Subtitles Get Stuck After Seeking

### ISSUE THREAD

**Issue by Hirosashii** [killergerbah/asbplayer#224]
When I use the "seek backwards 10 seconds", "seek forward 10 seconds", "seek to previous subtitle", or "seek to next subtitle" buttons, intermittently it will cause the autoscroller to get stuck on one subtitle and not auto scroll to the next subtitle, even if the video is past the corresponding line. And then even if the video is, say, 1 minute past that line, if I use "seek to previous subtitle", the video will jump all the way back to the line it was stuck on. Not sure why this happens, especially intermittently. Using Chromium (Brave, to be exact) and a .mkv file, and .srt subtitle file.

**Comment by killergerbah** [comment]
@Hirosashii Do you know what is the encoding of the video? If not can you paste the name of the file here?

**Comment by Hirosashii** [comment]
The video codec is H264 - MPEG 4-AVC (part 10) (avc 1)

**Comment by killergerbah** [comment]
Thanks

**Comment by killergerbah** [comment]
@Hirosashii I pushed what I believe to be a fix - let me know if you are still having problems.

**Comment by Hirosashii** [comment]
It looks like it is fixed, yeah. Watched a whole video with no issues. Thank you for taking a look into this.
