### ISSUE TITLE
subtitle page flips to another subtitle when  selecting one

### ISSUE THREAD

**Issue by thiagocasti** [killergerbah/asbplayer#227]
https://user-images.githubusercontent.com/130512347/231300906-c80eec3e-00d2-4893-a059-5d830651d716.mp4

(the final flip i think it was just lag made from sharex lol bad computer) I'm constanly having problems with netflix reproducer when  wanting to select a subtitle it just flips to another one and it freaks me when i want to mine something from the asb player it just records another dialog. And i even re installed the extension twice and refreshed the page.

**Comment by killergerbah** [comment]
@aoimonster Hard to tell what's going on from that video but these are the possibilities I can think of:
- Seeking lag from Netflix. Netflix is finishing seeking to the last place you selected just as you try to select another subtitle.
- Seeking imprecision. Sometimes when seeking you will get sent to someplace near the subtitle timestamp but not exactly to the exact timestamp.

I'm going to guess it's more likely the former thing that's happening. As a workaround you could pay attention to whether Netflix is buffering or not when you're seeking. Or just use the arrow keys to seek from the Netflix video player tab and mine when video buffering actually finishes.

**Comment by aoimonster** [comment]
I think the subtitle page just desynchronized from the netflix reproducer, tried to just change the subtitle ms but it just shows another in the netflix reproducer, it's strange because this only happens when I try to select one or when mining a card whit cntrl +shift+ U. I should test if this happens in other streaming services or if it's a netflix problem. Thanks for the answer!

**Comment by aoimonster** [comment]
@killergerbah 

https://user-images.githubusercontent.com/130512347/231443858-5c691091-6e21-4a06-9357-4c434a8b041e.mp4

better video here, i think it's a problem whit how  my computer manages resorces like i was using my 4gb ram and when i open anki or hide the subtitle tab that's when it just desynchronized idk but when i go to my 8gb ram pc works fine.

**Comment by killergerbah** [comment]
@aoimonster Okay thanks it's clearer what's happening now.

**Comment by killergerbah** [comment]
This was a problem where Netflix seeks imprecisely on some hardware. The fix was lifted from Language Reactor.
