### ISSUE TITLE
failed to fetch error

### ISSUE THREAD

**Issue by kiyotakaCode** [killergerbah/asbplayer#230]
I've added the dependency to the webCorsOriginList however I am still getting 'Failed to fetch' for the Anki url, Yomichan is connected and working but asbplayer is not. This is the last step in my sentence mining setup, I heard a lot of great things about asbplayer it would be a shame to have to switch to another screen capture services.

**Comment by killergerbah** [comment]
Try the suggestions here https://github.com/killergerbah/asbplayer#asbplayer-cant-connect-to-anki-it-shows-an-error-message-eg-failed-to-fetch

**Comment by killergerbah** [comment]
No response
