### ISSUE TITLE
Cannot create note because note is empty

### ISSUE THREAD

**Issue by Smratest** [killergerbah/asbplayer#232]
I'm using JP mining note and I've been trying all day to troubleshoot this and have reinstalled everything multiple times, but whenever I attempt to create a new anki card, it just says the title.

**Comment by killergerbah** [comment]
Read this and see if it helps you: https://github.com/killergerbah/asbplayer/issues/220#issuecomment-1501124166

**Comment by killergerbah** [comment]
No response
