### ISSUE TITLE
several mining setup module

### ISSUE THREAD

**Issue by adgjlsfhk123** [killergerbah/asbplayer#233]
At present, I am studying English and Japanese concurrently, and I utilize various tools for my sentence mining: Online-Dictionary-Helper for English and Yomichan for Japanese. 

As I use Asbplayer, I often find myself alternating between these extensions, which ultimately consumes a significant amount of time. 

Consequently, I believe it would be a tremendous enhancement to be able to effortlessly toggle between distinct Anki configurations. 

By the way, I'd like to convey my heartfelt gratitude for your outstanding extension and express my thanks for developing such a useful product.

**Comment by nzarbayezid** [comment]
what's your top extension if you don't mind?

**Comment by killergerbah** [comment]
Thank you for the great suggestion.

**Comment by killergerbah** [comment]
Anki settings profiles are now implemented.
