### ISSUE TITLE
If a regex removes an entire subtitle, make condensed mode skip that subtitle

### ISSUE THREAD

**Issue by killergerbah** [killergerbah/asbplayer#235]
From ZyphDoz on Discord:
If a regex removes an entire subtitle, make condensed mode skip that subtitle. Would be useful because you could filter out stuff like `はあっ！|くっ！|はっ！|あっ！` to fly past action scenes

**Comment by Y-LBG** [comment]
I'm guessing that was implied but...
That'd be true for the auto-pause feature as well =]

**Comment by killergerbah** [comment]
The subtitle is removed from the list when only whitespace is left

58d8ff0a1ffc7709cbe6e6eea3c0f65845ce3e6b
