### ISSUE TITLE
Mining (Ctrl+Shift+X) or Updating last Anki card (Ctrl+Shift+U) while using the auto-pause feature tends to mine using the next subtitle

### ISSUE THREAD

**Issue by Y-LBG** [killergerbah/asbplayer#239]
Hi,

When doing intensive/interactive immersion (like a lot of people I believe), I tend to watch videos with the auto-pause feature on, allowing me to follow the video, then take my time to understand/read the subtitles, and finally possibly mine.

Typical use-case :
While watching a local video on 'https://killergerbah.github.io/asbplayer/' (with asbplayer extension installed) :
1. Watch the action corresponding to the current subtitle
2. Auto-pause at the end of the current subtitle
3. Use Yomichan on the displayed subtitles for words I don't understand
4. Create a new Anki card from the Yomichan pop-up if I want to mine it
5. "Ctrl+Shift+U" to export screenshot, audio, etc. to the newly created Anki card
   - That's where I'm noticing the bug... It's exporting the screenshort, audio, etc. as if I was on the next subtitle

This forces me to always slightly come back in time on the video before I mine (non-blocking, but quite inconvenient ^^)

Note: I can see that the hightligthed subtitle in the list (in the right pane) doesn't fit the subtitle overlayed on the video (which is were I use Yomichan)
I'm guessing the "Ctrl+Shift+U" is using the right pane subtitle... So this is most probably "only" a problem of synchronization between the subtitle list and the subtitle overlay on the video.

**Comment by Y-LBG** [comment]
Ok, had a look at the code.
I'm more of a C++ guy than a JS one... So I might be missing something !

But I believe this is related to that commit : fbbad59b68cedbb640aabb5a2945f9da85c5ad20
In particular the fact that you "Let VideoPlayer do the auto-pausing" when a videoFileUrl is provided.

From my understanding, that's correct to let the VideoPlayer handle the auto-pausing when auto-pausing at subtitle **start** (since the subtitle player seem to always be slightly ahead of time of the video... You don't want the video to still be showing the previous subtitle when the subtitle tree does the auto-pausing)
However, I'd say we should let the subtitle player handle the auto-pausing when auto-pausing at subtitle **end**  (to make sure the SubtitlePlayer is still correclty on the subtitle being displayed on the VideoPlayer)

My only concern is : What guarantee do we have that the SubtitlePlayer will always be ahead of time of the VideoPlayer ?
Is there somewhere in the code that guarantees SubtitlePlayer takes precedence over VideoPlayer ? Or is it just because Video is more heavy to process, and therefore the VideoPlayer is a bit "slower" ?

Before reading the code, my orignal idea was that the subtitles were being synced with the video (i.e. Video takes precedence over Subtitles), but that doesn't seem to be the case, given what I notice here.

Anyway, I'll try to propose a PR over the week-end (Changes in both Player.tsx and VideoPlayer.tsx expected)
Unless you come back to me telling me I got somehting wrong ^^

Hopefully that'll be good enough ;]

Cheers.

**Comment by killergerbah** [comment]
@Y-LBG There's no guarantee that the subtitle player is ahead or behind the video player. I suppose you could expect the subtitle player to be ahead of the video player most of the time - that would be a consequence of any playback commands being processed first by the subtitle player and then echoing those back to the video player, but that is not really a guarantee.

It would be safer to think of the video player clock and the subtitle player clock as being independent things that we make a best effort to keep in sync. This is simpler to implement and also makes it feel like the video is completely in sync w/ the subtitles regardless of wherever the subtitle player might be.

For that reason my suggestion would be to prioritize the subtitle being displayed on the video player when using any of the mining commands, although I realize not having attempted it myself that implementation may be more complex.

**Comment by Y-LBG** [comment]
Yeah, looking at it again last night, it did feel like I was taking the wrong approach.
Thanks for the confirmation ;]

Following what you are saying above, I'd say what makes the most sense is indeed to try and keep the video player clock and the subtitle player clock in sync, with the video player having priority (since this is the one that gives direct feedback to the user)

We obvioulsy cannot enforce that all the time, and should be able to live with "in sync enough" in most cases (as is the case today), but maybe in some "critical moments" (such as in the case of those auto-pause), we can try and force the re-sync.
i.e. The video player does the auto-pausing using its subtitles (as is the case today), and when letting the subtitle player know it needs to pause as well, it also provides info on "when did it pause", so that the subtitle player can re-sync.

Had a look at the code...
That'd most probably lead to somehting like :
Pause on Video -> Pause SubtitlePlayer -> Overwrite SubtitlePlayer's Current Time with VideoPlayer's Current Time

I like that the SubtitlePlayer is the sole responsible of mining (I'm guessing this is what allows more more powerful features like multi-subtitle mining, etc.)
The VideoPlayer only being here to "provide" frame/screenshot and audio when the SubtitlePlayer requests for those with provided timeframes.

So yeah... In the end, "only" a probelm of keeping things in sync I'd say.
Will try to wrap my head around some more of the code to see how doable that would be.

Let me know if you have any further ideas on that.

Cheers.

**Comment by killergerbah** [comment]
@Y-LBG Yes I agree that would work. You would however need to maintain some state somewhere in order for the subtitle player to know that it needs to mine the current subtitle after overwriting its timestamp. A simple way to do this might be to encapsulate the syncing behavior all within the same "copy subtitle" command e.g. 

```
Subtitle player receives "original copy subtitle" command -> 
Forward "original copy subtitle" command to video player ->
Pause on video player ->  
Send "sync + actually copy subtitle" command back to subtitle player with a timestamp -> 
Pause subtitle player and override with timestamp ->
Copy current subtitle
```

However at this point the flow could be simplified by skipping the sync and just having the video player forward its current subtitle back down to the subtitle player:

```
Subtitle player receives "original copy subtitle" command ->
Forward "original copy subtitle" command to video player ->
Forward "actually copy subtitle" command back to subtitle player ->
Copy the subtitles in that command
```

Which would amount to modifying the current code to forward the copy command to the video player, if a video is playing, rather than handling the copy command right away as it is doing right now in `handleCopyFromSubtitlePlayer`.

I think this suggests that there are two problems (and either one might not be a problem depending on how you look at it):

1. As you said, the video player isn't in sync with the subtitle player.
2. Sometimes the subtitle player receives the copy command, and sometimes the video player receives the copy command, since 'copy' key binding is detected in both. Unfortunately, the resulting behavior in either situation can be different because of problem 1.

So we could solve problem 1 directly as you suggest by syncing before copying, or solve 2 directly by having a "source of truth" for who actually decides what gets copied i.e. when a video is playing the video player should be that source of truth. At first glance, my preference would be to solve problem 2 in the way described above as this would certainly avoid having to keep any state around in order to coordinate the "sync + copy" operations.

**Comment by killergerbah** [comment]
I was able to implement this fix. It'll get pushed along with localization when I am done with that.

**Comment by Y-LBG** [comment]
Amazing =D
Tried having a look at it again a week and a half ago, but my intended solution was having unwanted side-effects...
It felt like everything was so coupled, but I'm guessing you had no choice when doing it that way originally.
Anyway, good to know the fix is coming soon ;]
Cheers.

**Comment by killergerbah** [comment]
@Y-LBG Unfortunately the code quality here isn't the best. I would be curious to know what problems you were running into and thoughts on possible improvements however.
