### ISSUE TITLE
How to sync subtitles?

### ISSUE THREAD

**Issue by Lombizrak** [killergerbah/asbplayer#241]
They speak for 200 to 500ms before the subs appear? 
Any help is very appreciated.

**Comment by killergerbah** [comment]
I would recommend you use the keyboard shortcuts: https://killergerbah.github.io/asbplayer/?view=settings#keyboard-shortcuts
If the subtitle are appearing delayed, then use `Ctrl+Shift+Right` to speed the subtitles up by 100ms increments.
