### ISSUE TITLE
"Auto-copy current subtitle" not working for all sites

### ISSUE THREAD

**Issue by Mycheze** [killergerbah/asbplayer#246]
Hello! I love asbplayer since it allows me to use Vocabsieve to very quickly and easily look up words, especially with the "auto-copy current subtitles" feature. But, it only seems to work on YouTube, but not on the other streaming site.

On YouTube, for auto-copy to work, I need to have the YouTube tab or the asbplayer tab active and "on top." While I wish it could auto-copy regardless of what was on top, this might not be possible.

But, the other streaming site I use, it *only* works if I have the asbplayer tab selected. Which kind of defeats the purpose of auto copy since I'd need to have a different tab highlighted and swapping between windows becomes difficult. I'm not sure if this is an actual bug or intended behavior, but it's something I noticed.

**Comment by killergerbah** [comment]
This will happen for video players inside of iframes that don't have permissions to write to the clipboard e.g. CrunchyRoll and zoro.to, which would explain why YouTube works. I would expect Netflix to work as well, but haven't tested it. Looking into a fix.

**Comment by killergerbah** [comment]
I have a fix for this. It will be released in a new version (probably in a couple weeks). But let me know if you'd like a dev build of the latest code to have the fix early.

b5dd9573035c11114b538789d91a743734d9dde2

**Comment by Mycheze** [comment]
That's awesome news! I'm happy to wait since I'm mostly mining from YouTube anyway. Thanks again for this awesome tool!
