### ISSUE TITLE
Not Supported Error Displaying

### ISSUE THREAD

**Issue by na2suara** [killergerbah/asbplayer#247]
I am using asbplayer on chromium running on a mac. I set up asbplayer with ankiconnect and even mined 1 card. The problem is now it displays not supported when I try to to export to anki. I checked all my settings and I didn't change anything so I don't know what the problem could be. My other programs running ankiconnect, such as yomichan, still work.

**Comment by killergerbah** [comment]
If you go to the URL `http://127.0.0.1:8765/` in your browser what do you see?
You'll want to be on at least version 6. Make sure AnkiConnect is up to date.

**Comment by na2suara** [comment]
I fixed it. It was some issue with the specific subtitle file. I don't know what exactly but when I switched it out everything worked.

**Comment by killergerbah** [comment]
Awesome
