### ISSUE TITLE
mp3 and srt out of sync after about 3 minutes

### ISSUE THREAD

**Issue by BlueD** [killergerbah/asbplayer#251]
Hi,

I am using asbplayer with mp3+srt to learn Japanese. And I found the audio and subtitle would gradually out of sync after 2 or 3 minutes. The audio will be several hundred milliseconds ahead.

The audio I am using is from '_Read Real Japanese Essays_'. You can download the mp3 from publisher's website.

https://cdn.kodansha.us/statics/Attachments/2020/12/9781568366180-01_HarukiMurakami_MasshironaUso.mp3

And the srt file is in the Zip file attached.

[9781568366180-01_HarukiMurakami_MasshironaUso.zip](https://github.com/killergerbah/asbplayer/files/11595761/9781568366180-01_HarukiMurakami_MasshironaUso.zip)

If you want to reproduce the problem, please turn "auto pause" on, and start from the second last paragraph (02:39).

**Comment by killergerbah** [comment]
Thanks for reporting this issue @BlueD 
Unfortunately I am not able to reproduce the problem on my computer using the steps you mentioned. I will continue to investigate.

**Comment by BlueD** [comment]
Play the line at 02:46.148 (奈良時代の日本では、) with "auto pause" on, in the end there is a redundant "あ", which is cut from the next word 悪質.
If you play the next line, same thing happened again.

**Comment by killergerbah** [comment]
@BlueD I see what you mean. At first glance the subtitles themselves seem slightly mistimed but I'll investigate more.

**Comment by Y-LBG** [comment]
My guess:
Directly related to this: https://github.com/killergerbah/asbplayer/issues/239
(Because of the usage of the auto-pause feature)

**Comment by killergerbah** [comment]
@BlueD I tried this on https://animebook.github.io/ and saw the same problem. It seems that the timing of the subs isn't very exact for many of those lines.

As @Y-LBG suggested subtitles and audio may be slightly out of sync anyway for technical reasons, but in general that will not be to the extent as seen with the files you provided.

**Comment by BlueD** [comment]
If someone is still interested:

1. the srt has no problem.
2. convert mp3 to ogg solved everything.
