### ISSUE TITLE
Feature condensed playback

### ISSUE THREAD

**Issue by vuongcris4** [killergerbah/asbplayer#254]
In feature **condensed playback**, I think people want **faster speed** video more than skip video.

**Comment by ostovane** [comment]
As a language learner I would say that a (Condensed + Auto Pause) would help me a lot.
Because I want to skip unspoken parts and then repeat the dialogue.

**Comment by killergerbah** [comment]
This is now implemented thanks to @artjomsR

**Comment by killergerbah** [comment]
"
