### ISSUE TITLE
Tab management does not handle page refreshes very well

### ISSUE THREAD

**Issue by killergerbah** [killergerbah/asbplayer#256]
Video elements never disappear from the TabRegistry until the tab's URL changes. This does not account for page refreshes are iframes disappearing from the page. As a result, orphaned video elements can fill up the video element list on the asbplayer site.

**Comment by killergerbah** [comment]
I've updated the issue for clarity following investigation.

**Comment by killergerbah** [comment]
3930e3f24cfc7291676798e2a36e137f9e9ffe7e

**Comment by Diego014cshmemorizer** [comment]
I'm glad you fixed it.
