### ISSUE TITLE
Subtitle placement on Local Videos 

### ISSUE THREAD

**Issue by itsgrunt** [killergerbah/asbplayer#258]
I am unable to mine to due a sudden change of the location of subtitle placement on local videos. I know there is a setting for this issue in the chrome extension for streaming videos. But I am unaware of any ability to change this setting for the playing of local videos.  The subtitles are now being place right under the progress bar, making me unable to mine when I hover over them. I provided images from when the subs where correctly placed, and my current situation. 
![IMG_8670](https://github.com/killergerbah/asbplayer/assets/136025787/e3b3ac36-eb46-40eb-a579-5db45d25fd98)

![IMG_8410](https://github.com/killergerbah/asbplayer/assets/136025787/d89fcad2-afa2-43f6-8ef3-bcfe980c429e)

**Comment by killergerbah** [comment]
@itsgrunt Scrollwheel moves the subs up and down. I need to document this in the README.

**Comment by killergerbah** [comment]
I'm going to close this but if the scroll wheel didn't help let me know @itsgrunt
