### ISSUE TITLE
Can't record audio for my anki cards.

### ISSUE THREAD

**Issue by AizenMikoto** [killergerbah/asbplayer#259]
Everything works fine except for the audio recording. Whenever the extension wants to record an audio clip for a said card, the video goes silent.
It also happens with other extensions that need to record internal browser audio (like "Aha music finder" for example).
I suppose that the problem is on my end and not the extension's. But if you have a solution i'd appreciate it.
I'm on Windows 8.1 64bit and use google chrome by the way.

**Comment by killergerbah** [comment]
@AizenMikoto What version of Chrome are you on?

**Comment by AizenMikoto** [comment]
> @AizenMikoto What version of Chrome are you on?

Hi.
Sorry for the late reply. I'm on version 109.0.5414.141. And that's due to Windows 8.1 not being supported anymore.

**Comment by killergerbah** [comment]
@AizenMikoto Got it, and just to double check, the audio file that's recorded is also silent?

**Comment by AizenMikoto** [comment]
> the audio file that's recorded is also silent?

Yes.

**Comment by killergerbah** [comment]
@AizenMikoto I suspect that either being on Chrome 109 or Windows 8 might be part of the issue, but regardless it may be worth giving an older version of the extension a try. This version is the last one on manifest v2, which used a different method for recording audio: https://github.com/killergerbah/asbplayer/releases/tag/v0.19.0

**Comment by AizenMikoto** [comment]
Okay. I'll try it out.
Thank you.
