### ISSUE TITLE
Support for changing which audio is played on a file with dual audio?

### ISSUE THREAD

**Issue by SaltyBarnacles** [killergerbah/asbplayer#262]
I have a lot of files with both English and Japanese audio, and asbplayer always defaults to the English audio. I can't find a way to change which audio it plays so those files are unusable for me.

**Comment by killergerbah** [comment]
@SaltyBarnacles See if https://github.com/killergerbah/asbplayer#audio-track-selection-for-mkv-files helps

**Comment by SaltyBarnacles** [comment]
> @SaltyBarnacles See if https://github.com/killergerbah/asbplayer#audio-track-selection-for-mkv-files helps

That works, thank you
