### ISSUE TITLE
There is not enough room for the actual film

### ISSUE THREAD

**Issue by ostovane** [killergerbah/asbplayer#269]
Hello

I have a 22 inch monitor with a resolution of 1920 to 1080
Unfortunately player takes too much space for subtitles.
It would be useful if there was a n option to collapse the subtitle part and only see the timing of the subtitle.
I also have problem copying the subtitle to the translator. I wish there was a shortcut for copying the subtitle or send the subtitle to the google translator just by clicking on it.

Thank you

**Comment by killergerbah** [comment]
Can you post a screenshot of what you're seeing so that it's easier to understand what you mean by the player taking up too much space for the subtitles?

**Comment by killergerbah** [comment]
@ostovane

**Comment by ostovane** [comment]
Here you go.
I appreciate your efforts for making such an amazing tool for language learners.
![Screenshot (110)](https://github.com/killergerbah/asbplayer/assets/139720878/5b6264ed-89a0-4ed9-8be5-c0469419e7c0)

**Comment by killergerbah** [comment]
@ostovane Okay I see what you mean. I've been wanting to make the size of the subtitle list adjustable as well, maybe with click-and-drag.

About translation, I recommend setting up VocabSieve (https://github.com/FreeLanguageTools/vocabsieve) for German and using the clipboard monitor. In the short term I am not planning to implement dictionary-lookups within asbplayer.

**Comment by killergerbah** [comment]
Subtitle list size is now adjustable.
