### ISSUE TITLE
absplayer popup window on youtube videos

### ISSUE THREAD

**Issue by Erland-Eldrid** [killergerbah/asbplayer#272]
Hi! The problem I'm having is, every time I start watching a youtube video, a popup window automatically appears. How do I get it to stop? Or, is it possible to make it appear only when I want it to? It's annoying to have to close it every time I open a new yt video. Thanks in advance!

![abs](https://github.com/killergerbah/asbplayer/assets/140424926/ee63d608-d746-4748-823c-4f7404ae33e5)

**Comment by killergerbah** [comment]
This is a bug with asbplayer not recognizing that you had already picked 'Empty' in the past. Normally it will default to the last track you picked.
