### ISSUE TITLE
Make it so for websites like Zoro (Aniwatch) clicking the subtitles doesn't play the video

### ISSUE THREAD

**Issue by aramrw** [killergerbah/asbplayer#275]
Make it so for websites like Zoro (Aniwatch) clicking the subtitles doesn't play the video. For some reason it works on Crunchyroll where the subtitles can exit out of stuff like Yomichan without playing the video if you click on them, but for Aniwatch it just plays the video, not really a big deal at all but its just kinda annoying a little bit

**Comment by aramrw** [comment]
i just wanted to say it only doesnt work in fullscreen, you can click on them without playing the video if its not in fullscreen but well then you cant take a good screenshot

**Comment by killergerbah** [comment]
@aramrw If you're on version 0.27.0 then the screenshot problem should go away.

**Comment by killergerbah** [comment]
Could not reproduce when I tried just now.
