### ISSUE TITLE
Remaining logo 

### ISSUE THREAD

**Issue by Jager228** [killergerbah/asbplayer#278]
Hi! I have an issue with remaining logo. Usually when I added video file it poped up for a second, but now it interferes watching. I've tried to restart browser and computer, but it didn't help much 

![image](https://github.com/killergerbah/asbplayer/assets/141614543/e515bb7a-fa25-42e6-9a78-b93671772be4)

**Comment by killergerbah** [comment]
@Jager228 Can you try again? It should be fixed.
