### ISSUE TITLE
m4b support

### ISSUE THREAD

**Issue by Whitesttax** [killergerbah/asbplayer#280]
Would be nice to have for audiobooks, using .srt to read along. 
The only other thing to have for a complete experience would be if the player remembered your playback position for next time when using then same media.

**Comment by killergerbah** [comment]
There seems to be little existing JavaScript library support for the m4b file format so a task like this would take a lot of time and effort. But I would still consider it a worthwhile feature that makes asbplayer more generally useful.

**Comment by killergerbah** [comment]
So the short answer to your question is "not planned" but I would be interested in implementing m4b support given enough time.

**Comment by killergerbah** [comment]
Oh never mind. Chrome and Firefox already support m4b playback, lol. I'll release this right now.

**Comment by killergerbah** [comment]
Released
