### ISSUE TITLE
[Feature request] Loop playback button

### ISSUE THREAD

**Issue by Azv121** [killergerbah/asbplayer#283]
I'd like to continuously listen to audio without having to click play every time the media has finished.
I right clicked and checked 'Loop' but this feature doesn't work.
I attached an image of a loop button which can be added to the group of buttons on the bottom right.

![Group 5](https://github.com/killergerbah/asbplayer/assets/142043934/f1b40fe4-565b-4b4e-bb61-3ee982b0ce67)

**Comment by cblanken** [comment]
Is this still an issue? Enabling the Loop option from the "right-click menu" works fine for me.

Browser: Vivaldi 6.6.3271.53 (Stable channel) stable (64-bit)

**Comment by killergerbah** [comment]
The "Loop" button works for me as well on Chrome without my making any code changes. If @Azv121 is still experiencing the issue I can investigate it further however.
