### ISSUE TITLE
Direct add to ANKI from the subtitle list (with audio+screenshot)

### ISSUE THREAD

**Issue by ONEsuzuki** [killergerbah/asbplayer#289]
(possible enhancement)
I have tried to make cards directly from the subtitle list from streaming media (netflix) but when I press the keybinds to export it captures no auido or screenshot which is strange, since it is scyned to the streaming media. 
![image](https://github.com/killergerbah/asbplayer/assets/111155695/a51398c0-078d-4b22-845d-471f32220346)
_What it does when I export from the subtitle list_ 
I don't see why this isn't working I know it's not stated in you're manual as a feature. But shouldn't the asbplayer be able to see netflix and capture everything it needs from the asbplayer itself? 
![image](https://github.com/killergerbah/asbplayer/assets/111155695/ed5fa0de-ba87-4e65-b0d6-ed56cdb9eefb)
Since it's connected to the page anyways, I'm not sure on why it wouldn't be able to so I look forward to hearing you're reply. 

This is how I would imagine it to be implimented, though I know you are working on native crome intergraion with the side pannel; I feel like this would be a good edition if you were not thinking of this already.
![image](https://github.com/killergerbah/asbplayer/assets/111155695/c89f4a0f-3f41-48e0-9b0a-6c70e623a812)
but make it like the mining history tab with an add to anki button, I did see somewhere about there being a way of doing this already if you know of it I appologise for wasting you're time.
![image](https://github.com/killergerbah/asbplayer/assets/111155695/b385c26a-def9-4275-87a8-419739a781ac)
and give us an option possibly in the settings tab to either direct add with audio and screenshot or open the anki export dialog (always adding with audio + screenshot regardless of option).

**Comment by killergerbah** [comment]
@Ethan1978 Unfortunately for security reasons Chrome does not allow extensions to record audio or take screenshots of tabs that the user is not looking at. More specifically the active tab permission is required, which is obtained when you perform a keyboard shortcut on the tab you're trying to extract media from. For this reason sentence mining from the subtitle list is limited.

**Comment by Ethan1978** [comment]
Thanks for the explanation, best of luck with the extention store release ;D

**Comment by killergerbah** [comment]
The next asbplayer release implements a similar feature via the side panel.

**Comment by ONEsuzuki** [comment]
Look forward to it, thanks for all you're efforts they are appreciated.
