### ISSUE TITLE
Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by sop61** [killergerbah/asbplayer#293]
As shown in the screenshot, I recently ran into this issue trying to auto-load subtitles from Youtube. It was working before, so I'm not sure what happened that would cause this, because I didn't mess with any settings prior to this. 
![image](https://github.com/killergerbah/asbplayer/assets/138299498/ad96348b-8e44-4fd6-bf81-68140929a6d3)

**Comment by killergerbah** [comment]
@sop61 It would be helpful to get a screenshot of your console logs and network tab in the developer console when this issue happens. Also, a link to the video where you're seeing it would be great.

**Comment by sop61** [comment]
Sorry about that. Here's a link to the vid: https://www.youtube.com/watch?v=jDW85zELIL0
![image](https://github.com/killergerbah/asbplayer/assets/138299498/0f350aff-cd4b-4e62-94ab-f9dd508e2e80)
![image](https://github.com/killergerbah/asbplayer/assets/138299498/50dd7476-52f0-4584-8405-4ca4e000890b)

**Comment by roboticsbrian** [comment]
Corroborating this bug report on Chrome Version 116.0.5845.141

This happens on every Youtube video. Netflix and Amazon are fine.

**Comment by Lengel1106** [comment]
I'm also seeing this on YouTube videos.

**Comment by killergerbah** [comment]
@sop81 I think this was mentioned on Discord as well, but ad blockers might be causing this. asbplayer needs to make some additional requests to YouTube to obtain the subtitle tracks, which may be blocked by ad blockers.

**Comment by sop61** [comment]
That seems to be the case for my situation. I wonder if there's a way I can somehow whitelist or enable the parts that involve asbplayer, without disabling adblocking...

**Comment by killergerbah** [comment]
I don't use ad blockers so I do not know. asbplayer needs to make a number of requests to YouTube to obtain subtitle tracks. So the ad blocker would need to allow those requests through.

**Comment by phamthaison1207** [comment]
yeah thank you killergerbah for mentioning it, I disabled ublock origin and it worked, unfortunately, I am still figuring out how to allow adblockers to allow requests

**Comment by sop61** [comment]
I ended up just switching off my filters one by one to check which ones are blocking it. Don't know if there's a better way than this, as others may have set their ad blocker different from mine. For those also wanting to mine from youtube and are running into this issue, just check your ad blocker's settings and filters. Or you can just turn off your ad blocker during the time you're mining, and turn it back on when you're done. 

In any case, the issue is not with asbplayer, so I'll close this.

**Comment by jam-madrigal** [comment]
Hello, I realize this was closed but I found a solution. By inspecting the HTTP requests upon opening the subtitle selection prompt, I discovered that adding the following url to your list of trusted sites in ublocks will resolve this issue while seemingly maintaining adblock functionality.

`https://www.youtube.com/api/stats/
`

**Comment by killergerbah** [comment]
Thanks @jam-madrigal !
