### ISSUE TITLE
Help!! Subtitles arent working!

### ISSUE THREAD

**Issue by diverenforce** [killergerbah/asbplayer#296]
I just got a new laptop and setting up my word mining workflow on it and testing if things work but asb player isnt detecting the sub files for some reason. It says no subtitles on the player.

**Comment by diverenforce** [comment]
Update: I tried reloading it and it seem like there are errors.
It says Uncaught Error: Extension context invalidated. ehhh can someone tell me whats going on?

**Comment by killergerbah** [comment]
@diverenforce You're using your own subtitle files? Or are you trying to load detected subtitles from a websiite?

**Comment by diverenforce** [comment]
@killergerbah hello thank you for reply. I went to sleep so I didnt see you right away. 
So I downloaded the sub files from kitsuneko.net and trying to use them on a streaming website. But none of the subs aren't working. I didnt make any of these subtitles.

**Comment by diverenforce** [comment]
I also tried reinstalling, downgrading to previous asbplayers versions.
The result is the same. 
![chrome_lV06hDpe9O](https://github.com/killergerbah/asbplayer/assets/120410051/03fcc8a0-79f7-44ad-9dbf-2849c8ada9cd)
![chrome_uQnPQ2qjAs](https://github.com/killergerbah/asbplayer/assets/120410051/34e879f0-c818-4a19-9d9f-2604deb0d0f9)

**Comment by killergerbah** [comment]
@diverenforce 
Can you record yourself trying to load these subtitles onto a streaming video?
I tried one of the subtitle files in the screenshots and they work for me, so I want to see if there's a difference between what you're doing and what I'm doing.

**Comment by diverenforce** [comment]
okay sure thing wait.  sorry again, for late reply because it was my bed time over here

**Comment by diverenforce** [comment]
Here is the video. its on asb 0.28.0.  

https://github.com/killergerbah/asbplayer/assets/120410051/739ef01b-80c2-48e0-852b-ede2776f0edc

**Comment by diverenforce** [comment]
@killergerbah I forgot to ping you.

**Comment by killergerbah** [comment]
@diverenforce Can you upload the first file that you drag in? At 0:19:0 an error is showing up saying that the file is malformed, so I'm wondering if that has something to do with it.

**Comment by diverenforce** [comment]
@killergerbah  alright i gotchu :) i renamed it to .txt file because github doesnt suppport .srt files. dont forget to rename it.
[One Piece - 001.txt](https://github.com/killergerbah/asbplayer/files/12698396/One.Piece.-.001.txt)

**Comment by killergerbah** [comment]
@diverenforce Thanks for letting me know. Depending on the video source and the subtitle files themselves, the offset can be off.
