### ISSUE TITLE
Automatic captions not working on Youtube

### ISSUE THREAD

**Issue by xPau12** [killergerbah/asbplayer#298]
Hello! I've been using this extension without any problems for a while now but it has suddenly stopped being able to fetch automatic captions on Youtube.

![image](https://github.com/killergerbah/asbplayer/assets/145494869/6077a40d-4e7a-4a6a-a380-844e5328ff24)

Is there any way to fix the issue? Thanks in advance.

**Comment by killergerbah** [comment]
@xPau12 Please see https://github.com/killergerbah/asbplayer/issues/293 . There is advice at the bottom for working around this issue.

**Comment by jam-madrigal** [comment]
I have also commented in that closed issue with the fix I found and have been using just now using the clues provided in the posts. Hope it helps @xPau12

**Comment by xPau12** [comment]
It's working again, thanks to both of you!
