### ISSUE TITLE
v0.28.0 Anki dialog -- cannot update most recent card

### ISSUE THREAD

**Issue by harlansgs** [killergerbah/asbplayer#300]
After updating to v0.28.0, the "Update last card" option in the Anki dialog results in an "Invalid request" error from ASB and does nothing. Using the keyboard short-cut for "update last created card..." is still working without issue, so I wasn't sure what to make of this. I am seeing this issue on Chrome Version 117.0.5938.152 on a Windows 10 host

**Comment by killergerbah** [comment]
@harlansgs That is odd, as both "update last card" from the Anki dialog and "update last card" from the keyboard shortcut use similar code paths. Out of curiosity what version of Anki connect are you on? If you visit `http://127.0.0.1:8765/` in your browser you can check.

**Comment by kraiyt** [comment]
I'm experiencing the same issue with asb player v0.28.0, if it's any help I'm currently using Anki connect v.6

**Comment by killergerbah** [comment]
@harlansgs @kraiyt I found the issue - there is a bug where asbplayer cannot send tags with 'update last card.' So for now you will have to use the keyboard shortcut, or not use tags when updating last card from the export dialog.

**Comment by killergerbah** [comment]
Fixed in 1.0.1
