### ISSUE TITLE
Failed to execute 'decodeAudioData' and Black screenshot

### ISSUE THREAD

**Issue by 13ocho** [killergerbah/asbplayer#301]
![Screenshot 2023-10-14 132603](https://github.com/killergerbah/asbplayer/assets/147921241/5a616f83-afda-4c6c-9696-9f832a9209ed)
i'm using edge and when i'm trying to update the last card i have this error message, also i tried to remove the sentence audio field then it worked but the screenshot is just a full black picture.
i set up asb with this video: https://youtu.be/B60cj69MSmA

**Comment by killergerbah** [comment]
If you can provide a more complete error log from your developer console that would be great. Otherwise I would suggest using a different browser. Chrome now supports HEVC decoding depending on your hardware, so there is less reason to use Edge.

**Comment by 13ocho** [comment]
thank you it works perfectly fine now.
