### ISSUE TITLE
Netflix audio and screengrab are blocked

### ISSUE THREAD

**Issue by dijiango** [killergerbah/asbplayer#304]
When trying to mine a subtitle, the audio file created does not contain any sound and the screenshot does not contain the video image.
![image](https://github.com/killergerbah/asbplayer/assets/85248514/fdb2caa0-01ad-48e3-98fb-6666be59aca6)
[www.netflix.com-1697776716671.log](https://github.com/killergerbah/asbplayer/files/13050001/www.netflix.com-1697776716671.log)

**Comment by killergerbah** [comment]
I've seen others have this issue due to hardware acceleration settings. Have you tried messing with those?

**Comment by dijiango** [comment]
I see. I haven't touched the default settings before but turning the hardware acceleration off seems to make asbplayer work again
