### ISSUE TITLE
Improved multi sub support

### ISSUE THREAD

**Issue by artjomsR** [killergerbah/asbplayer#306]
I'm interested if it's possible to select dual subs with streaming services? At the moment, it seems that it's only possible to select either a single subtitle or use `Open Files` to load multiple subtitles at the same times (so to have multiple subtitles from a streaming service, one needs to DL both of them and then `Open Files` both of them). It would be good to have checkboxes (rather than a single subtitle selection) to load dual subs automatically without downloading them.

Additionally, I don't think there's a consistent way to load dual subs regarding their positions? I.e. sometimes English subtitles get loaded into 1st track and sometimes - into 2nd. This means that the shortcut to hide English subtitles changes from video to video. It seems that subtitle order depends on the video and nothing else. I tried clicking the subtitles in different order when opening them but for some videos English subtitles are always first and for others - second

**Comment by ONEsuzuki** [comment]
It would also be cool if I could export both the target language sentence and the native subtitle sentence, to the same card. So target language on the front, native on the back of the card. Similar to sub2srs.
While all through the video JP subs are displayed on top of English subs maybe with a flip button or blur, or each with there own individual keybind to hid and show, different text style for each would be fantastic.
