### ISSUE TITLE
MKV video files not showing.  Only audio plays.

### ISSUE THREAD

**Issue by AizenMikoto** [killergerbah/asbplayer#307]
Is ASB Player unable to run MKV files ?
As I said in the title, only the audio plays with a black screen. I tried multiple video files and they are all the same.

**Comment by AizenMikoto** [comment]
Never mind. The video files are somehow corrupted.

**Comment by killergerbah** [comment]
mkv is just a container format and may contain video tracks encoded in formats not supported by your browser.
