### ISSUE TITLE
mkv mute can i import wav audio file manually?

### ISSUE THREAD

**Issue by laovvai** [killergerbah/asbplayer#308]
I've been trying to open an mkv file in asbplayer but each time it's mute and has no subtitles. 
I managed to extract subtitles and drop it in the player. Can i do the same thing for the audio file? 
Or should I try to change the browser? What to do if there is no audio playing?
Thank you in advance!

**Comment by killergerbah** [comment]
Subtitle detection of subtitle tracks embedded inside mkv files is not currently supported. As you suggested, you can instead extract the subtitles and open those with asbplayer instead. Also, some audio codecs will not be supported by your browser, which is the problem you are probably experiencing now. If you already know how to extract the subtitles, you can as you suggested extract the audio into a different format and try that.

**Comment by killergerbah** [comment]
There is already an issue for subtitle extraction from MKVs.
