### ISSUE TITLE
I can't find the ease of use features

### ISSUE THREAD

**Issue by doctorhibert** [killergerbah/asbplayer#310]
I came here since animebook says it's deprecated and that this app is more focused on ease of use and has extra features. I'm not sure if I'm completely missing the part where these features are explained in the guide, but I wanted to ask if the following features from animebook are here, and if so, how to use them:

The first one is resizing the subtitle history, like so:
![brave_Q9rBrQsOsc](https://github.com/killergerbah/asbplayer/assets/46629336/94181575-71b6-4833-b39a-966fef2a71e3)
But I can't do it on asbplayer, is there an option for that anywhere?:
![brave_pxYWoEbH8z](https://github.com/killergerbah/asbplayer/assets/46629336/1aba1f62-abe0-402c-b410-ed37e2f42ec9)

The second problem is the subtitles. I honestly have no idea about all the options in the settings menu, I just want regular, normal looking subtitles like animebook has by default. I never had to touch any options for the subs in animebook to look like that: white, with no background, and they look fine in front of any background.
![image](https://github.com/killergerbah/asbplayer/assets/46629336/0a4351e6-38a8-436c-b86e-03eb465ca118)
I messed around with the options for a long time and the best I could do is this:
![image](https://github.com/killergerbah/asbplayer/assets/46629336/791a7f4e-4578-4941-83d3-6afec1a012ab)
I legitimately do not want anything fancy, I just want normal looking subtitles. I don't even know how to reset the options for the subtitles

Then there's the audio track selection. The documentation says that you can change the audio track for MKV files, but what about the rest? I can change the audio track for this file just fine in animebook, but I can't find the option on asbplayer.

And the final thing, which is the most important to me, is the mining process. On animebook I can just press the plus sign next to any subtitle, and it instantly adds the image, audio and sentence for that subtitle onto the last created anki card. I don't need to go back to that subtitle, pause the video, or open any dialog box. That is to say, I can create anki cards instantly without stopping, or having to go back to the line where the word originally appeared like so:
![brave_bqXEf6msmO](https://github.com/killergerbah/asbplayer/assets/46629336/7cd0c1b5-b813-424b-acfe-c815aba669ab)
I'm not sure how to do this on asbplayer, since I have to either open the mining dialog with ctrl+shift+x, or if I try ctrl+shift+u, I still need to go back to the original line, and this also stops playback, so I have to wait until the recording is finished to keep going.
Am I missing something? Is there a way to activate mining like in animebook?

**Comment by killergerbah** [comment]
Thanks for the feedback, all good points. Some of these can be addressed easily such as the one about the resizable subtitle list, but most of the points you bring up will take more time and thought.

- Blurry subtitles: I don't know why this is happening so I don't know what the fix or workaround would be. I can only suggest turning off background transparency, subtitle outlines, and removing antialiasing. But it sounds like you've probably already tried this.

- Audio tracks: Tracks will show up if experimental web platform features are enabled. I'm not sure why animebook would show subtitle tracks for a file while asbplayer doesn't, since both players should be using the same API to access the tracks. But I would be curious to know the name of the file you're observing this with.

- Mining: Using ffmpeg to clip audio the same way animebook does is a possibility and could potentially be a feature in the far future. For the time being, asbplayer will continue to rely on the audio recording capabilities of the browser. Because of this, asbplayer is a little bit more optimized for streaming video than local video files.

**Comment by doctorhibert** [comment]
I'm not sure about the subs, even if I turn off outlines it doesn't look good, and messing with the outline thickness never produces something as good as standard subs (maybe it's to do with the opacity of the outline?). Is there a way to check the "default settings" for subs in animebook?

The file is this release of watamote, which has dual audio that defaults to English:
https://nyaa.si/view/1160703
Maybe I just couldn't find the keybind/button? I could only find how to switch the subtitle tracks, not the audio.

Like you said, the reason I decided to try asbplayer is because it can stream video unlike all the other programs, but the way it mines audio doesn't really work for me. Even with anacreon's MPV script, while you do need to go back to the subtitle file, you don't need to actually pause the video to record audio. Do you mean to say that mining works like animebook is you're watching a stream instead of a local file? If it's to do with the browser, would using Marmaduke's browser help with that?
If anything, something you could do for the moment is let you click a plus sign next to each subtitle line to add that line/video/audio to the most recent card. Even if you do have to pause the video to record it, at least you wouldn't have to go back and could keep watching from wherever you were.

**Comment by alszczep** [comment]
I have a similar issue with the subtitles, what I was able to find is that animebook approaches outlines differently.

currently in asb:
```
-webkit-text-stroke: #000000 1px !important;
``` 

![image](https://github.com/killergerbah/asbplayer/assets/44731926/b0d5f653-a557-4707-9273-f206f8c014bf)
![image](https://github.com/killergerbah/asbplayer/assets/44731926/4efc0f2b-1feb-4caa-a60b-03678f0b7d5a)

vs copied from animebook:
```
text-shadow: 0.04em 0 0.03em hsl(0, 0%, 0%),
    0 0.04em 0.03em hsl(0, 0%, 0%),
    -0.04em 0 0.03em hsl(0, 0%, 0%),
    0 -0.04em 0.03em hsl(0, 0%, 0%),
    -0.04em -0.04em 0.03em hsl(0, 0%, 0%),
    -0.04em 0.04em 0.03em hsl(0, 0%, 0%),
    0.04em -0.04em 0.03em hsl(0, 0%, 0%),
    0.04em 0.04em 0.03em hsl(0, 0%, 0%);
```

![image](https://github.com/killergerbah/asbplayer/assets/44731926/fd759966-8106-452d-88d7-0f265ec0b496)
![image](https://github.com/killergerbah/asbplayer/assets/44731926/cf2d8749-2fb8-43ae-9a05-d35b2b45bc04)

```
text-shadow: 0.08em 0 0.06em hsl(0, 0%, 0%),
    0 0.08em 0.06em hsl(0, 0%, 0%),
    -0.08em 0 0.06em hsl(0, 0%, 0%),
    0 -0.08em 0.06em hsl(0, 0%, 0%),
    -0.08em -0.08em 0.06em hsl(0, 0%, 0%),
    -0.08em 0.08em 0.06em hsl(0, 0%, 0%),
    0.08em -0.08em 0.06em hsl(0, 0%, 0%),
    0.08em 0.08em 0.06em hsl(0, 0%, 0%);
```

![image](https://github.com/killergerbah/asbplayer/assets/44731926/ffdd7cbe-7ac0-48e5-bafc-4ea5a4d44241)
![image](https://github.com/killergerbah/asbplayer/assets/44731926/045a3e79-faee-431a-8be3-e7dda78beebb)

From what I see fixing it in asb is easily possible by setting custom CSS in settings, but maybe the default could be slightly adjusted.

**Comment by doctorhibert** [comment]
Sorry, I'm dumb. Which numbers exactly do I need to put in to each of the asbplayer subtitle options for my subs to look like that? Or do I need to mess with the css?

**Comment by alszczep** [comment]
![image](https://github.com/killergerbah/asbplayer/assets/44731926/dc223cec-3275-415a-b1f3-ea97de2dfe72)

You can change it here, in settings, that's how I have it set up for myself. To add a new property you can search for it in the `Add Custom CSS` field and click `+`. You need `unset` for `webkitTextStroke` to remove the default border. In the field for `textShadow` you can try putting: 
`0.04em 0 0.03em hsl(0, 0%, 0%),
    0 0.04em 0.03em hsl(0, 0%, 0%),
    -0.04em 0 0.03em hsl(0, 0%, 0%),
    0 -0.04em 0.03em hsl(0, 0%, 0%),
    -0.04em -0.04em 0.03em hsl(0, 0%, 0%),
    -0.04em 0.04em 0.03em hsl(0, 0%, 0%),
    0.04em -0.04em 0.03em hsl(0, 0%, 0%),
    0.04em 0.04em 0.03em hsl(0, 0%, 0%)`
and see if it looks okay for you. If you want it thicker you can use:
`0.08em 0 0.06em hsl(0, 0%, 0%),
    0 0.08em 0.06em hsl(0, 0%, 0%),
    -0.08em 0 0.06em hsl(0, 0%, 0%),
    0 -0.08em 0.06em hsl(0, 0%, 0%),
    -0.08em -0.08em 0.06em hsl(0, 0%, 0%),
    -0.08em 0.08em 0.06em hsl(0, 0%, 0%),
    0.08em -0.08em 0.06em hsl(0, 0%, 0%),
    0.08em 0.08em 0.06em hsl(0, 0%, 0%)`
or simply manually scale the values before each `em`. Ofc you can also change the color by replacing `hsl(0, 0%, 0%)` with whatever you like (https://hslpicker.com/)

**Comment by killergerbah** [comment]
> Do you mean to say that mining works like animebook if you're watching a stream instead of a local file? If it's to do with the browser, would using Marmaduke's browser help with that?
> If anything, something you could do for the moment is let you click a plus sign next to each subtitle line to add that line/video/audio to the most recent card. Even if you do have to pause the video to record it, at least you wouldn't have to go back and could keep watching from wherever you were.

Sorry, I mean that for asbplayer to work with streaming video it has to seek to the subtitle and record the audio, and it uses a similar mechanism to record audio for local files. This is the opposite of what you want.

In order for asbplayer to work like animebook it would need to use ffmpeg to clip audio and screenshots out of local files.

**Comment by killergerbah** [comment]
The subtitle list is now resizable, and text shadow is now available as a setting. I've created another issue for more efficient media capture using ffmpeg: https://github.com/killergerbah/asbplayer/issues/329
