### ISSUE TITLE
Scaling video element

### ISSUE THREAD

**Issue by alszczep** [killergerbah/asbplayer#311]
The video that I am trying to use for some reason has big black bars on the sides that make the actual content pretty small. I wasn't able to find any way to make it larger. It's not really a bug in the app, rather something with the video file itself, but I thought that it may be worth adding since it should be as easy as putting a new property in settings which would control the video size with `transform: scale()`.
Also if it's okay for you I could try posting a PR handling this.

**Comment by killergerbah** [comment]
Given that the use case for a setting like that would be very limited I would be hesitant to support it in asbplayer. Have you tried modifying. the styles directly using the developer console?

**Comment by alszczep** [comment]
I can change it, but I will be changed back after each reload. However, I found another solution which is still fairly simple too, this can be done with a browser extension ([Stylebot](https://chromewebstore.google.com/detail/oiaejidbmkiecgbjeifoejpgmdaleoha)), so I guess we can consider this issue solved.

**Comment by killergerbah** [comment]
Glad you found a solution.
