### ISSUE TITLE
Anki Connect URL 

### ISSUE THREAD

**Issue by SumZbrod** [killergerbah/asbplayer#315]
I again have this exception. I try to use another python versions, but not help. 
`Type object 'QMessageBox' has no attribute 'Question'`
This looks like a python package error. I have:
Python 3.12.0 \ 3.9.9
![image](https://github.com/killergerbah/asbplayer/assets/71086504/449a90a6-44d1-43bc-bca5-f39f31e14ae9)

**Comment by killergerbah** [comment]
@SumZbrod Make sure that in the cors settings for AnkiConnect that there is no `/` at the end of `https://killergerbah.github.io/asbplayer`

**Comment by Eodis** [comment]
I'm having the exact same issue here. And no `/` around

**Comment by killergerbah** [comment]
This seems to be an issue related to Anki trying to display the "request permissions" UI so I would suggest updating Anki and if that doesn't work I can start looking into workarounds.

**Comment by killergerbah** [comment]
This issue was solved outside of this thread. The problem was using `https://killergerbah.github.io/asbplayer` instead of the actual origin which is `https://killergerbah.github.io`
