### ISSUE TITLE
Update last card feature not working properly

### ISSUE THREAD

**Issue by uehasuuu** [killergerbah/asbplayer#316]
I've run into a bug where I have to press "update last card" twice to update the card while it's open in Anki. If the card isn't open in Anki though I only have to press it once. I've tried reinstalling and downgrading both asbplayer and Anki but that didn't fix it.

https://github.com/killergerbah/asbplayer/assets/152575560/535b7d85-95e7-4be5-a009-aa01f6129918

**Comment by killergerbah** [comment]
This is a known issue with AnkiConnect https://github.com/FooSoft/anki-connect/issues/82

**Comment by uehasuuu** [comment]
Unless I missed something, it looks like there's no direct fix then. Thanks for the quick response.

**Comment by killergerbah** [comment]
Yeah, you'll just need to keep the card browser closed when updating last card. Or a fix needs to be submitted to AnkiConnect.
