### ISSUE TITLE
ASBplayer is automatically copying every new line of subtitles

### ISSUE THREAD

**Issue by jam-madrigal** [killergerbah/asbplayer#321]
I've noticed asbplayer is automatically copying subtitles as they appear on YouTube. As demonstrated in the video, by yomichan automatically searching anything on my clipboard, it can be observed that as long as a subtitle track is loaded in asbplayer the subtitles are being continuously copied without input from the user. This issue was only noticed today.

I have now confirmed it to be happening on netflix as well.

Video:

https://puu.sh/JVYpn.mp4

**Comment by killergerbah** [comment]
@jam-madrigal I have deployed a fix for this issue. Can you let me know if you are still experiencing it?

**Comment by jam-madrigal** [comment]
> @jam-madrigal I have deployed a fix for this issue. Can you let me know if you are still experiencing it?

Been testing it over the past few minutes and so far it seems like I can't replicate the issue anymore. Thanks.
