### ISSUE TITLE
Nothing happen when I try to "Update last card"

### ISSUE THREAD

**Issue by freegood93** [killergerbah/asbplayer#335]
After pressing "ctrl+shift+X" (Mine current subtitle and open Anki dialog), I click on "Update last card", the buttons grey out and nothing happen
I didn't changed anything since and it stoped working out of nowhere (I'm using firefox)

**Comment by killergerbah** [comment]
@freegood93 I have deployed a fix for this. Based on the nature of the fix, it seems that there was a change to how Firefox loads audio, so I suspect that you started experiencing the issue after a Firefox update. If you can let me know whether the fix worked. Thanks!

**Comment by wathan** [comment]
I got this problem as well on Brave Browser.
Click "Update last card" in Anki dialog and get "Invalid Request" pop up.
Updating the card with "Update last-created Anki card with asbplayer-captured screenshot, audio, etc." (default ctrl+shift+u) works fine though.

**Comment by killergerbah** [comment]
@wathan That's a similar bug that has been fixed in the latest version of the extension.
