### ISSUE TITLE
Anki mining issue for H265 MKV videos

### ISSUE THREAD

**Issue by Shichiya-San** [killergerbah/asbplayer#336]
Currently using asbplayer on Edge version 120.0.2210.77 with the HEVC support extension from the Microsoft store. Browser extension H265ify was also installed to enable the H265 codec on Edge since apparently this browser does not officially support H265 codec. 

Video plays fine on both H264 and H265 MKV videos but when I specifically want to mine words from a H265 MKV video, the anki screenshot returns a blank image, and the sentence audio are not properly recorded. Attempting to mine words with the option "Re-encode audio as MP3" enabled returns error below:

![image](https://github.com/killergerbah/asbplayer/assets/68813643/78fcc3c0-221d-43b5-a206-c622d5ed8fa6)

Test from https://html5test.com/ returns most audio and video codec supported as well.

![image](https://github.com/killergerbah/asbplayer/assets/68813643/d1588742-7970-4c42-a0e5-7443f76c62cb)

**Comment by killergerbah** [comment]
@Shichiya-San Does image/audio capture work correctly with non h265 videos?

**Comment by Shichiya-San** [comment]
Yes, other video files such as MP4 and H264 videos worked with no problem.

**Comment by killergerbah** [comment]
@Shichiya-San Can you confirm that you're experiencing this problem on https://killergerbah.github.io/asbplayer/ right now? I fixed a problem with audio recording earlier today and want to make sure that you are experiencing a different problem than that one.

**Comment by Shichiya-San** [comment]
@killergerbah Yes this problem exists on the web browser asb video player. The asbplayer browser extension is not installed either.

Below image shows the screenshot I get when I attempt to mine a word from H265 video.
![image](https://github.com/killergerbah/asbplayer/assets/68813643/9eb0cce6-93af-4fb6-ae4b-089949ad96a1)

**Comment by killergerbah** [comment]
@Shichiya-San I've been unable to reproduce the issue, but I'm wondering if you are also experiencing this problem on Chrome. Later versions of Chrome support H265 as long as your hardware supports it. If you have the time do you think you could give Chrome a try?

**Comment by Shichiya-San** [comment]
@killergerbah Tested it on Chrome ver.120.0.6099.110 and seems like there's no problem there. Screenshot and audio capture worked perfectly on Chrome. Could it be that Edge has some problem with the H265 codec since HEVC support extension from Microsoft does not officially support H265 codec on Edge? If I try disabling H265ify extension, the Edge browser no longer support H265 format as stated by https://html5test.com/. However despite removing the H265ify extension, the video can still be played normally.

**Comment by killergerbah** [comment]
@Shichiya-San I'm not completely sure, but h265ify + Edge not being enough for asbplayer to work properly seems like a reasonable guess. For now I would recommend just using Chrome if that is no trouble for you.

**Comment by Shichiya-San** [comment]
@killergerbah Understood, I'll be using Chrome for the time being. Thank you.
