### ISSUE TITLE
Not updating card in Anki

### ISSUE THREAD

**Issue by penguinbrew** [killergerbah/asbplayer#337]
Every time i update most recent card, asb player says: updated card 123123etc., but the card isn't updated in Anki. Sometimes deleting the card, restarting anki and remaking the card seems to help, but only for the first card.

**Comment by killergerbah** [comment]
@penguinbrew There's a known issue with AnkiConnect where cards won't update if the card browser is open. Could this be what is happening for you?

**Comment by penguinbrew** [comment]
That seems to have been the issue, thank you for the quick reply. I was afraid I would have to abandon this wonderful tool.
