### ISSUE TITLE
Image not displaying on card with AnkiConnect, despite being present. Cut and paste fixes the issue. Why?

### ISSUE THREAD

**Issue by elemn** [killergerbah/asbplayer#338]
I'm running into a weird issue. When I mine a card, I usually use Yomichan for the lookup and card creation, then ASB player for the update card. It captures everything perfectly, but when I preview the card in Anki the image does not show. Despite being present in the card field. If I cut the image to my clipboard, then paste again, it suddenly starts showing up. Why might this be the case ? Is it a known bug?

**Comment by killergerbah** [comment]
@elemn There's a known issue with AnkiConnect where cards won't update if the card browser is open. Could this be what is happening for you?

**Comment by elemn** [comment]
If by card browser you mean clicking browse, where a window pops up, then no I don't believe that's the case. I made sure to close it and the issue remains. Is that known issue exclusive to image media or everything else ? All other information transfers okay. Perhaps this is an issue on the side of my card template? Image format? Any other ideas would be appreciated.

I'm on Linux by the way, AnkiConnect seems to be up to date and I have the latest version of ASBPlayer installed on Chrome.

**Comment by elemn** [comment]
Update: I looked in the CSS (not mine), and this line seems to have something to do with it : `.images br,
.images> :not(img) {
    display: none;
    visibility: hidden;
}`

**Comment by killergerbah** [comment]
@elemn asbplayer wraps the `img` in a `div` so that's probably why.
