### ISSUE TITLE
Asbplayer "Failed to fetch" AnkiConnect

### ISSUE THREAD

**Issue by Sfoyarbide** [killergerbah/asbplayer#339]
Absplayer cannot connect to Anki Connect even if I already added "https://killergerbah.github.io is in the webCorsOriginList", it just says "Faild to fetch". 

Absplayer error:
![image](https://github.com/killergerbah/asbplayer/assets/63980929/27067263-b4ba-4f27-959f-b991e07e3cd2)

Configuration of AnkiConnect:
![image](https://github.com/killergerbah/asbplayer/assets/63980929/e526c4e3-4e0d-4299-8c43-ca3ed6353f70)

I tried everything at my hand, but I keep getting the same error; I don't know what else I could do, therefore I think it's a weird bug.

**Comment by killergerbah** [comment]
@Sfoyarbide Check out the suggestions here and see if one of them works for you: https://github.com/killergerbah/asbplayer?tab=readme-ov-file#asbplayer-cant-connect-to-anki-it-shows-an-error-message-eg-failed-to-fetch

**Comment by Sfoyarbide** [comment]
The problem was for Shield in Brave. 
Thank you so much, and sorry for the trouble.

**Comment by jdolanc** [comment]
I tried to take off my VPN, and the shield in Brave but still showing failed to fetch.
