### ISSUE TITLE
incorrectly updating latest anki card (black screenshot, no audio)

### ISSUE THREAD

**Issue by pekoraptor** [killergerbah/asbplayer#341]
when autoconvert audio to mp3 is enabled, it says "failed to execute 'decodeAudioData'" when i press the shortcut for updating previous anki card. When autoconvert is off, it says "update card" and then when i check the card, there is just a black screenshot and no added audio. I'm on Edge using asbplayer website if that matters.

**Comment by killergerbah** [comment]
Hi @pekoraptor , can you give either vanilla Chrome or one of the all-codecs Chromium builds listed [here](https://chromium.woolyss.com/) a try instead? I seem to see reports recently about Edge not working well with asbplayer.

**Comment by pekoraptor** [comment]
@killergerbah, thank you for answering so quickly. I've tried it with chrome and it works perfectly. The github readme for this project recommended using Edge, so i was surprised, but i guess it's just the browsers fault. Thank you for creating such a good tool for language learning.
