### ISSUE TITLE
One line youtube subtitles

### ISSUE THREAD

**Issue by Kellen-wq** [killergerbah/asbplayer#343]
**Is your feature request related to a problem? Please describe.**
in asbplayer, as well as in parent mpv, autogenerated youtube subtitles are shown in 2 lines. 1 line is always the past, unnecessary line. this is quite inconvenient to use, because you get confused all the time, besides it is all copied to the anki card.

**Describe the solution you'd like**
show only the bottom line.

**Describe alternatives you've considered**
it works fine in LanguageReactor, would be nice if it would work in asbplayer as well.

**Comment by codeguruuu** [comment]
i agree this would be a nice feature to have

**Comment by killergerbah** [comment]
This is implemented on the website and will be released with the next version of the extension. Extension users can benefit from the website fix now if they enable the 'open subtitle list when loading subtitles option.'
