### ISSUE TITLE
Recording starts from wrong point

### ISSUE THREAD

**Issue by erikji** [killergerbah/asbplayer#346]
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.01.04-17_20_32.webm](https://github.com/killergerbah/asbplayer/assets/87676483/42b399a8-8d79-42d0-9005-d3cb2aa639dd)

Using the latest version, though I just updated Chrome. The recording starts a few seconds earlier than when it should. (In the video, it actually ends up recording the previous subtitle.)

**Comment by killergerbah** [comment]
Hi @erikji , did this problem just start happening?
I've seen reports of problems in the past of precise seeking being kind of broken on Netflix's video player, particular for slower/older computers.

**Comment by erikji** [comment]
Yes, it just started. The computer I'm using is a 2016 MacBook if that helps.

**Comment by killergerbah** [comment]
@erikji Do  you mind sharing the name of the video you're watching?

**Comment by erikji** [comment]
Switched

I also tried it on Stand By Me Doraemon which had the issue as well. The program seems to get 'stuck' to a certain timestamp sometimes.

**Comment by erikji** [comment]
I just tried again with the old version of asbplayer. It appears to be an issue with subtitle offset that affects recording but not subtitle display, if that helps.

**Comment by GriefBacon** [comment]
I'm having a similar issue on Brave browser.

Using a Macbook Air M1
Both ASB player and Brave browser are up-to-date.

I've tried both on Dungeon Meshi and Monster. It seems to be grouping subtitle tracks in two's.

**Comment by killergerbah** [comment]
For some reason (possibly CPU core count) Netflix does not allow precise seeking on some devices by default. A speculative fix for this is implemented (see Discord server for snapshot release).
