### ISSUE TITLE
'Seek to next subtitle' cannot seek if both the media is a certain point and it's paused

### ISSUE THREAD

**Issue by artjomsR** [killergerbah/asbplayer#348]
To replicate:
go to this video https://www.youtube.com/watch?v=YUean65jji8
pause playback
hold Seek to next subtitle key

Eventually it fails to seek to the next subtitle for me. E.g. these are the trouble timestamps that I've found:
1:06
4:26
8:33

Seek to previous subtitle doesn't seem to suffer from the same issue - if I go to the end of the video and hold that shortcut, it can fast-forward all the way to the beginning (while paused).

I can reproduce the same thing with other YT videos, but the timestamps are different.

**Comment by killergerbah** [comment]
I believe this is due to float imprecision causing the seek destination to end up slightly before when the subtitle is actually supposed to appear.

**Comment by killergerbah** [comment]
02c29a69484a213a7e8b91956ac1dbb5e8d494e7
