### ISSUE TITLE
Automatically play media when invoking 'Seek to beginning of current'

### ISSUE THREAD

**Issue by artjomsR** [killergerbah/asbplayer#349]
I've mentioned this one in discord. Implementation-wise, it's as simple as adding `context.play();` to `extension\src\services\key-bindings.ts:_unbindSeekToBeginningOfCurrentSubtitle`.

You mentioned that you'd prefer this to be a setting, and this is where I got stuck - that file doesn't seem to be using any settings at the moment. And I'm not sure what's the best way to import them.

**Comment by killergerbah** [comment]
The approach I would take is to add the new setting, and then cache it as an instance variable in `Binding._refreshSettings`. Then in `_unbindSeekToBeginningOfCurrentSubtitle` you can access the cached variable through `context` to decide whether to `play()` or not.

**Comment by artjomsR** [comment]
Closed as completed, thanks for the help with implementation tips :)
