### ISSUE TITLE
Toggle timestamps in side panel

### ISSUE THREAD

**Issue by voothi** [killergerbah/asbplayer#353]
**Is your feature request related to a problem? Please describe.**
I use an external translator (QTranslate) and when I try to select the text of several subtitles to translate the entire sentence, timestamps end up in the copied text.

**Describe the solution you'd like**
I would like to be able to turn off the display of timestamps and/or be able to highlight text without timestamps.

**Describe alternatives you've considered**
Opening the YouTube Transcript panel separately is not convenient. You have to scroll down the screen every time to highlight the text. In YouTube Transcript, I can disable timestamps and copy multiple subtitles.

**Additional context**
Perhaps the issue here is changing the sidebar template. Or creating a new button to hide timestamps like in YouTube Transcript.

**Comment by voothi** [comment]
<img width="302" alt="image" src="https://github.com/killergerbah/asbplayer/assets/9587340/c4763dc1-8017-4f3b-adbc-66260aef23e1">

**Comment by voothi** [comment]
<img width="347" alt="image" src="https://github.com/killergerbah/asbplayer/assets/9587340/c0c4fdcd-9ea5-437b-9fdd-05bb51ef7631">
<img width="352" alt="image" src="https://github.com/killergerbah/asbplayer/assets/9587340/447e5078-64c2-458c-90f0-ae01afbe8942">

**Comment by killergerbah** [comment]
I have made a change to make the timestamps unselectable, since they are not very useful to select anyway. I am considering implementing an option to hide timestamps. Either change will be in the next extension release which may or may not be soon.

**Comment by phamthaison1207** [comment]
actually, I think the time stamps are really useful for listening practice, if the options to hide the text are available

**Comment by killergerbah** [comment]
For now the timestamps are not selectable. This will release with extension version 1.1.
