### ISSUE TITLE
Make screenshots savable/copy to clipboard + subtitles below video

### ISSUE THREAD

**Issue by FirionHope** [killergerbah/asbplayer#360]
I'm coming from animebook since it's having audio issues on occasion now. There's a couple of features from there that're really essential to me and I think might be handy to others.

One is making screenshots either savable (preferred) or at least copyable to clipboard. I like to share screenshots of stuff I watch. There's an option in the settings to manually take screenshot, but it seems to be for anki mining only, I want to be able to just save the screenshot, or at least copy it to the clipboard on its own, separate from any anki stuff.

Another is having the subtitles be below the video instead of on top of the video. I prefer this as it's not covering up the video, would be great to have as an option.

Other than that it seems like everything works really well!

**Comment by killergerbah** [comment]
@FirionHope At the very bottom of the subtitle display settings you can adjust the subtitle position offset from the bottom of the screen. Hopefully that achieves what you are looking for.

About copying screenshots to clipboard, thanks for the suggestion. That would not be so hard to implement.

**Comment by FirionHope** [comment]
> @FirionHope At the very bottom of the subtitle display settings you can adjust the subtitle position offset from the bottom of the screen. Hopefully that achieves what you are looking for.
> 
> About copying screenshots to clipboard, thanks for the suggestion. That would not be so hard to implement.

Oh great thanks!

About the subtitle offset, I'm not seeing the option? At the bottom of subtitle appearance I'm only seeing "image based subtitle scale factor" which doesn't seem to move the subtitles and none of the other options seem to be it either. Just to be clear I'm not speaking about the timing offset, just the actual position of them relative to the video, though if I'm not able to do that I can live without it, just would be a nice to have.

**Comment by killergerbah** [comment]
@FirionHope This is the setting I'm talking about:
![image](https://github.com/killergerbah/asbplayer/assets/2254858/8b25cb1a-02ea-436f-a618-b163e8fa0c4b)

**Comment by FirionHope** [comment]
@killergerbah option wasn't showing up for me, I installed the extension though and it shows up now. Is that intended behavior?

**Comment by killergerbah** [comment]
@FirionHope Yeah that is currently the intended behavior, although it is confusing enough that even I had forgotten about it. If you don't have the extension installed it's possible to use the scrollwheel to change the position offset instead.

**Comment by killergerbah** [comment]
For what it's worth, I've enabled those settings on the website even if the extension is not installed.

**Comment by FirionHope** [comment]
Did there ever end up being a way to either copy screenshots to keyboard or save them? As it is I have to use ShareX which is a little inconvenient.
