### ISSUE TITLE
Make work asbplayer in librewolf or mozilla firefox

### ISSUE THREAD

**Issue by sponner22** [killergerbah/asbplayer#361]
**Is your feature request related to a problem? Please describe.**
Hi there, i'd like that asbplayer would be available for browsers that doesn't use chronium extensions, recently i stopped using opera gx cuz it use spywares to sell my data, and i don't like, furthermore, i reformatted and cleaned my computer, nevertheless, i don't know if even possible that a developer can write some codes or publish this addon in the mozilla firefox store. I love asbplayer, but i hate centralized plataforms that use spywares. 

I read before that some tried to do it, but this guy couldn't do anymore, sadly.
This is not a issue, just a recommendation.

**Comment by phly95** [comment]
Firefox lacks a lot of the codecs that would make asbplayer useful on many video files. Animebook recommends an all-codecs+ build of Chromium from here: https://chromium.woolyss.com/ but Microsoft Edge may work as well.

The good news is that these are open source forks that don't sell your data (at least the ungoogled ones), so you can use this player without the Google or Opera spyware.

**Comment by killergerbah** [comment]
Duplicates https://github.com/killergerbah/asbplayer/issues/62
