### ISSUE TITLE
Version 1.0.1 not recording audio or screenshots on Netflix

### ISSUE THREAD

**Issue by Wanna-Play-Frisbee** [killergerbah/asbplayer#362]
Not sure what's going on here -- running on Windows 11, latest Chrome release Version 120.0.6099.225 (Official Build) (64-bit). Using Ctrl + Shift + X to open the Anki dialog, the captured audio file is silent (same with or without "re-encode as mp3"). Further, screenshots don't work at all -- no image is populated in the dialog, no matter the combination of "Take Screenshot", "Clean Screenshot", and "Crop Screenshot". My console also fills up with errors that look like:
```
cadmium-playercore-6.0043.486.911.js:1 
POST` https://www.netflix.com/msl/playapi/cadmium/logblob/1?reqAttempt=1&reqName=logblob&clienttype=akira&uiversion=vf37ed0df&browsername=chrome&browserversion=120.0.0.0&osname=windows&osversion=10.0 net::ERR_BLOCKED_BY_CLIENT
d @ cadmium-playercore-6.0043.486.911.js:1
(anonymous) @ cadmium-playercore-6.0043.486.911.js:1
...
anki-ui.js:2 [Report Only] Refused to connect to 'data:audio/mp3;base64,//u0BAAP8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAETEFNRQMACQgABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' because it violates the following Content Security Policy directive: "default-src https: wss: 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```
[Full console log trace on hastebin](https://hastebin.com/share/cakizewili.csharp). YouTube and other sites, however, work just fine. Any advice on how to get this working with Netflix?

**Comment by killergerbah** [comment]
@Wanna-Play-Frisbee I'm not exactly sure why Netflix has issues for some people. You could try flipping hardware acceleration on and off in your browser settings.

**Comment by Wanna-Play-Frisbee** [comment]
Actually, that fixed it for me -- thanks! I feel a bit silly for not trying that sooner

**Comment by killergerbah** [comment]
Glad that it fixed it for you. Just be aware that when hardware acceleration is off you will find that your browser will eat a lot more CPU just to play videos on any website.
