### ISSUE TITLE
Audio track selector does not appear in Sidekick

### ISSUE THREAD

**Issue by Arctagon** [killergerbah/asbplayer#366]
The audio track selector does not appear in the browser Sidekick, which is based on Chrome. Experimental web platform features enabled. I tried with the same settings and setup in Chrome, and it the selector appears just fine there.

**Comment by killergerbah** [comment]
It appears that the browser doesn't support the API required by asbplayer to display the track selector, so unfortunately there isn't anything that can easily be done from the asbplayer side.
