### ISSUE TITLE
Softcoded subtitle within a local video isn't detected by asbplayer

### ISSUE THREAD

**Issue by Claude-Kenni** [killergerbah/asbplayer#373]
**Is your feature request related to a problem? Please describe.**
Yes. When I tried to play a local video file that has already have softcoded subtitles. It isn't being detected nor loaded by the player. For example, I am watching this show that has 2 softcoded subtitles within it, but it doesn't load the subtitles.

**Describe the solution you'd like**
The subtitles should be loaded.

**Describe alternatives you've considered**
For now, I'm using a software called "Subtitle Edit' to manually extract the subtitles from a video and dropping it in asbplayer.

**Additional context**
![image](https://github.com/killergerbah/asbplayer/assets/97787671/99a7874f-66ae-458a-a098-e8fd4bb7737b)

![image](https://github.com/killergerbah/asbplayer/assets/97787671/f114f947-1c09-4628-a30f-80478ee13f45)

**Comment by killergerbah** [comment]
Duplicates https://github.com/killergerbah/asbplayer/issues/88
