### ISSUE TITLE
MKV file don't have any sound (multiple audio tracks)

### ISSUE THREAD

**Issue by MartinMeda** [killergerbah/asbplayer#375]
Hi,
I look up on the readme and youtube video since an hour and honestly, I don't see what I may have miss now, so I post a message here.

I :
- use Chrome version 122.0.6261.70 (Build officiel) (64 bits) on windows
- have enabled "experimental web platform features"
- enable material acceleration in setting too (even if I have images, just no sound)
- install the plugin twice (delete local folder and plugin in chrome and unzip and install it again)
- test several video files (some with a audio track set as default, some doesn't, some with video encoded as h265 and some with h264)

But I didn't manage to have sound on any of my video with multiples audio tracks (for those with just one track, it works perfectly) using asbplayer (but it works on vlc or mpv)

From what I see on the readme, I must have a audio track selector, but I didn't found it. I see no new buttons on the player
![image](https://github.com/killergerbah/asbplayer/assets/25613747/b08028eb-7857-4fad-b869-a50e9b75f7f0)
And the other tab don't seem to have any button or selection available on it
![image](https://github.com/killergerbah/asbplayer/assets/25613747/255c60e0-e0ec-42b9-b0ae-3803dd064246)

I hope I just miss somethinig (like I miss the audio track selection button) and I'm sorry to waste your time seeking help, but I really don't find what I did wrong.

**Comment by MartinMeda** [comment]
Okay I got sound back with chronium ([Marmaduke all-codecs+ builds](https://chromium.woolyss.com/)) as said in https://github.com/animebook/animebook.github.io?tab=readme-ov-file#video-format-support-last-update-january-2023
However, I still don't find a way to select the audio track (I enable "Experimental Web Platform features" on chronium too), so if the default audio track is a wrong one, I have to modify the file manually before using it.

I leave the ticket alive because this audio track selection feature is described in the readme (https://github.com/killergerbah/asbplayer/blob/main/README.md#audio-track-selection-for-mkv-files)

Again if I'm just blind, please show me the way ;)

P.S : And well, I don't know how much people learn several language in the same time, but having a language track configuration would be great I think.

**Comment by killergerbah** [comment]
When I enable experimental web platform features, restart the browser and load an mkv file with multiple audio tracks, the audio track selector appears at the bottom-right of the screen:
<img width="656" alt="image" src="https://github.com/killergerbah/asbplayer/assets/2254858/76e03572-fbdd-4c77-9c2b-e84c7ea5f54e">

What is the name of the file with which you're seeing this problem?

**Comment by MartinMeda** [comment]
I downloaded MKVToolsNix, and the issue seem to appears when a DTS-ES audio tracks is present (they're not detected)
Here an exemple with default tracks :
![image](https://github.com/killergerbah/asbplayer/assets/25613747/f7a7567d-2e74-4ef7-b0b2-ea401e15fc75)
If I extract all audio exept DTS one, I have no sound on the browser

When I try with another video (with  EAC audio track) and It works well
![image](https://github.com/killergerbah/asbplayer/assets/25613747/badc7bc6-2c1e-4bef-a4fb-cf159c16bd91)
Here a picture of its tracks :
![image](https://github.com/killergerbah/asbplayer/assets/25613747/300bb122-4a00-43e9-a718-dfde0f05c71c)

Don't know if it's a broswer support issue, but I don't find DTS in the list tested by "all-codecs+" flag (https://tools.woolyss.com/html5-audio-video-tester/), so it must be it.

Sorry for this ticket, I didn't know audio track support is just a mess on browser.

P.S : Thanks for your works

**Comment by killergerbah** [comment]
Makes sense, it does seem that Chromium does not support DTS audio yet.
