### ISSUE TITLE
Toggle subtitle hotkeys stop working under a certain circumstance

### ISSUE THREAD

**Issue by avc1657** [killergerbah/asbplayer#382]
I noticed that after doing a look up with Yomitan, even after closing the pop up window, the subtitle toggle hotkeys stop working unless I left click the video. I need to specifically left click the video, left clicking the subtitles does not fix the problem. I don't even know if that's a bug or not, just reporting it. I sometimes want to toggle a secondary sub but because of the "bug" I need to left click the video and if it was already paused, left clicking will play it, but I want it to remain paused so you need to left click again. Anyways, it's annoying. But as I said, I don't even know if that's a bug, maybe it's the expected behavior.

Edit: actually if I click the subs twice the hotkeys work again. I normally just click out of the pop up window to close it (and when I do that, I need to click the subs twice so the hotkeys work again). I suppose, then, that the browser is somehow thinking I'm doing something related to Yomitan after a single click to close the window so the hotkey to toggle subtitle visibility does not work, is that right?

**Comment by killergerbah** [comment]
Yeah seems like an issue possibly related to Yomichan's popup in its own iframe.

**Comment by killergerbah** [comment]
I would file an issue with Yomitan for this. It seems like if Yomitan just defocused the popup when this problem would improve.
