### ISSUE TITLE
Option to disable subtitle splitting

### ISSUE THREAD

**Issue by YoriJaski** [killergerbah/asbplayer#392]
Please add an option to disable subtitle splitting. Most sentences split, and changing the font size does nothing. This often ends up with incomplete sentences on anki in the sentence field if mining with an external program or extension such as yomitan or yomichan.

Mining using asbplayer keeps the sentence intact, although more inconvenient than having an option to avoid subtitle splitting.

**Comment by killergerbah** [comment]
I think I understand what you mean by subtitles "splitting" (a single sentence being split across two subtitles) but what does that have to do with font size?

To be clear, asbplayer doesn't do anything special to subtitle timing - the subtitles appearing split is a consequence of the subtitle file itself. However, some work could be done to try to intelligently guess when adjacent subtitles comprise a single sentence.

**Comment by YoriJaski** [comment]
You're right, It's actually just the subtitle file, asbplayer isn't doing anything to split them. To explain the font size, I thought maybe lowering it would stop it from splitting due to the font being smaller in its container. My bad

**Comment by killergerbah** [comment]
As a workaround for now I would suggest using the side panel to mine multiple lines at once. Clicking dragging and holding will mine multiple subtitles.

**Comment by killergerbah** [comment]
I've made a separate issue for asbplayer to intelligently detect sentences split across subtitles: https://github.com/killergerbah/asbplayer/issues/396
