### ISSUE TITLE
time-stamps in netflix work WRONG

### ISSUE THREAD

**Issue by thiagocasti** [killergerbah/asbplayer#399]
I already commented this but the issue is still going on, when i try to mine a certain subtitle on netflix the extension dosent mine the current subtitle but the one that is before, is so frustating i even tried to film a video but i couldnt even do it because when i click one subtitle time-stamp it automatically goes even three times back lol. This happens on every device i ever used asb player and on every web browser

**Comment by killergerbah** [comment]
@thiagocasti Does seeking through subtitles with left/right keys work correctly for you on Netflix?

**Comment by thiagocasti** [comment]
Ok so, i came up with solution lol, the function of seeking trough subtitles with left/right keys, mining a sentence, clicking on a subtitle etc. doesn't work so good only on netflix for some reason  but i found out that if i install language reactor, this extension  changes something about the netflix reproducer and now asbplayer works way better without loosing track of subtitles, i made two videos the first one is with language reactor installed and the other one is without.  

Sorry for the quality of the videos, i tried my best to show how it worked on each one, the one in language reactor when i clicked the subtitle it automatically pauses netflix reproducer (sometimes) and then goes to the subtitle position witch surprised me because even though i got the extension off it works way better lol, the only time it didn't went to my desired position on the video was because i made a false click lol.

Then in the second one just asbplayer, it works way different from, the netflix reproducer never pauses  and when you click on a subtitle the reproducer may not be running but the subtitle are already being played, so i think every time you click and change from different timestamps the delay goes worst and worst.

idk if this helped, again, sorry for the bad quality of the videos, i would keep using asbplayer this way because i just love it and is the only thing i have to mine from my dorama's and anime's in linux lol. 
https://github.com/killergerbah/asbplayer/assets/130512347/d788cabf-e0fe-456c-9df8-5f4c3cc87e4c


https://github.com/killergerbah/asbplayer/assets/130512347/fb5b4168-18a2-4a21-bb68-aacce3d81c67

**Comment by thiagocasti** [comment]
ok, idk i couldn't upload the two videos this is the one with language reactor:
https://github.com/killergerbah/asbplayer/assets/130512347/fdccdbd5-6aa8-490a-ba4a-28565fd1b942

**Comment by thiagocasti** [comment]
https://github.com/killergerbah/asbplayer/assets/130512347/9b00b73f-234e-4273-aed4-66bc4899feb9

**Comment by thiagocasti** [comment]
https://github.com/killergerbah/asbplayer/assets/130512347/54179c94-78a8-4ff9-982f-4527766f9591

**Comment by thiagocasti** [comment]
idk what happened with the video that has language reactor, tell me if you can reproduce it lol

**Comment by thiagocasti** [comment]
https://github.com/killergerbah/asbplayer/assets/130512347/cb875673-9dca-4830-99e5-dd1b767eeef1

**Comment by thiagocasti** [comment]
It seems that language reactor does add "better playback controls" wich could contribute in asbplayer working better on netflix
![image](https://github.com/killergerbah/asbplayer/assets/130512347/93d18b02-bb86-48e8-96ee-3996dd98e96f)

**Comment by killergerbah** [comment]
Thanks for the info it looks like language reactor has a way to force Netflix's player to seek precisely

**Comment by killergerbah** [comment]
For some reason (possibly CPU core count) Netflix does not allow precise seeking on some devices by default.  A speculative fix for this is implemented (see Discord server for snapshot release).
