### ISSUE TITLE
Changing Audio Tracks

### ISSUE THREAD

**Issue by CroakingToadElf** [killergerbah/asbplayer#401]
I cannot find a way to change audio tracks. I have many Dual Audio files and many have the english track as default. Even changing the default track with MKV tools doesn't change them in the ASBPlayer.

Please add a feature to change the audio tracks. It is extremely frustrating.

Anyways, thank you for your amazing work, your player is a godsend.

**Comment by Mapik0** [comment]
**Audio track selection for mkv files**
An audio track selector will appear for mkv files if experimental web platform features are enabled from `chrome://flags`. Note that enabling this flag may cause issues with other features of asbplayer, such as card creation through the Chrome extension.

Source:
https://github.com/killergerbah/asbplayer?tab=readme-ov-file#audio-track-selection-for-mkv-files
