### ISSUE TITLE
asbplayer not detecting subtitles

### ISSUE THREAD

**Issue by TheStatMann** [killergerbah/asbplayer#403]
While having asbplayer and Netflix both open in separate windows, the former does not load the subtitles. It displays "no subtitles" on a blank interface screen. About two days ago, this was not an issue. I could normally download the subtitles, then drag and drop them into the Netflix window which, they then would populate on their own in the asbplayer window right after. 

Now, when I do this, the asbplayer window seems to flash as if trying to respond to the subtitles but they do not populate in the asbplayer window. Usually, the top left of the asbplayer window that normally displays "asbplayer" on the right side of a little file emblem disappears and shows a string of numbers (or sometimes the name of whatever I'm watching in the Netflix window). 

I have tried reloading both tabs, checking my settings for streaming videos, and have deleted then reinstalled the extension, but nothing is changing. I have also updated Google Chrome, but that did not help. Any advice would be greatly appreciated.

**Comment by killergerbah** [comment]
@TheStatMann Can you upload subtitles where you are seeing this? And also the name of a video?

**Comment by TheStatMann** [comment]
The name of the video is "贄姫と獣の王　エピソード6:　 少年の魔族の王". 

This is the subtitle file I converted to text to submit here. Please let me know if I can include anything else or if I should change the way I listed the episode or sent these subtitles. 

[81685204_ja (7).txt](https://github.com/killergerbah/asbplayer/files/14864380/81685204_ja.7.txt)

**Comment by killergerbah** [comment]
@TheStatMann It appears that the file you provided is not a valid SRT file. Instead of actually lines, the escape sequence `\n` is being used in the file. You will find that other programs are not able to parse the file correctly.

On Netflix,  I would instead suggest that you use the subtitles autodetected by asbplayer instead. When watching a video, press `Ctrl + Shift + F` or open the side panel and click "Load Subtitles"

**Comment by TheStatMann** [comment]
Thank you for the reply! I didn't think of this, but it makes sense. 
Thank you for your time and help!
