### ISSUE TITLE
When mining using Yomitan and Update Last Card mining button, '''class="term">''' randomly shows up on the sentence field

### ISSUE THREAD

**Issue by jifufu** [killergerbah/asbplayer#404]
![image](https://github.com/killergerbah/asbplayer/assets/166309022/7681c954-3803-4d55-bb29-6536c7707b06)
![image](https://github.com/killergerbah/asbplayer/assets/166309022/bf35c87f-5480-4bc2-b08f-097be0570594)

No text is missing, just the extra addition of `class="term">` which is not supposed to be there.

**Comment by killergerbah** [comment]
Are you using any Yomitan settings that might apply a css class called term? Just curious in case it helps with me reproducing the issue.

**Comment by jifufu** [comment]
I'm not using any custom css and I'm not sure about the default css used, but yomitan does seem to use "term" to mean words selected for its popup feature.

**Comment by killergerbah** [comment]
Speculative fix is in 1.2.0 
Will not be doing more work on this unless @jifufu reports that its still broken
