### ISSUE TITLE
Add option to disable changing the subtitle position offset with scroll wheel

### ISSUE THREAD

**Issue by unectomy** [killergerbah/asbplayer#407]
**Is your feature request related to a problem? Please describe.**
Sometimes, I accidentally use my scroll wheel when I'm scanning subtitles in the video player. This makes the subtitle box move around which is annoying because to I have to go into the settings menu and set the "Subtitle position offset from bottom" option back to where I want it.

**Describe the solution you'd like**
I'd like there to be an option to disable changing the subtitle position offset with the scroll wheel. This option could be a toggle in the MISC section of the settings page.

**Comment by killergerbah** [comment]
This has been addressed by removing the scroll wheel bind entirely.
I did not add a setting for this since there is a way to modify position offset via the subtitle display settings and it seems unlikely that a wheel bind would be preferred over this.
