### ISSUE TITLE
firefox support

### ISSUE THREAD

**Issue by JunkyardCat** [killergerbah/asbplayer#409]
will you guys be including firefox in release

does asbplayer store the subtitle in cache or under its own solder?

does asbplayer still support yomichan or do i need yomitan now?

**Comment by killergerbah** [comment]
1. Firefox support will be released soon (weeks or days).
2.asbplayer does not store subtitles anywhere. To use asbplayer you need to load subtitles every single time, either from a file or from an auto-detected source (like on YouTube or Netflix).
3. Yomichan and Yomitan are entirely separate extensions from asbplayer. Yomitan is the successor to Yomichan so if you want the version of the extension that is actively being developed use Yomitan.
