### ISSUE TITLE
Disabling Sub Track should disable Mining from that track

### ISSUE THREAD

**Issue by bpwhelan** [killergerbah/asbplayer#410]
**Is your feature request related to a problem? Please describe.**
It's nice to have asbplayer setup with multiple subtitles (target language + native language) with native language disabled, so I can mine subtitles like usual, but open up the native translation in case i'm stuck on the meaning of a sentence.

The problem is when mining the target language, the native language is also often included in the mined sentence.

**Describe the solution you'd like**
Do not include disabled subtitles in Anki Exports, or have a config to disable this behavior.

**Describe alternatives you've considered**
Disabling Native Language subtitles. As of right now the workflow I was trying is not really possible since I have to go through and erase all the English from all the flashcards I mine while watching.

**Additional context**
I did a few searches in issues, but couldn't find anything. I feel like this would be a pretty popular workflow to increase the casual enjoyment factor of sentence mining.

![image](https://github.com/killergerbah/asbplayer/assets/8314499/e19177f2-f1f6-4d19-98ef-6fcd59c0b00e)

![image](https://github.com/killergerbah/asbplayer/assets/8314499/a28d742b-1ddd-4b42-b436-8abcaa7fe5b5)

**Comment by artjomsR** [comment]
I think this should be solved by https://github.com/killergerbah/asbplayer/issues/306 when subtitle tracks will be written to separate Anki fields, then you should be able to hide the respective field with the English subtitles

**Comment by bpwhelan** [comment]
@killergerbah this looks to be working nicely with the new version thanks to https://github.com/killergerbah/asbplayer/commit/6ddaec14b589b92ce102ac198f3515af4e2ede2e

Closing this.
