### ISSUE TITLE
Navigate by clicking an entry in the mining history 

### ISSUE THREAD

**Issue by naiza-asaad** [killergerbah/asbplayer#412]
**Is your feature request related to a problem? Please describe.**
Is it possible to navigate to a part of the video by clicking an entry in the mining history of the sidepanel? Similar to how it's done by clicking a subtitle entry in the sidepanel.

**Describe the solution you'd like**
The [linked article](https://soyuz18.notion.site/Sentence-mining-from-Netflix-and-YouTube-with-asbplayer-83a03590cd8349ba81ca10340645b565#c94df434c5c248a5bd3c79f2131afd4c) in the README that describes how to do asynchronous mining involves manually filling out some fields (definition, word, etc) by copying from Yomitan. If it would be possible to navigate by clicking a sentence saved in the mining history, we could go through each saved sentence and:
- go back to that point in the video
- hover over the word and add to Yomitan
- click "Export to Anki" from the mining history
- update the last card with the audio and image

I'm not sure what's the fastest way to create cards from the saved sentences after watching a video right now. Maybe there's an existing workflow that I'm not familiar with?

**Comment by killergerbah** [comment]
If all you need is a Yomitan-scannable sentence on your screen then you can just do that from the 'Anki Export' dialog itself. From the mining history, click on 'Export to Anki' for the sentence. Then scan the sentence from the popup itself with Yomitan, add it to Anki with the + button, and click 'update last card' from the dialog.

**Comment by naiza-asaad** [comment]
Ahh I didn't know I could scan from there. That's exactly what I needed, thank you!
