### ISSUE TITLE
some function stop working after loading my sub

### ISSUE THREAD

**Issue by JunkyardCat** [killergerbah/asbplayer#417]
im using 1.2.0 on firefox and watching it on a site that has name a name "wave" in it (not sure if its not allowed to say the name). so when i load the subtitle some parts stopped working. 
1. shift+p to auto pause doesnt work
2. nothing happens when i click the fullscreen button or the cog wheel button (the one that changes the quality and other things on the anime) 
Note: number 2 only happens if i press shift+P to activate auto pause but doesnt really activate because see problem 1

**Comment by killergerbah** [comment]
@JunkyardCat are you experiencing problems like this on any other site?

**Comment by JunkyardCat** [comment]
@killergerbah 
its ok now i think some of my extension was interfering with it.
btw kinda off topic but do you know of any way to show the kanji and its meaning on the side pinal (or some other way to display) without having to hover over the word on the  subtitle each time?

**Comment by killergerbah** [comment]
If you're referring to using Yomitan on the side panel then no that's not possible because extensions can't inject themselves into another extension page.
Adding a built-in dictionary to asbplayer is in my TODO list but will not be coming soon.
