### ISSUE TITLE
ASB stops playing after updating a card 

### ISSUE THREAD

**Issue by FuuSpirit** [killergerbah/asbplayer#422]
Every time I update mined card video stops playing. It happens when I use the side panel and when I use the overlay as well. Is there a way to turn this auto-pause off? 

It used to work without pauses before updating to the latest version.

**Comment by killergerbah** [comment]
asbplayer will restore the playback state of the video prior to mining the card. So a workaround for now would be to not pause when using the mining action. There is a [PR](https://github.com/killergerbah/asbplayer/pull/415) in progress to add a setting to control this behavior.

**Comment by FuuSpirit** [comment]
Ah, I see! Thank you very much, this helped. Will be waiting for future updates, really appreciate your work and effort with this program 💪
