### ISSUE TITLE
Adding language profile

### ISSUE THREAD

**Issue by cristian428** [killergerbah/asbplayer#424]
I use yomitan and your extension to learn Japanese and Chinese. Most times I forget my asbplayer extension Anki settings are setup for one of the 2 languages I study. I find that to switch I need to press at least 2 buttons to get it setup right (selecting deck and then note type). I think having a kind of setting profile would be nice to easily switch between 2 or more language study goals or even just card type goals(different Anki fields etc). 

Since yomitan now supports multiple languages and has a setting for it like here
![Screenshot_20240515_004559_Kiwi Browser](https://github.com/killergerbah/asbplayer/assets/36088384/3cf740d0-108c-4b7e-9f61-d20b6e8873bf)
![Screenshot_20240515_004612_Kiwi Browser](https://github.com/killergerbah/asbplayer/assets/36088384/fe500deb-56b2-45cc-b42f-408b9484604c)

Do you think it'd be possible to have the extension find what language is chosen on a given profile (since profile names can vary) and therefore automatically switch to an asbplayer profile name, that matches the language being studied ?! 

That way for yomitan users, we just have to be on the desired yomitan profile and the player could have the language anki settings too. 

EDIT: Or rather simply just change profile based on the subtitles language!

 I just thought of this idea but don't know anything about the difficulty of implementing this so I apologize if the idea is crazy. At the very least I think profiles in asbplayer Anki section or ones that affect the whole of asbplayer settings would be beneficial to many. 

Really appreciate this extension and all the work put into it. This is one of my favorites. Thank you !

**Comment by killergerbah** [comment]
No plans to do any specific integrations with Yomitan but a way to quickly change anki settings can be considered as part of the anki settings revamp for 1.3.0

**Comment by cristian428** [comment]
If you do decide to add a sort of profile feature I'd like to suggest subtitle settings or at the very least font settings be included in that feature because if one is switching profiles for the sake of another language, especially for languages that use kanji/hanzi glyphs, the font used could be important. Chinese has simplified and traditional character scripts and I use different fonts for Chinese and Japanese for example. It's just a thought I had because I have to switch the font every time too. Thank you for considering it, really appreciate your app

**Comment by killergerbah** [comment]
Settings profiles have been added. Automatically choosing a profile based on some criteria will be a backlog task.
