### ISSUE TITLE
"github pages" time out issue

### ISSUE THREAD

**Issue by DPowrie** [killergerbah/asbplayer#429]
I've been using Asb for a couple months now with zero issues, so much that I sent in a small donation but just today my connection to asb player repeatedly ends in an "ERR_CONNECTION_TIMED_OUT" message. This isn't happening with any other website on my PC. I've also checked on my phone and I'm having the same issue so I'm inclined to say it's probably on my side.

I've looked around on the general "github pages" host or whatever you would call it and I can't even open that site up which I find strange

Anyone else come across this issue? Sorry if it's fairly vague but it would be greatly appreciated if anyone had any advice

**Comment by DPowrie** [comment]
Hey just as an update, apparently it's an issue on githubs side and they are looking to solve the issue, I'll link the page in which this is discussed: https://github.com/orgs/community/discussions/127077

**Comment by killergerbah** [comment]
Nice work reporting the issue
