### ISSUE TITLE
Condensed Option to skip music and closed captions

### ISSUE THREAD

**Issue by CroakingToadElf** [killergerbah/asbplayer#431]
Hey, 

thanks a lot for your hard work, this is easily the best tool for learning Japanese and I am very grateful!

I have the following request:

Could you add an option to the "condensed" mode that skips closed captions (anything in parentheses) and music.
Something like this:

  "filtered_characters": "♩♪♫♬～〜",
  "filter_parentheses": true,
  
  I took this from the config.json of a tool called "Condenser": https://github.com/ercanserteli/condenser

Thank again and have a wonderful day.

**Comment by killergerbah** [comment]
@CroakingToadElf This can already be achieved using the subtitle filter regex settings. If those subtitles are filtered out, asbplayer will skip them automatically in condensed mode. See https://github.com/killergerbah/asbplayer?tab=readme-ov-file#filtering-subtitle-text
