### ISSUE TITLE
Asbplayer won't send audio and text to anki on Brave Browser 

### ISSUE THREAD

**Issue by Loongoon** [killergerbah/asbplayer#436]
Good evening,

I recently switched to brave browser as my main browser of choice and asbplayer doesn't want to send the audio or text to anki now. I went and tested if it would work on Chrome still, but that browser also seems to be having the same issue. I've verified that the anki connect URL is functional. I saw the recommendation to open the developer console to see if there were any errors and issues and the following is what appeared after I tried to mine a subtitle. If you could help with this issue I'd greatly appreciate it.

**Error messages**
![Screenshot 2024-06-13 133437](https://github.com/killergerbah/asbplayer/assets/161155212/2fcc74b3-5e72-4afb-b5c5-e689e1afcb4c)
![Screenshot 2024-06-13 133446](https://github.com/killergerbah/asbplayer/assets/161155212/8d9d216e-a0d0-4b46-9447-36b4a1fbbdd3)

**Comment by killergerbah** [comment]
If you're using Brave make sure that asbplayer isn't being blocked by Shield

**Comment by Loongoon** [comment]
Here the settings for my shield. I'm not sure which of the following would be blocking asbplayer. 

![image](https://github.com/killergerbah/asbplayer/assets/161155212/fa67908d-b7dd-4bdc-9c8c-b01c0f6b00e6)
![image](https://github.com/killergerbah/asbplayer/assets/161155212/a04457df-4c2e-4483-87b7-407bb70ccb45)

**Comment by Loongoon** [comment]
Turns out I'm just stupid. Thank you for your time and help.
