### ISSUE TITLE
Set delay for capture of automatic screenshot

### ISSUE THREAD

**Issue by keineahnungking** [killergerbah/asbplayer#437]
I have the problem that the automatic screenshot is always way too late. Is it possible to change the timing?

**Comment by killergerbah** [comment]
Yes check the mining section of the settings. There is a delay setting.

**Comment by keineahnungking** [comment]
I already set the setting "Screenshot capture delay" in the Streaming Video section to 0 but it is still delayed by several seconds. I only have this issue in on Android. I don't see any setting in the Mining section that affects screenshot delay, what is it called?

**Comment by killergerbah** [comment]
The one you changed is the right one. But is it happening for local or streaming video?

**Comment by keineahnungking** [comment]
Local video

**Comment by killergerbah** [comment]
For local videos the screenshot taken will be the frame on the screen at the time of mining. So you will have to manually adjust accordingly.

**Comment by anantasuryakurniawan** [comment]
Hi, I also have this problem, but unlike what you said, the screen at the time of mining and the resulted image imported to Anki is still delayed for a few second. Is there a way to get around this?
