### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by killergerbah** [killergerbah/asbplayer#44]

**Comment by MatiasIslaA** [comment]
Like language localization?

**Comment by killergerbah** [comment]
> Like language localisation?

@MatiasIslaA Yep

**Comment by MatiasIslaA** [comment]
@killergerbah I could do the Spanish one but I would need some guidance on how to set up the files. Is there any way I could contact you over Discord?

**Comment by killergerbah** [comment]
@MatiasIslaA Sure I am killergerbah#4325 on Discord. But I haven't researched how to implement the localization yet so I don't think I can be helpful right now. (I will plan to do it soon).

**Comment by killergerbah** [comment]
@MatiasIslaA I know it's been a very long time but I finally got around to working on this. If you would still like to provide a Spanish localization I would love to have your help.
