### ISSUE TITLE
copy-to-clipboard often stops working after a few lines

### ISSUE THREAD

**Issue by rtr46** [killergerbah/asbplayer#446]
When i load a sub via asbplayer, the copy-to-clipboard functions often stops copying lines.

I have the issue with:
windows 10
chrome 126.0.6478.63
asbplayer 1.2.0 (via chrome web store)

Sometimes it just skips 1-2 lines
Sometimes it just seems to stop copying new lines completely (tested for around 10 lines or so)
When i manually search to the next or last subtitle it often works again for 2-3 lines and then stops again

**Comment by killergerbah** [comment]
@rtr46 This could happen if the tab is backgrounded (not in focus).

**Comment by rtr46** [comment]
@killergerbah i tried it, but it didn't help :(

Here is the video (i hope it's ok to post links, otherwise just feel free to delete it or tell me to do delete):
https://hianime.to/watch/konosuba-gods-blessing-on-this-wonderful-world-3-19108?ep=125147

Here is the srt:
https://jimaku.cc/entry/2835/download/Subarashii%20Sekai%20ni%20Shukufuku%20o%EF%BC%81%203%20-%2010%20%E3%80%8C%E3%81%93%E3%81%AE%E8%BA%AB%E5%8B%9D%E6%89%8B%E3%81%AA%E8%8A%B1%E5%AB%81%E3%81%AB%E7%A5%9D%E7%A6%8F%E3%82%92%EF%BC%81%E3%80%8D%20(AT-X%201280x720%20x264%20AAC).srt

I open the video, drag-and-drop the subtitle, it starts showing and the first couple of lines are copied to clipboard, but then after a few lines the subs still are displayed correctly, but the clipboard doesn't get updated. The video tab is in foreground and focused. I tried it with 3 different clipboard grabber, to make sure they don't do anything weird, causing the issue. I tried fullscreen video and normal video with no difference in result.

**Comment by killergerbah** [comment]
I believe under certain conditions you need to give explicit permission to the website to automatically copy text to clipboard. So you might have failed to give permissions in the past. For example, after a few seconds on the website I get an in-browser popup like in the screenshot to give clipboard permissions to the website:

<img width="366" alt="image" src="https://github.com/killergerbah/asbplayer/assets/2254858/9a756390-bada-462c-b2c7-5b3fb0a4193e">

You can reset any existing permission settings from Chrome settings. Search for something like 'permissions' and you should find it under "site settings."

**Comment by rtr46** [comment]
Indeed. I didn't get a popup tough. I can only see a clipboard simple in my url bar:
![image](https://github.com/killergerbah/asbplayer/assets/171138461/cf6e4bc7-6bd3-4336-a5a1-d206934f05d6)

Once i click the icon, i can grant permission and then it works... which is curious, since when i seek to the next subtitle manually, it works even without the permission for a couple of lines.

Either way... for me the problem has been solved. Thanks for the support!

**Comment by killergerbah** [comment]
Right, it's odd that it works at all without giving permission first. I suspect it has to do with some timing w.r.t. the tab coming into focus / user gesture. Anyway, glad it's working now. This is a great candidate for the FAQ.
