### ISSUE TITLE
Subtitle per track separation preview misleading when performing Export

### ISSUE THREAD

**Issue by artjomsR** [killergerbah/asbplayer#450]
I've assigned different Anki fields to different subtitle tracks. These settings are applied when updating the last card. However, when I'm trying to Export a new card, both tracks appear under the Sentence field, and the 2nd track field is empty.

This seems to be mainly a visual glitch, as when the card is exported, the tracks are assigned correctly

https://github.com/killergerbah/asbplayer/assets/6875790/9e8ec060-8fed-4f7a-a969-b00f9b18bbcf

Tested on commit f14bd91fa85f1fb65cae6bda604613b0e7ae82fd

**Comment by artjomsR** [comment]
Ah I see, I've missed the 3 dots in the UI. But that's only part of the problem - in my video you can see Sentence Translation is mapped in Anki, but that field appears blank on the Export window popup

**Comment by killergerbah** [comment]
Sorry, I'm not seeing how that is not the same problem as the fields being hidden. For what it's worth, any of the default fields with special behavior (like sentence, word, track 1, track 2, etc) will always be populated as long as they are showing in the dialog. But they might not actually be used in the actual anki card.

**Comment by artjomsR** [comment]
Yes you’re right, I’ve hidden the default fields so it’s no longer confusing. Thank you so much!
