### ISSUE TITLE
Blur shortcuts improvements

### ISSUE THREAD

**Issue by artjomsR** [killergerbah/asbplayer#451]
**Is your feature request related to a problem? Please describe.**
With the current implementation, `toggleAsbplayerBlurTrack` blur shortcuts persistently enable / disable the blur. This requires 2 key presses to unblur and then blur the subtitle, which is equivalent to using a shortcut to hide & then display the subtitle

**To distinguish the shortcuts, I suggest one of the following:**
- The `toggleAsbplayerBlurTrack` shortcut unblurs the subtitle but doesn't persist the blur setting. As soon as the subtitle changes, the track becomes blurred again (I think this option is easier and more intuitive. This is also how Language Reactor does this. I'm not aware of other players that provide subtitle blur) 
- `toggleAsbplayerBlurTrack` shortcut unblurs the subtitle as long as the subtitle is held. The subtitle is blurred again after the key is released

tagging @nekorushi in case you're interested in this discussion :)

**Comment by nekorushi** [comment]
That's a cool improvement. I am not sure if that should be a separate set of shortcuts or should it replace the current ones (although i feel that your idea would be utilised more often, so it could replace current ones).
Personally I won't be able to look into it myself due to personal responsibilities, but definitely +1 from me.

**Comment by killergerbah** [comment]
In this scenario, would the settings toggle specify the initial blur state when subtitles load? And the shortcuts only control the blur state during playback?

**Comment by artjomsR** [comment]
Yes, exactly. 

If track blur is **off** in the settings:
blur is permanently off for that track and mouse hover / blur shortcut doesn't change the subtitle appearance

If track blur is **on** in the settings:
- shortcut removes blur for the respective track, but blur is reintroduced when subtitles change
- mouse hover works as is, no changes (unblurs on hover, resumes blur when cursor leaves the sub track)

**Comment by artjomsR** [comment]
>  I am not sure if that should be a separate set of shortcuts or should it replace the current ones

I think it is fine to replace the existing set of shortcuts. Whoever will use the blur subtitles will be using them regularly as part of their workflow, and I'm not expecting them to use the shortcuts to change the type of the flow that they use

In other words, if they're using blur, I'm expecting them to continue using the blur and not use the shortcuts to periodically toggle that setting on and off

**Comment by killergerbah** [comment]
I see, makes sense. I agree this would be better.

**Comment by artjomsR** [comment]
Ok I'll take a look at this then

**Comment by artjomsR** [comment]
I've created the PR but it's slow to respond to keypresses and not sure what's the best way to tackle that. Feel free to update the PR! :)

**Comment by killergerbah** [comment]
Thanks again @artjomsR
