### ISSUE TITLE
Not all Netflix subtitles shown in subtitles menu + 1st subtitle option in menu is forcefully changed

### ISSUE THREAD

**Issue by shiki-tm** [killergerbah/asbplayer#452]
I can't select all subs that are on netflix, but the specific number and names matching the subs that are above this horizontal divider makes me think it's the extension unable to read those subs underneath that line.

![msedge_PjMWz64FRi](https://github.com/killergerbah/asbplayer/assets/36088384/3a452ddd-8f6b-49e4-9f78-2a1185388f81)
![msedge_BnbEBimMRg](https://github.com/killergerbah/asbplayer/assets/36088384/71b799bc-1b22-4139-9143-90a01c2078e7)

It seems like theres nothing special about that section dividing line, its just that the most popular languages are at the top and then under the line is everything else. Definitely not a problem in Youtube, and I don't really use other popular streaming platforms.

PART 2 - another bug

So when I tried getting my TL subtitles that were at the very bottom of the netflix subs list, i selected them from the netflix menu to see if they really show and they did, after that I refreshed my page and then they appeared as an option in the extension subs menu at the top of the list, replacing whatever is usually at the top. This can happen with any language selected, as long as its from underneath that horizontal line. Happens regardless of what is selected in the extension subs menu

![msedge_qLUd0pYcmG](https://github.com/killergerbah/asbplayer/assets/36088384/25a43b35-2833-411d-8532-48044f83e061)
![msedge_USQtHRMgnH](https://github.com/killergerbah/asbplayer/assets/36088384/e1fd46bf-cff1-4c78-bd71-8c06c9e4c224)

I'm pretty sure this isn't intended behavior, and maybe it's related to the first issue?
I'm using Microsoft Edge browser on the latest version and latest version of asbplayer. Tested another movie with lots of subtitles and the same issues are present.

**Comment by killergerbah** [comment]
This seems to be a result of specific Netflix behavior such that subtitle file URLs are provided for only a specific set of languages (in this case, the ones above the horizontal line). In order to request subtitles for the other languages, Netflix itself seems to implement a protocol that is not straightforward to reverse-engineer, let alone re-use to request subtitle file URLs ALL available languages, so I am inclined to defer this issue for now.

**Comment by killergerbah** [comment]
I believe I've found an approach using Netflix's high-level JS player API.
URLs for any language can be requested on demand by using the `setTimedTextTrack`. An object with `timedtexttracks` is then immediately received with the URLs.

This would require asbplayer to support URLs being requested from the page script on-demand for a specific language code, which is not currently supported now.
