### ISSUE TITLE
Yomitan not picking up the full sentence with a normal "add". Related to: {cloze-prefix} {cloze-suffix}

### ISSUE THREAD

**Issue by Viterkim** [killergerbah/asbplayer#459]
I like having a setup in yomitan with (anki connect)
```
{cloze-prefix} ({cloze-body}) {cloze-suffix}
```
when i mine stuff i have the full sentence and the word in `()`.
However with asbplayer, when there's "2 lines of subtitles" only the line with the actual word in will get mined, this means that the audio will have the full sentence but the sentence is only "half".

Using the asbplayer anki settings doesn't help as i like modifying the content and not just pop in the entire sentence.

Would it be possible to make both sentence lines the same HTML part or something like that? Or is there a way i can make yomitan pickup both sentences?

Thanks!

edit: this used to work fine in https://github.com/animebook/animebook.github.io :D
also would it be possible to disable double click to full screen, or click to play/pause?

edit 2:
disabling double click can be done with a simple violent monkey / tamper monkey script:
```
// ==UserScript==
// @name        Disable oduble click for fullscreen for killergerbah.github.io
// @namespace   Violentmonkey Scripts
// @match       https://killergerbah.github.io/asbplayer/*
// @grant       none
// @version     8.5
// @author      Good old chat gippity
// @description 7/6/2024, 1:33:00 PM
// ==/UserScript==

(function() {
    'use strict';

    document.addEventListener('dblclick', function(event) {
        if (event.target.tagName.toLowerCase() === 'video') {
            event.stopPropagation();
        }
    }, true);
})();
```

**Comment by killergerbah** [comment]
@Viterkim If you 
1. Configure both Yomitan and asbplayer to supply the sentence.
2. And use the "create card with Yomitan, then update with asbplayer" flow.

Then, the asbplayer-supplied sentence should override the Yomitan one, BUT also inherit any HTML markup in the Yomitan sentence. If that's not what is happening then there might be a bug.

**Comment by Viterkim** [comment]
Here's a subtitle file 
[Non Non Biyori-S3 E12-Episode 12_ja.zip](https://github.com/user-attachments/files/16314964/Non.Non.Biyori-S3.E12-Episode.12_ja.zip)

**Comment by killergerbah** [comment]
@Viterkim Got it, I think I understand the problem a bit better now. Yomitan picks up the entire sentence on animebook, I believe due to a combination of how animebook renders the subtitle and how Yomitan detects boundaries between sentences. I can suggest two possible workarounds:

- Instead of using () to highlight your word, use HTML i.e. <b>{close-bodyy}</b> instead. asbplayer already knows how to inherit HTML.
- Mess with Yomitan sentence boundary settings and see if you can get it to pick up the entire sentence on asbplayer. I _think_ if you remove `\n` as a possible sentence separating character then you might have some success.

Unfortunately I am hesitant to make any subtitle rendering changes just to fix this issue so it would be great if one of the options above work for you.

**Comment by Viterkim** [comment]
![image](https://github.com/user-attachments/assets/2ae4bb4b-9662-44c6-a61f-9127cac8341b)
![image](https://github.com/user-attachments/assets/fc68a8ec-aa27-4dc1-8995-454ec8924ba0)

There's no `\n` line terminator when parsing sentences.

I'm not really sure how doing anything with {cloze-body} would help? My card format are vocab cards, with the sentence on the back where i have the `()` for convenience, for glancing at the word location. 

asbplayer:
![image](https://github.com/user-attachments/assets/f0135338-043f-484a-a881-de9aaf25a9cd)
i can see that there's just a newline in the content

animebook:
![image](https://github.com/user-attachments/assets/32a2391d-e647-4a48-9e7c-4fca02d5041f)
Here there's the <p> tags?

Maybe this helps?

Also appreciate you spending your time on answering!

**Comment by killergerbah** [comment]
> I'm not really sure how doing anything with {cloze-body} would help? My card format are vocab cards, with the sentence on the back where i have the () for convenience, for glancing at the word location.

What I mean is to highlight `{cloze-body}` using HTML formatting instead of parentheses. So something like `<b>{cloze-body}</b>` would do it, but you would be highlighting the word in bold instead of using parentheses.

If you do this then asbplayer will properly retain the highlighting when it updates the sentence.

**Comment by Viterkim** [comment]
like this?
![image](https://github.com/user-attachments/assets/b93d94b9-6709-4327-8743-d8f750ef80cd)

![image](https://github.com/user-attachments/assets/8145e5f8-16cf-4859-94be-61560b3def5c)


![image](https://github.com/user-attachments/assets/78199069-4bfc-4243-827c-21f5ec24ec42)


no doesn't work

**Comment by Viterkim** [comment]
Okay it seems to work with the
![image](https://github.com/user-attachments/assets/bbb3fba4-636c-4b63-9adb-6830fd3946fa)
and not the subtitle track 1 field (didn't see the top one).
But man i just don't like the bold stuff :D

**Comment by killergerbah** [comment]
l see, the HTML markup being retained for the individual subtitle tracks should probably be considered a bug.

About the bolding, you could still use HTML to get parentheses instead if you use the solution in this StackOverflow post: https://stackoverflow.com/questions/60178429/add-parentheses-before-and-after-paragraph-in-html-css

I would try something like this:

```
<span>{cloze-body}</span>
```

And then CSS in your Anki note type like this:

```
span::before {
  content: "("
}

span::after {
  content: ")"
}
```

**Comment by Viterkim** [comment]
It's actually a really good solution, and would also have something unique to wrap the word in! But it unfortunately doesn't work.
Before:
![image](https://github.com/user-attachments/assets/7e683821-d091-4c0b-9524-2c182a990662)
![image](https://github.com/user-attachments/assets/ace4e1f1-3469-477c-a597-8dfcc97c3472)


After:
![image](https://github.com/user-attachments/assets/87b8ddb6-c57d-47ee-97a6-5b01eda3ca39)

**Comment by killergerbah** [comment]
Hmm not sure what to tell you - maybe it is not possible to achieve the parentheses with HTML.

For asbplayer, I am reluctant to make changes to support this very specific use case, and you might have better luck submitting an issue to Yomitan regarding its sentence boundary detection when it comes to text separated by newlines.
