### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by killergerbah** [killergerbah/asbplayer#46]
The app layout is dysfunctional on mobile and some features don't work.

**Comment by Staz0r** [comment]
Is it possible to even drag and drop subtitle to websites?

**Comment by killergerbah** [comment]
> Is it possible to even drag and drop subtitle to websites on mobile?

@Staz0r 
As far as the extension goes, I actually have  no idea if any part of it works on mobile. If syncing from the asbplayer site works already, that would be great. As you suggest, implementing a way to sync from a streaming video tab would take some work though, but it would just be a matter of exposing a button to open a file instead of using drag-and-drop.

**Comment by killergerbah** [comment]
Also - I just realized what you were asking. Drag-and-drop doesn't work on mobile, but with the current version of the site you can browse for files to open.

**Comment by Staz0r** [comment]
> Also - I just realized what you were asking. Drag-and-drop doesn't work on mobile, but with the current version of the site you can browse for files to open.

I didn't realize that browse for file support has been implemented, anyway thank you very mich!

**Comment by killergerbah** [comment]
There are better tools than asbplayer for mining things on mobile.

**Comment by T1CkShot** [comment]
> As far as the extension goes, I actually have no idea if any part of it works on mobile. If syncing from the asbplayer site works already, that would be great. As you suggest, implementing a way to sync from a streaming video tab would take some work though, but it would just be a matter of exposing a button to open a file instead of using drag-and-drop.

There is an app to emulate Anki Connect on android. I wonder if that can he of any help. Yomichan can add cards to Ankidroid using it same as PC.
Here is the repo https://github.com/KamWithK/AnkiconnectAndroid

**Comment by killergerbah** [comment]
@T1CkShot 
Thanks for the info; because those tools you mentioned exist asbplayer is actually someone close to working on mobile but currently it's not possible, one of the reasons being that audio recording not being possible on Kiwi browser for some reasons related to how extensions work on mobile and MV3 only supporting tab audio capture in a  very specific way.
