### ISSUE TITLE
Subtitles not appearing on Amazon Prime Video

### ISSUE THREAD

**Issue by cspotcode** [killergerbah/asbplayer#464]
Subtitles are not appearing on Amazon Prime Video.  I am able to load subtitles, and they appear in ASBPlayer's sidebar.  DevTools shows that ASBPlayer has successfully created all the subtitle <div>s.

As far as I can tell, this is a visual issue where the subtitles don't appear over the video.

Please let me know if there's anything I can do to help debug this issue.

**Comment by killergerbah** [comment]
From the DevTools can you find elements with class `asbplayer-subtitles` and see where they are on the page?
Can you try messing with the subtitle position offset setting?
Also, can you paste a link to the video here?

**Comment by killergerbah** [comment]
@cspotcode While I can't reproduce the issue you're describing, the symptoms of your problem suggest that subtitles are loaded on more than one video element (an empty track on one video element, and the actual subtitles on another). So I would suggest looking into whether there there is any way you might be accidentally loading tracks onto multiple video elements on the page.

**Comment by cspotcode** [comment]
Ok, that does ring a bell.  #50 talks about how Prime Video has multiple video elements on the page.  And I can see the page always has 2x `<video>` elements.

I am once again seeing the issue with subtitles not appearing over the video.  Here is the requested information about the `asbplayer-subtitles` elements in DOM, relative to the video element:
![image](https://github.com/user-attachments/assets/6ba7fdb8-8606-4cef-9e75-694dbfb1b978)

I also tried changing the offset value to 0, but that didn't help.  I think the subtitles are hidden behind the video element, for some reason.

---

### Another experiment

I tried loading the episode listing again, without playing a video: just looking at the list of episodes.  Already on this page, ASBPlayer appears to detect subtitles from two episodes, even though I haven't played anything.

![image](https://github.com/user-attachments/assets/7409cdd1-0bf3-4a4c-b297-7afbffa5b04d)

The first episode, "Regrets" is the one that Amazon says I'm halfway through, offers to let me resume where I left off.  So maybe that video element is being pre-loaded somehow.  "Breakdown" is the episode after that.

![image](https://github.com/user-attachments/assets/bb93d768-5a91-4462-a730-11d97953c3a6)
![image](https://github.com/user-attachments/assets/dd83ae20-27cf-40b2-83c0-a8f943a65d74)

Experimenting: I tried loading the subtitles for "Regrets", which appear in the sidebar.  Then I click to play a different episode, episode 1.  Still only 1 video element on the page, yet the sidebar is synced to the _middle_ of where I left off in "Regrets" despite the video playing at the _beginning_ of episode 1.
![image](https://github.com/user-attachments/assets/a22175a0-1aed-46bb-8f21-0152dd298b7d)

**Comment by cspotcode** [comment]
I think I figured it out!

The <video> is an overlay over top of a larger page which can be scrolled up and down.  For example, I had to scroll down to click on the last episode of a season.

The subtitles are being positioned relative to the top of the page, meaning they are off-screen, off the top of the screen.

I discovered this with `$('.asbplayer-subtitles-container-bottom').getBoundingClientRect()`

### To reproduce

1. Find an episode listing where you can scroll down a lot.
2. Click an episode to play it.
3. Load subtitles.
4. In DevTools, `$('.asbplayer-subtitles-container-bottom').getBoundingClientRect()` and see that the returned `DOMRect` has a negative `y` and `top` values.

**Comment by killergerbah** [comment]
Thanks, I'll try this when I get a chance

**Comment by killergerbah** [comment]
It looks like asbplayer isn't dealing with the scrolling correctly. Hopefully it is something obvious and I can have a fix for it.

**Comment by killergerbah** [comment]
I believe I have the fix. This will go into 1.4.0. In the mean time you will need to scroll up to the top of the screen for the subtitles to appear correctly.

**Comment by cspotcode** [comment]
Thanks!
