### ISSUE TITLE
Pause when looking up a word?

### ISSUE THREAD

**Issue by woobeewoop** [killergerbah/asbplayer#473]
I am used to Language reactor, and sometimes when I want to look up a word I forget to pause and then I lose the word I was looking up. 

If possible, I would like to have a setting that allows the stream to automatically pause when looking up a word with yomitan.

if not auto pause, it could automatically trigger the rewind feature that already exists, that way it replays the sentence the word is in until you are done hovering over the word.

**Comment by killergerbah** [comment]
Asbplayer is unlikely to implement integrations with specific dictionary extensions and so your problem is not likely to be solved as is.

I am planning to add a pause-on-hover feature for asbplayer which if implemented cleverly may be able to help with this problem.

**Comment by killergerbah** [comment]
This is now possible with pause-on-hover.

**Comment by woobeewoop** [comment]
woohoo!
