### ISSUE TITLE
Toggle subtitles keyboard shortcut no longer works after mining

### ISSUE THREAD

**Issue by zuckyyyy** [killergerbah/asbplayer#479]
I decided to start using the toggle subtitles shortcut and I noticed that after mining, you have to click the video player screen again in order for the keyboard shortcut to work. At the same time this happens, other shortcuts such as play/toggle still work.

**Comment by killergerbah** [comment]
@zuckyyyy Is this issue still happening? Is this happening with local video on the asbplayer website?

**Comment by zuckyyyy** [comment]
It stopped happening when the fullscreen issue came up. Was using the local player, both update last card and the export dialog

**Comment by killergerbah** [comment]
I haven't been able to reproduce this and it looks like it's not happening for @zuckyyyy anymore. Feel free to re-open if that's not true.
