### ISSUE TITLE
Subtitles randomly appear twice (or bleed over from the previous subtitle) when pressing replay on SOME subtitles, randomly.

### ISSUE THREAD

**Issue by Viterkim** [killergerbah/asbplayer#480]
Maybe related to equality of the timestamps of when to show a subtitle, or rerendering? (Overlap on end and start of a subtitle)

This is really annoying when replaying some subtitles again and again :D

Here's an example
```
5
00:00:29,100 --> 00:00:31,400
「この先に記されていることは

6
00:00:31,400 --> 00:00:34,740
正直 信じられないようなことだと
思うけど
```

1:
![image](https://github.com/user-attachments/assets/51648cb7-9174-494d-8216-3e71eddb7e89)

2:
![image](https://github.com/user-attachments/assets/0763230f-0396-4375-9b94-e0c0a01bee0e)

And when pressing replay on 2 (ghetto screenshot with phone as windows print screen was too slow):
![image](https://github.com/user-attachments/assets/81c21cf1-18cb-441f-8974-f8c128fa5794)

[Seishun Buta - 01.zip](https://github.com/user-attachments/files/16479225/Seishun.Buta.-.01.zip)

Depending on the subtitle, it happens randomly, like from 5% to 90% of the time

**Comment by killergerbah** [comment]
Thanks for reporting this issue!

**Comment by Viterkim** [comment]
Great work, and thanks for putting up with all the comments! Just did a donation on github.
