### ISSUE TITLE
This document requires 'TrustedHTML' assignment.

### ISSUE THREAD

**Issue by s-cork** [killergerbah/asbplayer#482]
Yesterday no problems.
Today, on youtube, I get the error:
```
Failed to execute 'parseFromString' on 'DOMParser': This document requires 'TrustedHTML' assignment.
```

The image is what I'm seeing:
<img width="511" alt="Screenshot 2024-08-06 at 14 10 26" src="https://github.com/user-attachments/assets/1b4114bc-3a57-4d1f-a7f2-b0588bd87823">

I checked Netflix, and asbplayer works as expected there.
I did all the obvious things (restarted the browser, removed and re-added the extension, restarted my laptop)

MacOS 14.4.1
Arc Browser (Chromium Engine Version 127.0.6533.89)

**Comment by VenroyDEV** [comment]
Got the same issue today

**Comment by s-cork** [comment]
update - this only happens on one of my YouTube accounts. When I switch accounts asbplayer works as before.

**Comment by Loongoon** [comment]
I'm also having the same issue, and it also only happens on one of my YouTube profiles.

**Comment by StarlightsJourney** [comment]
bruh, I can't learn Japanese without this :< any fixes yet or other alternatives available?

**Comment by killergerbah** [comment]
Seems like a new YouTube update rolling out.
Apparently switching login profiles can help.
I'll be working on this between work and life stuff but hopefully I can have a fix soon. YT seems to have obfuscated their code even more than before so this may be a tough one.

**Comment by s-cork** [comment]
I've had a quick look at the code and this seems to be the line causing the issue:

https://github.com/killergerbah/asbplayer/blob/dd5f49f3ab97cd5b1eefa2cde113704a125e69b5/extension/src/pages/youtube-page.ts#L18


Something like this seems to work

```javascript

const trusted = trustedTypes.createPolicy("myPolicy", {
  createHTML: (s) => s
});


```

and changing the line of code above to

```javascript

                .then((pageString) => { 
                    const html = trusted.createHTML(pageString);
                    return new window.DOMParser().parseFromString(pageString, 'text/html'))
                }
```

**Comment by killergerbah** [comment]
@s-cork Hi, were you able to get the subtitle detection working completely?

In my case, instead of the original error message:
```
Failed to execute 'parseFromString' on 'DOMParser': This document requires 'TrustedHTML' assignment.
```

I got a new one:
```
Failed to execute 'parseFromString' on 'DOMParser': This document requires 'TrustedHTML' assignment.
```

which makes sense since the error is being thrown from a line farther below which evaluates a string as JavaScript.

**Comment by killergerbah** [comment]
Never mind, it looks like the analogous function needs to be called for the script. Thanks @s-cork !
