### ISSUE TITLE
Closing fullscreen in webapp

### ISSUE THREAD

**Issue by penguinbrew** [killergerbah/asbplayer#483]
Every time i use yomitan in fullscreen mode in the webplayer, whenever i want to close the popup by ex. clicking on the video or the menu bar, fullscreen ends and i am back to windowed mode. This has just recently startet happening.

**Comment by avc1657** [comment]
Same happening here. A temporary solution is using the pop out feature (iirc that's the name). That one the video opens in a new window. Putting it to full-screen in the new window and using yomitan as you described doesn't cause the issue, at least on my end.

**Comment by penguinbrew** [comment]
That seems to do the trick for now. Thank you :-)

**Comment by killergerbah** [comment]
Not obvious to me why this is happening. You could instead simulate fullscreen mode by hiding the subtitle list and the app bar as a workaround.

**Comment by zuckyyyy** [comment]
I had the same issue, my workaround was just setting a hotkey to close yomitan
