### ISSUE TITLE
Error loading youtube subtitles

### ISSUE THREAD

**Issue by emanuelps2708** [killergerbah/asbplayer#484]
Hi, I installed asb player on brave but for some reason it doesn't work with youtube videos, I disabled shield and enabled all the extension permissions but it still doesn't work. It works with downloaded subtitles though. 
Asb player settings: 
[asbplayer-settings.json](https://github.com/user-attachments/files/16515417/asbplayer-settings.json)
![WhatsApp Image 2024-08-06 at 14 55 50](https://github.com/user-attachments/assets/7ba3c2b1-9c3e-44e4-853a-09bd3b54fdce)
![WhatsApp Image 2024-08-06 at 14 56 21](https://github.com/user-attachments/assets/61e894a2-881c-48db-a7c6-d49081015379)

**Comment by StarlightsJourney** [comment]
same issue, if possible, go and comment on the other post so others will know it's urgent.

**Comment by s-cork** [comment]
Duplicate of #482

**Comment by killergerbah** [comment]
Seems like a new YouTube update rolling out.
Apparently switching login profiles can help.
I'll be working on this between work and life stuff but hopefully I can have a fix soon. YT seems to have obfuscated their code even more than before so this may be a tough one.

**Comment by killergerbah** [comment]
Closing as duplicate.
Fix is in thanks to @s-cork
