### ISSUE TITLE
Failed to execute 'parseFromString' on 'DOMParser': This document requires 'TrustedHTML' assignment.

### ISSUE THREAD

**Issue by YossefGamerr** [killergerbah/asbplayer#485]
![image](https://github.com/user-attachments/assets/b61115c9-8ef6-4914-92f7-724563ba2565)

**Comment by killergerbah** [comment]
Fixed in https://github.com/killergerbah/asbplayer/issues/482#event-13800352358
Release will be in a couple days after Chrome web store approves.
