### ISSUE TITLE
Youtube subtitle detection 

### ISSUE THREAD

**Issue by Daii1414** [killergerbah/asbplayer#487]
I installed a new plugin update and restarted the Chrome browser, but my error changed from:

Failed to execute 'parseFromString' on 'DOMParser': This document requires 'TrustedHTML' assignment

to:
![Screenshot_20](https://github.com/user-attachments/assets/0c5c09a6-6f2f-4d68-80ac-97b1d4e995d0)

Refused to evaluate a string as JavaScript because this document requires 'Trusted Type' assignment

**Comment by WaynMax** [comment]
![スクリーンショット 2024-08-08 132345](https://github.com/user-attachments/assets/f8efc772-531a-4801-befe-cd7ae8d15735)
Same ploblem

**Comment by Varangian6** [comment]
![Снимок](https://github.com/user-attachments/assets/0293dfa2-e31a-4b98-9534-24b460cffa52)
The same issue. I can't sentence-mine. Got some technical issiues today with new update and I have no clue how to solve it. Hte old versions don't woth also.

**Comment by Loongoon** [comment]
They have found a fix for this bug, but I'm confused on how to implement it. Here's the original post: https://github.com/killergerbah/asbplayer/issues/482

**Comment by killergerbah** [comment]
Fixed in 1.4.1. Let me know if it works for you all.

**Comment by WaynMax** [comment]
> Fixed in 1.4.1. Let me know if it works for you all.

Perfect!
