### ISSUE TITLE
Can't solve issue with new extention, 1.4.1

### ISSUE THREAD

**Issue by Varangian6** [killergerbah/asbplayer#491]
Before submitting an issue check out the common issues section of the README:
https://github.com/killergerbah/asbplayer?tab=readme-ov-file#common-issues
Hello, as a lot of people resently, I've got proplemms with Youtube subtitles. The new update was released an hour ago but I can't install it. It says-The manifest file is missing or unreadable. 

![Снимок](https://github.com/user-attachments/assets/ec802018-fe50-4202-b1d4-5611c2f685d0)
How to solve it, guys?

**Comment by killergerbah** [comment]
@Varangian6 Use this https://github.com/killergerbah/asbplayer/releases/download/v1.4.1/asbplayer-extension-1.4.1-chromium.zip

**Comment by Varangian6** [comment]
Thank U so much. It works perfectly, once again!
