### ISSUE TITLE
"en - English" and "en - English ( auto-generated )" are selected at the same time, I can't select one of these

### ISSUE THREAD

**Issue by andranikarakelyan** [killergerbah/asbplayer#493]
Last few days there an issue during language selection. In my case, "en" and "en ( auto-generated )" are selected at the same time, I can't select one of these, and I don't know exactly which is selected ( manual or auto-generated version ). There are some videos, on which this is not an issue (  e.g. https://www.youtube.com/watch?v=h_lZo9hvNhY&ab_channel=PursuitofWonder ), and there videos on which it is ( https://www.youtube.com/watch?v=lPrjP4A_X4s&t=6s&ab_channel=Kurzgesagt%E2%80%93InaNutshell ). I see this issue at least on Chrome and Edge.

I think maybe this is related with manual subtitle's name, if it's a same as a auto generated subtitle, both are selected at the same time ( "en - English" in this case ).

![image](https://github.com/user-attachments/assets/8ae77c87-5dcc-49a2-8e1e-7d5aca8df55e)

![image](https://github.com/user-attachments/assets/05d4f8a9-654d-486c-b174-48abe4af9259)

**Comment by killergerbah** [comment]
Which version are you on? Should be fixed on 1.4.2.

**Comment by andranikarakelyan** [comment]
> Which version are you on? Should be fixed on 1.4.2.

Ah, it was the latest version, but I needed to restart. Everything works now. Thank you!
