### ISSUE TITLE
Audio track selector doesn't appear even after enabling experimental web platform features

### ISSUE THREAD

**Issue by dungdul** [killergerbah/asbplayer#494]
I have enabled experimental web platform features as suggested in README. However audio track selector doesn't seem to appear. I don't know if this is a bug or I have done something wrong.
![image](https://github.com/user-attachments/assets/fef86f60-0d5f-416e-98d5-0a59bd776b30)

**Comment by killergerbah** [comment]
Different audio tracks could have different encodings. Not all of them might be supported by your browser. You can get more information by using ffmpeg to find out the encoding of each audio track.
