### ISSUE TITLE
New Version Set "subtitles width" to 100%

### ISSUE THREAD

**Issue by bpwhelan** [killergerbah/asbplayer#496]
I was noticing that I couldn't interact with the video anywhere adjacent to the subtitles. Then realized this setting was set to 100% somehow (on both edge and chromium). This should definitely be defaulted to "auto" since that works flawlessly for me and I assume most users.

100% vs "auto" cant pause the video on 100%
![image](https://github.com/user-attachments/assets/7a2f761a-b5af-407b-a236-5e5976997ef9)
![image](https://github.com/user-attachments/assets/10f9f961-f8ac-4557-8652-f554112b7bde)

Also opening this issue for if people notice this and come to open an issue. Just click the "x" in subtitle width in "subtitle appearence" and it fixes this specific issue.

**Comment by killergerbah** [comment]
Default will be changed back to 'auto' in 1.5.0.
