### ISSUE TITLE
subtitle background opacity does nothing

### ISSUE THREAD

**Issue by clearlyqt** [killergerbah/asbplayer#501]
subtitles displayed on the video have no background despite having it on, tried changing values, reloading, seeing if theres formatting in the subs themselves but it will not display
![image](https://github.com/user-attachments/assets/e187c64c-00f6-4fec-96ca-e4f122750be9)
![image](https://github.com/user-attachments/assets/8835f978-0cc1-4974-9d6d-e7f5d798a025)

**Comment by DarkMessiah27** [comment]
I have the same issue. For what it's worth: I used the asbplayer on Saturday without issue, but on Sunday the problem with the subtitle background started. This doesn't seem to be a problem with the video or subtitle files as the problem also occurs on the video/subtitle file I watched on Saturday (the one without issues) or other videos I watched recently. The same thing happens to all video and subtitle files.

Some other subtitle related display options, like bottom/top alignment _do_ work.

**Comment by killergerbah** [comment]
@clearlyqt @DarkMessiah27 What browsers are you all using? Can you paste what you see when you right click on the subtitles -> inspect element?

**Comment by clearlyqt** [comment]
![image](https://github.com/user-attachments/assets/c380149f-bf4b-4340-9e91-90822821fcd7)
![image](https://github.com/user-attachments/assets/98763e05-82f5-44df-9162-13943fc66cf0)
using the installed app

**Comment by killergerbah** [comment]
@clearlyqt @DarkMessiah27 Fix is deployed; can you confirm that it's working?

**Comment by clearlyqt** [comment]
![image](https://github.com/user-attachments/assets/8699df31-8abc-41b4-8ff9-4b80de48265b)
looks good, thanks a lot

**Comment by salty-cell** [comment]
i had the same issue yesterday (no text background), and while the deployed fix makes the background appears now, it makes multi-line subtitles look weird, it is just one big box now

![image](https://github.com/user-attachments/assets/4a7c03ca-b419-4222-accd-bd6abdf56d66)
(image: how it used to look just a couple of days ago vs how it looks now)

tried multiple versions (updating/downgrading), different videos and different subs, and even tried different chromium browsers always the same thing

**Comment by killergerbah** [comment]
Yeah someone else reported the giant box issue too, hopefully this is the final fix for the issue.
