### ISSUE TITLE
They don't load my subtitles

### ISSUE THREAD

**Issue by Pepo-cell** [killergerbah/asbplayer#502]
When I tap the keyboard shortcut I don't get the subtitles.

**Comment by killergerbah** [comment]
Can you give some more details? What do you mean by "I don't get the subtitles?" What are you expecting to get? What website are you seeing this problem on?

**Comment by Pepo-cell** [comment]
Mira en YouTube no me cargan los subtitulos cuando toco el atajo de teclado
ctrl+shift+f no me cargan.

**Comment by killergerbah** [comment]
Can you check your keyboard shortcuts at `chrome://extensions/shortcuts`?
