### ISSUE TITLE
Choppy Audio Playback during Recording and Anki Card

### ISSUE THREAD

**Issue by KaiWritesCode** [killergerbah/asbplayer#503]
Audio is coming out choppy when recording. Happening on version ASBPlayer 1.4.2. Confirmed audio drivers are up to date. Occurring on all tested browsers.

**Comment by killergerbah** [comment]
Most likely lacking sufficient CPU to record audio smoothly. If you're using a laptop I recommend trying while connected to a power source.

**Comment by KaiWritesCode** [comment]
Connecting to power source fixed the problem. Thank you!
