### ISSUE TITLE
Clicking anywhere on the player video exits fullscreen

### ISSUE THREAD

**Issue by DPowrie** [killergerbah/asbplayer#504]
This is an issue I only encountered recently after having used asb player with no issue previously.

I know this is an extreme first world problem but it gets really annoying when trying to scan words with yomitan and it ends up exiting fullscreen everytime.

I thought there could be a problem with yomitan at first, but I found that even the features such as "scan popup disappears after x amount of time" wouldn't work as there seems to be something inside of asb player stopping any action like that, whereas it worked on any other webpage.

Hope this isn't too vague but if there's any extra info I need to add just let me know

**Comment by DPowrie** [comment]
I bring up the "popup disappearing" as a possible fix as it would mean I wouldn't have to click on text/ the bottom of the screen in order to make the popup disappear, but either way - it ends up exiting fullscreen anyway.

**Comment by Viterkim** [comment]
Does a violentmonkey script like this fix it?
```
// ==UserScript==
// @name        asbplayer: Doduble click killer for fullscreen
// @namespace   Violentmonkey Scripts
// @match       https://killergerbah.github.io/asbplayer/*
// @grant       none
// @version     8.5
// @author      Gippity
// @description 7/6/2024, 1:33:00 PM
// ==/UserScript==

(function() {
    'use strict';

    document.addEventListener('dblclick', function(event) {
        if (event.target.tagName.toLowerCase() === 'video') {
            event.stopPropagation();
        }
    }, true);
})();
```
I have it to disable clicks to fullscreen

**Comment by DPowrie** [comment]
> Quote reply
> Refere

Thanks so much for giving this a shot, but it seems my issue is still continuing.

I think the two strange things about this situation is that is ONLY happens after I scan something in from Yomitan, but like I mentioned previously, I'm pretty sure it's not an error on their end purely because the strange issues have only shown up on asb player and everything else has operated smoothly.

That being said I'd obviously be open to looking in to see if theres an issue for Yomitan for some reason but I could mess about with some more setting and see if I can find anything out.

Once again, thank you for trying!

**Comment by killergerbah** [comment]
I've pushed a fix for this.
@DPowrie  @Viterkim I would appreciate if you can confirm it's fixed on your end.

**Comment by DPowrie** [comment]
That seems to have done the trick! Thanks so much @killergerbah
