### ISSUE TITLE
"Mine current subtitle and open Anki dialog" No longer works in fullscreen (Mac Google Chrome)

### ISSUE THREAD

**Issue by zuckyyyy** [killergerbah/asbplayer#506]
After using the Mine current subtitle and open Anki dialog shortcut, the dialog only shows up until fullscreen is exited. The updated card notification after mining also only appears when exiting full screen.

**Comment by killergerbah** [comment]
@zuckyyyy I deployed a fix for this, let me know if it works for you.

**Comment by zuckyyyy** [comment]
Works now thanks
