### ISSUE TITLE
Volume being increased when extracting subtitles for Anki

### ISSUE THREAD

**Issue by AstralDice** [killergerbah/asbplayer#510]
**Before submitting an issue check out the common issues section of the README:**
https://github.com/killergerbah/asbplayer?tab=readme-ov-file#common-issues

**What is the issue and how what do you do to make it happen**
Whenever I use asbplayer to extract subtitles for anki, after the first, second or third (it's basically lottery from what I can tell) time I extract subtitles (including audio and a screenshot), the volume of the media increases by (guesswork) roughly 70%. This 70% increase however is not captured by the audio capturing system, however it does extremely annoy me. Whenever I restart the website and set up asbplayer again, it comes back to normal but again occurs after very few extractions for Anki.
**What browser?**
Firefox but also had the same issue with Opera GX
**Is it happening with local video or streaming video?**
streaming video
**If the issue is happening with streaming video, what version of the extension are you using?**
Version 1.4.2, last time I updated it was August 16 2024
**If the issue is happening with streaming video, on what website(s) is the issue happening?**
zoroxtv.to (doesn't exist anymore tho), hianime.to, 9animetv.to

**VERY IMPORTANT EDIT:**
I'm doing some trial and error on my behalf and it **seems** (haven't tested it enough to be 100% sure) to be the case whenever I try listening to the extracted audio (to check if the audio is the way I want it or not) when the interface for importing cards to Anki opens up (by clicking on the audio file name).

edit 2, electric boogaloo: seems to not having to do with the audio replay lol mb

**Comment by killergerbah** [comment]
This is a bug with how asbplayer manages the video's audio stream on Firefox. Fix will go into 1.5.0.

**Comment by AstralDice** [comment]
@killergerbah thank thee, I can finally use asbplayer with my headphones because there was one scene (actually it was two: the Given movie (anime) where they started playing the song & a scene where a car just casually drove by) which made a literal bass boosted (unjoking) 400% volume increase which destroyed my eardrums but still made me laugh lmao

Thank you so so much!!! (If I one day have the money laying around I'd gladly donate some money cause you've been helping me out so much that I can't leave this service ungifted from my side lol)
