### ISSUE TITLE
Netflix Image and Audio blank with Chrome Extension

### ISSUE THREAD

**Issue by llbaker302** [killergerbah/asbplayer#511]
**Issue**

When using the chrome extension on Netflix for creating Anki cards - the image is black and the audio is blank.

**What should Happen**

The card should be populated with an image from the show and some audio.

**Screenshot**

![image](https://github.com/user-attachments/assets/c9bdddef-2e68-45c6-8816-0949a31cbed3)

**Steps to recreate**

1. Click on a video on Netflix
2. Press keyboard shortcut to load subtitles
3. Create an Anki card with base application like vocabsieve
4. Make sure tab is selected and in the foreground and press keyboard combination to update Anki card

**What browser?**

Google Chrome Version 128.0.6613.120 (Official Build) (64-bit)

**Is it happening with local video or streaming video?**

Streaming video

**If the issue is happening with streaming video, what version of the extension are you using?**

1.4.2

**If the issue is happening with streaming video, on what website(s) is the issue happening?**

Netflix

**Comment by killergerbah** [comment]
@llbaker302 Regarding the screenshot - unfortunately for some computers there are problems taking screenshots of Netflix when hardware acceleration is enabled. I would try disabling hardware acceleration and see if that helps. Keep in mind that this will drain your CPU faster when watching videos.

Regarding audio, is the audio field of your Anki card being populated with anything at all? If not, then asbplayer's Anki settings may be misconfigured and you need to point the audio field at the right place. I would also check the STREAMING VIDEO settings to make sure "Record audio" is enabled.
