### ISSUE TITLE
SRT subtitles not loading

### ISSUE THREAD

**Issue by jonathanluepfert** [killergerbah/asbplayer#515]
I have srt subtitles that work if I drag them onto the video but when watching the video with Emby the subtitles don't automatically load. The dialog to choose a subtitle opens and the subtitles are found, but when clicking on OK nothing happens: https://imgur.com/a/EnkEpsM
The subtitles have the same name as the video file and are found, but they don't load for some reason.

**Comment by bpwhelan** [comment]
already fixed in dev, to fix for right now, edit your srt name to *.ja.srt, the language being null is what is causing this.

**Comment by bpwhelan** [comment]
@killergerbah this should be closed after https://github.com/killergerbah/asbplayer/pull/514 was merged.
