### ISSUE TITLE
AnkiConnect failed to fetch

### ISSUE THREAD

**Issue by yona19** [killergerbah/asbplayer#52]
I added https://killergerbah.github.io to ankiconnect but it doesn't work. Do you know how to fix it?

**Comment by killergerbah** [comment]
@yona19 Some questions:
What browser are you using? Do you have any ad blockers enabled? 
Can you paste the logs that appear when trying the AnkiConnect URL in asbplayer?
Go to Chrome menu -> Other tools -> Developer console to see logs.

**Comment by yona19** [comment]
I changed the browser to Chrome and it worked. Thank you I really appreciate it

**Comment by killergerbah** [comment]
Glad it works now. Curious what browser you were using? I know with Brave you have to add the asbplayer site to a whitelist.

**Comment by yona19** [comment]
Sorry for the late response. I was using brave.
