### ISSUE TITLE
600ms addtional recording on online videos

### ISSUE THREAD

**Issue by AAAAbleng** [killergerbah/asbplayer#528]
As youtube auto-generated subtitles often cut one sentence into many pieces, while mining on the youtube, I often need to adjust the audio cutting point manually.

Cause there is no reference to determine if a certain word is included, I need to adjust the starting and ending point and hit the white recording dot on the right of the audio field over and over again. It's indeed something I have to do. However, the recording timeline is a little bit tricky. After clicking the dot, I can hear the full recording based on the period I chose. But after exporting to anki and cheking the card on anki, the audio on anki is about 600ms shorter than the recording I hear; the last 600ms is omitted.

I guess the recording I hear whist mining is actually 600ms longer than the preset time, the recording did not stop at the right place. The result is that every time during mining, I need to add 0.6s at the ending point after I hear the right audio and click the white dot once again to record what I want (at this time I will also hear an additional 600ms audio that will not be included on anki card).

I tried to adjust Audio Padding, but it does not help but add the padding to the timeline, which does not change the recording anyway.  

Also, for local videos, the cutting point is as precise as I hear during mining. It looks like just a glitch of recording.

Thank you for reading my post and hopefully I stated my question clearly. This is really a fantastic extention for second language learners!!!

**Comment by killergerbah** [comment]
Hi, I believe I understand the issue. asbplayer is mp3-encoding the audio immediately after recording. This should be a relatively simple fix. In the mean time you can work around the issue by turning off the "re-encode audio in mp3" option under the MINING section of the settings. Unfortunately this means that your audio will be in `webm` if you're using Chrome and not `mp3`, but this isn't a problem if you only review Anki cards on a desktop computer. Thanks for reporting!
