### ISSUE TITLE
Update last-created Anki card command no longer works

### ISSUE THREAD

**Issue by Cassandre60** [killergerbah/asbplayer#536]
![chrome_AJUD9JBWa0](https://github.com/user-attachments/assets/aff3b611-93c5-4dd5-b056-bbfdc910c5f0)
Hi.
Simply put the extension stopped working today (specifically, only the Update last-created Anki card command )for no reason and I have no idea why,

Open in Anki still works but is too tedious since I usually use this extension with Yomitan.

Tried the troubleshooting methods in the README with no success,
I'm Windows 11, google chrome, last version of the extension,
Any help would be appreciated

**Comment by killergerbah** [comment]
Can you upload screenshots of your Anki settings and the Anki note type you're using?
The only thing I can think of is that somehow the settings are no longer matching up anymore.

**Comment by Cassandre60** [comment]
ok, but I doubt that since open in anki still works
![image](https://github.com/user-attachments/assets/c8603765-c784-488f-bee3-a574ca8086f8)
edit: Woke up this morning and everything seems to work, I did not change anything, but finger crossed things stay this way

**Comment by Cassandre60** [comment]
Since my problem is solved for now, I'm turning this into a feature request,

Is it possible to have below Anki Connect URL in stetting some kind of green or red light that signals if everything is going ok, I mean in addition to connecting to Anki-Connect, sending a test card to Anki and verifying internally that sound and image are there and then deleing this test card.

**Comment by killergerbah** [comment]
Created new issue for feature request at https://github.com/killergerbah/asbplayer/issues/542 and closing this one
