### ISSUE TITLE
Keyboard shortcuts hints 

### ISSUE THREAD

**Issue by ganqqwerty** [killergerbah/asbplayer#545]
Before submitting a feature request, please look through the asbplayer readme (https://github.com/killergerbah/asbplayer) and settings (https://killergerbah.github.io/asbplayer/?view=settings)
to be sure that your feature request isn't already implemented.

**Is your feature request related to a problem? Please describe.**
I'm using ASBPlayer for a year already but I'm constantly forgetting the keyboard shortcuts. The extension's main interface is through keyboard, but if you don't use the shortcut often, you just don't know. Also, the shortcut-oriented interface often alienates the new users. People simply don't know where do click, they don't know the full set of features until they spent a lot of time trying to tweak ASBPlayer and effectively becoming power users. 

**Describe the solution you'd like**
An obvious way would be to have more buttons on the floating control panel. Each button should have a tooltip. Preferably each button should be on a control panel, but users can hide or show as many buttons as they want. 

**Describe alternatives you've considered**
An alternative way is to have a button "show shortcuts" somewhere 1 click away with all shortcuts displayed on one page. Here's how the KeyCue program allows doing that for Mac: 
![image](https://github.com/user-attachments/assets/d067b342-143d-4dd6-897e-786b9eedfbd2)

**Comment by killergerbah** [comment]
@ganqqwerty I haven't put absolutely every bind in the overlay but this is what it looks like now and I'd be curious what you think:

https://github.com/user-attachments/assets/5206f7bb-3c6f-4892-8f92-819842d1e61b

**Comment by killergerbah** [comment]
I believe most of the important asbplayer features are now in the overlay. Adding even more can be separate tasks.
