### ISSUE TITLE
Audio gets distorted when replaying audio on Opera GX

### ISSUE THREAD

**Issue by AstralDice** [killergerbah/asbplayer#554]
**Before submitting an issue check out the common issues section of the README:**
https://github.com/killergerbah/asbplayer?tab=readme-ov-file#common-issues

**What is the issue and how what do you do to make it happen**
whenever I replay the audio of the sentence I'm sentence mining, the audio gets distorted. By that I mean that the recorded audio etc. still being fine and being pretty much the exact same audio as outputted from the player, but when I replay the audio (to check if the recorded audio is the way I want it to be) it gets distorted for roughly half a minute
**What browser?**
Opera GX
**Is it happening with local video or streaming video?**
streaming video
**If the issue is happening with streaming video, what version of the extension are you using?**
1.5.0
**If the issue is happening with streaming video, on what website(s) is the issue happening?**
hianime.to

**Comment by killergerbah** [comment]
Usually this type of issue has to do with lack of CPU. If you're using a laptop I would try connecting it to a power source.

**Comment by AstralDice** [comment]
My laptop is almost constantly connected to a power source and when I looked at my task manager, the CPU didn't go above 15% (I have a laptop with an i5-4210M). The RAM is a bit high but if I only take Opera GX into account, I only reach roughly 20% at most of my available RAM

**Comment by killergerbah** [comment]
Interesting seems to random from my perspective 
If it happens again and you notice any patterns let me know
