### ISSUE TITLE
"Remove names enclosed by parenthesis" regex filter doesn't work anymore

### ISSUE THREAD

**Issue by unectomy** [killergerbah/asbplayer#562]
The regex filter that removes names enclosed by parentheses, `([(（]([^()（）]|(([(（][^()（）]+[)）])))+[)）])`, does not work anymore. Before, I wouldn't see parentheses and the text inside them in subtitles, but now, I do.

I think the issue came from #556 where the `v` flag was added to regex filtering. If you go to https://regex101.com/, paste the above filter, set the flavor to JavaScript, and add use the flags `gv`, you get an error. However, if you escape the filter like `([\(（]([^\(\)（）]|(([\(（][^\(\)（）]+[\)）])))+[\)）])`, you don't get an error anymore.

If I use this escaped filter on asbplayer, then I don't see parentheses and their text in subtitles, which is what I expect the "removes names enclosed by parentheses" filter to do.

**Comment by mathiaslovnes** [comment]
I have the same error. It worked until very recently.
This is the filter I'm using:
[(（][^()（）]*[)）]|[→《》。＞＜～　♪]

**Comment by killergerbah** [comment]
As @unectomy  mentioned please escape the parentheses by inserting backslashes before them e.g. `[\(（][^\(\)（）]*[\)）]|[→《》。＞＜～　♪]`
