### ISSUE TITLE
No sound playing after dropping the video file on to ASB Player

### ISSUE THREAD

**Issue by SamSS956** [killergerbah/asbplayer#563]
Hi,

I use ASB Player on Google Chrome. When I loaded my video file from my laptop drive, the video didn't play any audio. Is it an issue for certain video? How can be done to solve this problem? Looking forward to any suggestions and advice.

Cheers

**Comment by killergerbah** [comment]
@SamSS956 Probably your browser doesn't support the audio format of the file. See this advice on browser support for audio/video formats: https://github.com/animebook/animebook.github.io?tab=readme-ov-file#video-format-support-last-update-january-2023

The same advice applies to asbplayer.

**Comment by SamSS956** [comment]
@killergerbah Thank you for the advice. I successfully installed the Chromium browser with [Marmaduke all-codecs+] and added the Chromium web store to it. However, I couldn't add asbplayer and yomitan to Chromium.
![スクリーンショット 2024-11-04 125056](https://github.com/user-attachments/assets/e0dce557-d8af-4492-85d0-a255d3ee4121)
