### ISSUE TITLE
Updates for [No sound playing after dropping the video file on to ASB Player (Issue #563)]

### ISSUE THREAD

**Issue by SamSS956** [killergerbah/asbplayer#564]
@killergerbah  Thank you for your advice on the last post. I managed to install the chromium-browser with [Marmaduke all-codecs+]. I also added the Chromium Web store to allow me for adding extensions. However, I couldn't add Yomitan into the extension. Any suggestions you recommend? 

Cheers 

![スクリーンショット 2024-11-04 135059](https://github.com/user-attachments/assets/c1457565-d1bd-46a2-a877-dbd02587690f)

**Comment by killergerbah** [comment]
@SamSS956 Sorry I don't have specific advice. You can try hopping onto the Discord server and asking there since I assume most people who install a custom build have to deal with this problem.

**Comment by SamSS956** [comment]
@killergerbah No worries! I found the solution so now all the things worked! Appreciate that!
