### ISSUE TITLE
Image capture failed on Android using Kiwi browser

### ISSUE THREAD

**Issue by miroshQa** [killergerbah/asbplayer#575]
When I try to mine words using the kiwi browser on android, the extension cannot take a screenshot. 

Here's the error I get:
![Screenshot_20241129-233241~2](https://github.com/user-attachments/assets/72b6c622-11a2-4d2d-b823-3a4039798c85)
![Screenshot_20241129-233454](https://github.com/user-attachments/assets/5f01518e-02d3-46ca-9632-6be398321f19)

1) I also tried  it in firefox mobile and it doesn't work either.

2) I also gave all permissions to the kiwi browser but it didn't help
![5354945249216162911](https://github.com/user-attachments/assets/34d23b62-7d1e-4188-8eb0-0b4d82af5434)

**Comment by miroshQa** [comment]
I found a mention of this problem [here](https://github.com/killergerbah/asbplayer/issues/438#issuecomment-2244137498). If it is not possible to fix it, then I think it is worth mentioning it in the readme as a known issue to avoid confusion

**Comment by miroshQa** [comment]
I have one more question. Image capture also does not work in firefox mobile due to the lack of screenshot api?

**Comment by killergerbah** [comment]
For Firefox with Android the screenshot API exists but from testing it does not appear to function. Maybe this will be fixed in the future.

In the mean time I will add a warning to the README as per your suggestion.
