### ISSUE TITLE
Is there a way to switch the order of two overlapping subtitle lines based on their timestamps?

### ISSUE THREAD

**Issue by goINTo425** [killergerbah/asbplayer#577]
**Is your feature request related to a problem? Please describe.**
For example, in the following video, the overlapping subtitles are as follows:
https://www.netflix.com/watch/80084854

- 70 00:01:41,476 --> 00:01:43,144 That didn't stop you  
- 71 00:01:41,476 --> 00:01:43,144 from taking on  
- 72 00:01:43,144 --> 00:01:45,146 No, it didn't.  
- 73 00:01:43,144 --> 00:01:45,146 those miners last year. 

In reality, the dialogue is:
- "That didn't stop you from taking on those miners last year."
- "No, it didn't."

The overlapping timestamps indicate that the distinction between these lines relies on their positioning on the screen. Since regex pattern matching is typically applied to single lines, it doesn’t seem possible to use regex alone to address this issue.

**Describe the solution you'd like**
I’ve thought of two potential solutions:

1. Merge overlapping subtitles in asbplayer, and then resolve the issue using regex, such as:
^([A-Z][^.!?]*[.!?])\n([a-z][^.!?]*[.!?])  replace with $2 $1

2. Detect overlapping subtitles in asbplayer, identify their screen positions, and reorder them so that the higher-positioned subtitle appears first. 
In VTT files, the position of each line can be determined.

This seems like an issue that can be easily fixed by developers, but it’s probably impossible to resolve on the user’s end. 
Thanks for your help!

**Comment by killergerbah** [comment]
It was easy enough to sort by position on screen
