### ISSUE TITLE
Side panel not working

### ISSUE THREAD

**Issue by OMGerCoder** [killergerbah/asbplayer#585]
**What is the issue and how what do you do to make it happen**
The side panel is not working, it just doesn't appear when I want it to. Nothing happens.
**What browser?**
Opera GX
**Is it happening with local video or streaming video?**
Streaming video/possibly local video
**If the issue is happening with streaming video, what version of the extension are you using?**
[1.6.1](https://github.com/killergerbah/asbplayer/releases/tag/v1.6.1)
**If the issue is happening with streaming video, on what website(s) is the issue happening?**
All websites

**Comment by killergerbah** [comment]
@OMGerCoder Opera's fork of Chromium is many versions behind and doesn't support the Chromium side panel.
