### ISSUE TITLE
Timestamp Added to Mined Sentence on Mobile

### ISSUE THREAD

**Issue by zesky18** [killergerbah/asbplayer#592]
**What is the issue and what do you do to make it happen**
When mining content on mobile, a timestamp from the video is now attached at the beginning of the sentence when the sentence is grabbed through Yomitan. 

![1000231646](https://github.com/user-attachments/assets/130720d3-f4d3-47e3-aff9-fdb7bd390087)

I believe this issue might be related to asbplayer, as this behavior did not occur previously on mobile. It seems to have started after the mining overlay for the player was implemented. I double-checked by mining on PC, and the issue does not occur there.

**What browser?**
Kiwi Browser.

**Is it happening with local video or streaming video?**
Local video.

**Comment by killergerbah** [comment]
@zesky18 I've deployed a workaround. Let me know if it's still happening to you.

**Comment by zesky18** [comment]
> @zesky18 I've deployed a workaround. Let me know if it's still happening to you.

Thank you for the speedy fix. Indeed, it seems the problem is fixed. I will this issue now.
