### ISSUE TITLE
Adding player mode select to YouTube (mobile?)

### ISSUE THREAD

**Issue by shiki-tm** [killergerbah/asbplayer#593]
Since I really liked this new button for local video player on mobile I was thinking if it'd be possible to add this button to YouTube or I guess other platforms too? 
I don't know if some modes are difficult to add but I think as long as there's subs you can probably at least do repeat and auto pause right ? Would be especially great for YouTube on mobile. Thanks for considering! 
![Screenshot_20241221_112112_Kiwi Browser](https://github.com/user-attachments/assets/cfc51997-f978-4af2-ab65-eb0d36eb221a)

**Comment by killergerbah** [comment]
Yes, this will be in 1.7.0:
<img width="679" alt="image" src="https://github.com/user-attachments/assets/55acf0c4-5779-47a8-a791-2fd1279195dd" />
