### ISSUE TITLE
Buttons in the control overlay for Yle Areena videos are not clickable

### ISSUE THREAD

**Issue by east825** [killergerbah/asbplayer#600]
**What is the issue and how what do you do to make it happen**

When a video is paused on Yle Areena, the extension control overlay is visible (if enabled in settings) but none of the buttons is clickable.

**What browser?**

Arc Version 1.74.0 (57065)

**Is it happening with local video or streaming video?**

While streaming.

**If the issue is happening with streaming video, what version of the extension are you using?**

1.7.0

**If the issue is happening with streaming video, on what website(s) is the issue happening?**

https://areena.yle.fi

**Comment by killergerbah** [comment]
Thank you, this is fixed in the latest snapshot now.
