### ISSUE TITLE
Request: 2 subtitles at a time

### ISSUE THREAD

**Issue by aiko-tanaka** [killergerbah/asbplayer#66]
I'm not sure if this is the proper way to do this but,
Is it possible to request a feature to play two subs at the same time, e.g. another eng sub which i can toggle on/off with a hotkey?

Huge thanks

**Comment by killergerbah** [comment]
Thanks for the suggestion. I'll give it some thought but at first glance this seems like a complex change to make. Do you want it for local files or videos synced with the extension?

**Comment by aiko-tanaka** [comment]
Mostly for local files.
Btw, I don't have much experience with JS but I'm taking a wild guess that it's a bit complex because the subs might overlap visually?(e.g. if they're both displayed at the bottom) In which case I think it might be easier if the other sub is displayed at the top?
Not really sure though, but either way I'm fine with anything if it's too complex.

**Comment by killergerbah** [comment]
When I first thought about it the complexity comes from the fact that the code currently assumes that there is only one subtitle track in many places.

However after more thought I believe this feature is possible to implement without anything too crazy. I'll take a stab at it probably this weekend.

**Comment by aiko-tanaka** [comment]
Huge thanks!!

**Comment by killergerbah** [comment]
29efc7ee8526fb796ce516a7278793f25caafe7c
This change has been made.

To load multiple subtitle files, drag-and-drop all of them at the same time. Then use Ctrl+1,Ctrl+2... etc to toggle them on and off in the video player.

@aiko-tanaka  Let me know if you run into any issues!

**Comment by aiko-tanaka** [comment]
Thanks! It works perfectly.
I guess the only thing left would be an option to also hide the second sub(separate from Ctrl+1 or 2)  from the timeline browser at the right side. Other than that it's perfect.

----
I have an unrelated issue btw regarding AnkiConnect, 
My Yomichan works just fine with Ankiconnect, I've also already added `https://killergerbah.github.io/asbplayer/` to the webcorslist, and I've whitelisted the site from my adblock as per #52, but it still won't connect.
I'm on Anki 2.1.35, Yomichan 21.5.31.1 and Chrome 91.0.4472.124

Error from console:
`
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

Access to fetch at 'http://127.0.0.1:8765/' from origin 'https://killergerbah.github.io' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

HttpFetcher.js:4 POST http://127.0.0.1:8765/ net::ERR_FAILED
(anonymous) @ HttpFetcher.js:4
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ main.a28870b3.chunk.js:1
t @ main.a28870b3.chunk.js:1
(anonymous) @ Anki.js:178
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ main.a28870b3.chunk.js:1
(anonymous) @ Anki.js:13
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ main.a28870b3.chunk.js:1
(anonymous) @ SettingsDialog.js:210
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
setTimeout (async)
(anonymous) @ SettingsDialog.js:204
Al @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Nl @ react-dom.production.min.js:261
vl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
qi @ react-dom.production.min.js:123
Hi @ react-dom.production.min.js:122
gl @ react-dom.production.min.js:244
ru @ react-dom.production.min.js:289
t.render @ react-dom.production.min.js:296
256 @ index.js:8
i @ (index):1
t @ (index):1
r @ (index):1
(anonymous) @ main.a28870b3.chunk.js:1
Show 6 more frames

TypeError:Failed to fetch SettingsDialog.js:218
ypeError: Failed to fetch
(anonymous) @ SettingsDialog.js:218
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:29
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
setTimeout (async)
(anonymous) @ SettingsDialog.js:204
Al @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
Nl @ react-dom.production.min.js:261
vl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vi @ react-dom.production.min.js:122
qi @ react-dom.production.min.js:123
Hi @ react-dom.production.min.js:122
gl @ react-dom.production.min.js:244
ru @ react-dom.production.min.js:289
t.render @ react-dom.production.min.js:296
256 @ index.js:8
i @ (index):1
t @ (index):1
r @ (index):1
(anonymous) @ main.a28870b3.chunk.js:1

`

**Comment by aiko-tanaka** [comment]
After a few minutes of playing around with the new features, here are a few things I've noticed / suggestion

Bugs:
- the hotkeys ctrl+1 / 2 might not work when having multiple tabs open in chrome, probably because it conflicts with built-in chrome shortcuts --  ctrl+1(switch to 1st tab) or ctrl+2(switch to second tab)
- I'm not sure why but although the JP/main subs usually tend to be complete when importing, the EN/2nd subs usually have some lines missing (around 30% of the lines). I'll try to upload a video of what I mean maybe within a day. I can live with a few lines missing for now though.

Suggestions:
- would be nice to be able to specify which subtitle is the main subtitle(usually the JP subs). As such, it might be easier to specify its behavior (e.g. appears above the JP/main subs, can be hidden from the timeline)

**Comment by killergerbah** [comment]
Thanks for the feedback!

The multiple tab bug should be an easy fix. Weirdly I wasn't experiencing that issue even with lots of tabs but it should be easy enough to change the shortcut to something else.

I need to think about how hiding the subs in the timeline should look like. For the subtitle timeline I want it to still be obvious that there are multiple tracks, so I'm thinking that the hiding function could simply blur out the tracks that should be hidden, instead of completely removing them from the table. Wonder if you have thoughts on this?

I'll look into specifying the track order of the subs. I'm hoping this is as easy as dragging and dropping the files in a certain way.

The last two suggestions have been in the backlog for a while but since you're mentioning them I'll prioritize them higher. The filesize thing kind of annoys me too since syncing to AnkiConnect at the end of the day can take a long time. For what it's worth, you can use CSS on your Anki card types to display resize the images when they're displayed, if you're not doing that already.

**Comment by aiko-tanaka** [comment]
Regarding showing/hiding the subs from the timeline, I think having maybe having checkboxes at the top of the timeline should be fine? Or maybe just a single button that says 'multiple subs detected, click to specify which to hide/show' or something like that.

Thanks!
