### ISSUE TITLE
Allow cards to be created from multiple adjacent subtitles

### ISSUE THREAD

**Issue by killergerbah** [killergerbah/asbplayer#67]
In Anki export dialog, add a button to include next subtitle.

Other option is to allow press-and-hold, but it seems Chrome extension shortcuts, when held down, are throttled to the point where this may not be feasible.

**Comment by mgpanpan** [comment]
> In Anki export dialog, add a button to include next subtitle.
> 
> Other option is to allow press-and-hold, but it seems Chrome extension shortcuts, when held down, are throttled to the point where this may not be feasible.

Could cards be created from multiple adjacent subtitles now? Sometimes, sentences are separated in multiple timelines, and I hope a compete line could be reserved in Anki export.

**Comment by cyphar** [comment]
Moving the slider doesn't cause the audio to be re-recorded -- sometimes subtitles are split mid-sentence and being able to capture the entire sentence is much more preferable (copying the subtitle line into Anki is really trivial for a user anyway). In mpvacious this is really trivial to do (in fact it does it somewhat automatically -- if you copy a line's timestamps and then move to another line, both lines will be included in the new card), but I get that with web videos this is a lot more annoying to do nicely.

Ideally moving the slider should cause a button to appear which will re-record the audio. It would also be really nice if there was a button to preview the audio before the Anki card is made, so that we can double-check if we need to re-record the audio.

**Comment by mgpanpan** [comment]
> Moving the slider doesn't cause the audio to be re-recorded -- sometimes subtitles are split mid-sentence and being able to capture the entire sentence is much more preferable (copying the subtitle line into Anki is really trivial for a user anyway). In mpvacious this is really trivial to do (in fact it does it somewhat automatically -- if you copy a line's timestamps and then move to another line, both lines will be included in the new card), but I get that with web videos this is a lot more annoying to do nicely.
> 
> Ideally moving the slider should cause a button to appear which will re-record the audio. It would also be really nice if there was a button to preview the audio before the Anki card is made, so that we can double-check if we need to re-record the audio.
> 
> Right now the only way to do this is to create multiple cards (one for each subtitle line) and then put them as consecutive media items in the sentence audio field -- this is results in there being a noticeable gap between subtitles lines as well as just making mining more difficult that necessary IMHO.

Yes, I think currently asbplayer is not convenient for creating multi-line subtitle cards. The animebook (https://github.com/animebook/animebook.github.io) is more convenient for this purpose.

**Comment by cyphar** [comment]
> Yes, I think currently asbplayer is not convenient for creating multi-line subtitle cards. The animebook (https://github.com/animebook/animebook.github.io) is more convenient for this purpose.

Yeah but it seems that's only for local files (and mpvacious already works well enough for local files).

**Comment by killergerbah** [comment]
> Moving the slider doesn't cause the audio to be re-recorded -- sometimes subtitles are split mid-sentence and being able to capture the entire sentence is much more preferable (copying the subtitle line into Anki is really trivial for a user anyway). In mpvacious this is really trivial to do (in fact it does it somewhat automatically -- if you copy a line's timestamps and then move to another line, both lines will be included in the new card), but I get that with web videos this is a lot more annoying to do nicely.
> 
> Ideally moving the slider should cause a button to appear which will re-record the audio. It would also be really nice if there was a button to preview the audio before the Anki card is made, so that we can double-check if we need to re-record the audio.
> 
> Right now the only way to do this is to create multiple cards (one for each subtitle line) and then put them as consecutive media items in the sentence audio field -- this is results in there being a noticeable gap between subtitles lines as well as just making mining more difficult that necessary IMHO.

I missed this post but this feature should have been in the extension at the time of writing. If you adjust the slider then the checkmark button in the audio field becomes clickable. Clicking that button will cause the audio to be re-recorded.
