### ISSUE TITLE
Include Timestamp in "Source" Field

### ISSUE THREAD

**Issue by cyphar** [killergerbah/asbplayer#75]
It would be nice to have the timestamp of the subtitle line be included in the source field along with the name of the subtitle file. [I added something similar to mpvacious recently.](https://github.com/Ajatt-Tools/mpvacious/pull/36)

**Comment by killergerbah** [comment]
@cyphar Thanks for the suggestion. This is an easy change to make that I can probably get to tomorrow.

**Comment by killergerbah** [comment]
The app implements this as of now. The extension will include this change in the next release.
