### ISSUE TITLE
Screenshots cropped with wrong offset

### ISSUE THREAD

**Issue by LazyKernel** [killergerbah/asbplayer#84]
When screenshots are cropped, the size is correct but the offset is not resulting in something like this
![Image of broken cropping](https://i.imgur.com/YJheeWo.png)

Extension version: 0.15.0
Screenshot cleaning and cropping turned on.

**Comment by killergerbah** [comment]
As a workaround I would suggest watching the video in full screen.

This bug is happening because Crunchyroll uses an iframe for its video player and it's not easy to know the offset of the iframe inside the window from inside the iframe.
