### ISSUE TITLE
Subtitle file timing resets occasionally when pausing source video

### ISSUE THREAD

**Issue by ludie1** [killergerbah/asbplayer#85]
When I pause the source video, the subtitle file sometimes resets back to zero minutes in the asbplayer window. When I unpause the source video, the subtitles still appear in sync with the source video but when I want to sentence mine, the asbplayer can't record or capture anything since the subtitle file is still paused at zero minutes.

**Comment by killergerbah** [comment]
What site is this happening on?
Can you also capture a video of this?

**Comment by ludie1** [comment]
It's happening on zoro.to. It doesn't happen often enough for me to be able to record it so I probably won't be able to.

**Comment by killergerbah** [comment]
@ludie1 Are you pausing the video and navigating away from the video tab? Asbplayer will eventually lose its connection to the video tab if you don't use the video tab for a while. In that case, you would need to resync the tab with asbplayer.

**Comment by ludie1** [comment]
That explains it, thanks for your work!
