### ISSUE TITLE
Button to make cards?

### ISSUE THREAD

**Issue by MohaKh1** [killergerbah/asbplayer#92]
For some reason Ctrl+Shift+Z is not letting me copy and open anki dialogue, any way to make a button with the same functionality?

**Comment by killergerbah** [comment]
Can you watch this video to make sure the shortcut is bound? https://youtu.be/wYWbgovfNlI

**Comment by MohaKh1** [comment]
I think I just have a problem with pressing multiple keys at a time, I changed the shortcut keys and it works

**Comment by aiko-tanaka** [comment]
> I think I just have a problem with pressing multiple keys at a time, I changed the shortcut keys and it works

How'd you change the shortcut key? I was thinking of choosing a custom shortcut as well

**Comment by MohaKh1** [comment]
On Microsoft edge
>>three dots on top right>>extensions >> keyboard shortcuts>> should show
you all extensions and any shortcuts available, you can customize it to
whatever key you want.

2021年11月2日(火) 午前8:38 田中愛子 ***@***.***>:

**Comment by aiko-tanaka** [comment]
Thanks, i guess this only works for streamed videos though.
@killergerbah , any chance of making the shortcuts editable for local playback as well?

**Comment by killergerbah** [comment]
@aiko-tanaka I'll make an issue for it

**Comment by MohaKh1** [comment]
Is it also possible to add a feature like 
after every subtitle:
auto pause

**Comment by killergerbah** [comment]
Button exists with side panel integration
