### ISSUE TITLE
[dev] Add Prettier to Project

### ISSUE THREAD

**Issue by Renji-XD** [killergerbah/asbplayer#95]
Hi,

was playing a bit with extension + code and noticed the default formatter of my ide reformats basically everything. 

To encourage pr contributions it maybe makes sense if you could add prettier+ whatever config you think makes sense to all (sub)modules and recommit all (reformatted) src files.. otherwise either you on the review or the dev while working on changes will get crazy ;)

**Comment by killergerbah** [comment]
Closed with https://github.com/killergerbah/asbplayer/pull/96 from @Renji-XD
