### ISSUE TITLE
Request: Fields for URL, tags in Anki Export

### ISSUE THREAD

**Issue by roboticsbrian** [killergerbah/asbplayer#98]
Please add fields for the URL where a card was mined (e.g. Youtube URL, possibly with timestamp?). That way, cards can have a link back to the source video, or even embed the video on the back of the card. 

Currently there is a "Source" field, but it populates with the filename of the subtitle file.

A field for tags that would be added to the card would be great as well. It would make it easier to look up cards mined with asbplayer in the Anki card browser.

**Comment by killergerbah** [comment]
53f348976fb4d172d1f882e0116c2cac76169bab
